Populating GIT from development system

diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_ext b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_ext
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_ext
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_ext
@@ -21,7 +21,7 @@
 # Copyright Dr. J. Pfennig (c) 2016-2024
 # ------------------------------------------------------------------------------
 
-CEN_MODULES['_centauri_bash_ext']='0.26:2'
+CEN_MODULES['_centauri_bash_ext']='0.27:3'
 
 CEN_EXT_TEMP=               # temp file base path, see tmpfile
 CEN_EXT_TIDX=               # ... auto index
@@ -244,7 +244,7 @@ copy() {
             $_omsg -a $"Removing destination before copy"": $_odes"
             remove $_orun ${_oflg/-p/} -d -- "$_odes" || return 1
         elif [ ! -w "$_odes" ] ; then
-            $_oerr $"Copy destination is not a writable"": $_odes" ; return 1
+            $_oerr $"Copy destination is not writable"": $_odes" ; return 1
         fi
     fi
 
@@ -624,10 +624,14 @@ prettypath() {
 # Return:   0   success
 #           1   error
 #           2   not a readable file (only without option -x)
+#
+#
+#           The function skips header lines starting with '#' and returns the
+#           1st line not starting with '#'. Trailing lines are ignored.
 # ------------------------------------------------------------------------------
 CEN_READLINE=
 readline() {
-    local _oerr='trace' _finp _oqui= _oarr _oexi _vnam='CEN_READLINE' _mesg
+    local _oerr='trace' _finp _oqui _oarr _oexi _vnam='CEN_READLINE' _mesg
     while [ "${1::1}" = '-' ] ; do
       case "$1" in
       --)   shift ; break ;;
@@ -647,14 +651,88 @@ readline() {
     if [ ! -r "$_finp" ] ; then
         [ -z "$_oexi" ] && return 2
         _mesg=$"Cannot read from:"" $_finp"
-    elif ! read $_oarr $_vnam <"$_finp" &>/dev/null ; then
+    else
+        while read $_oarr $_vnam ; do
+            eval "_mesg=\"\$$_vnam\""
+            [ "${_mesg::1}" = '#' ] && continue
+            [ -z "$_oqui" ] && $CEN_TRACE -a -c ' file OK' -- "$_finp"
+            return 0
+        done <"$_finp" &>/dev/null
         _mesg=$"Failed to read from:"" $_finp"
-    elif [ -z "$_oqui" ] ; then
-        trace -a -c ' file OK' -- "$_finp"
     fi
-
-    [ -z "$_mesg" ] && return 0
     $_oerr -- "$_mesg" ; return 1
+}
+
+# ------------------------------------------------------------------------------
+# writeline - write a single line of text
+#
+# Call:     (1) writeline [-c <text>] [-e|-f|-w] -o <file> [-m <mask>] [-t] [-q] <data>...
+#           (2) writeline [-c <text>] [-e|-f|-w] -h <hnum> [-q] <data>...
+#           (3) writeline [-c <text>] [-e|-f|-w] [-m <mask>] [-q] <data>...
+#
+#           This function writes data that can be retrieved by [[readline()]].
+#           Form (1) writes to a file, (2) to a file handle and (3) to **stdout**.
+#
+# Options:  -c  header comment text
+#           -e  report errors
+#           -f  make errors fatal
+#           -h  output to file handle
+#           -m  file mode (only bits 0666 are relevant)
+#           -o  output file path
+#           -q  no trace messages
+#           -t  truncate existing file
+#           -w  report errors as warnings
+#
+# Arguments:<data>  data to be written
+#           <file>  file path
+#           <hnum>  handle number
+#           <text>  header text ('-' for 'Created by ...')
+#
+# Return:   0   success
+#           1   write error
+#           2   destination exists
+#
+#.Examples: writeline -e -t -o 'some-file' -- write these words
+#
+#.          writeline -m 644 -q 'another-file' -- "This is data"
+#.          case $? in
+#.          1)  error "Write failed" ;;
+#.          2)  warning "Existing file not altered"
+#.          esac
+# ------------------------------------------------------------------------------
+writeline() {
+    local _oerr='trace' _fout _mask _oqui _orep _otxt
+    while [ "${1::1}" = '-' ] ; do
+      case "$1" in
+      --)   shift ; break ;;
+      -c)   [ "$2" = '-' ] && _otxt=$"Created by"" '$CEN_NAME'" || _otxt="$2"
+            shift ; _otxt="# $_otxt"$'\n' ;;
+      -e)   _oerr='error' ;;
+      -f)   _oerr='fatal' ;;
+      -h)   shift ; _fout="/dev/fd/$1" ; _orep=1 ;;
+      -m)   shift ; _mask="$1" ;;
+      -o)   shift ; _fout="$1" ;;
+      -q)   _oqui=1 ;;
+      -t)   _orep=1 ;;
+      -w)   _oerr='warning' ;;
+      *)    _cen_abort - "$1"
+      esac ; shift
+    done
+    if [ -z "$_fout" ] ; then
+        _fout='/dev/stdout'
+    elif [ -z "$_orep" ] && [ -e "$_fout" ] ; then
+        $_oerr -- $"Destination already exists:" "$_fout" ; return 2
+    fi
+    dryrun 'writeline' "$_fout" && return 0
+
+    [ -n "$_mask" ] && _cen_umask -s "$_mask"
+    if printf '%s%s\n' "$_otxt" "$*" >"$_fout" 2>/dev/null ; then
+        [ -n "$_mask" ] && _cen_umask -r
+        [ -z "$_oqui" ] && $CEN_TRACE -a -c ' OK' -- "$_fout"
+        return 0
+    fi
+    [ -n "$_mask" ] && _cen_umask -r
+    $_oerr -- $"Failed to write:" "$_fout" ; return 1
 }
 
 # ------------------------------------------------------------------------------
@@ -1384,7 +1462,7 @@ suffixpath() {
 # see form (4).
 # ------------------------------------------------------------------------------
 symlink() {
-    local _fign _targ _ocan _odir _oftl='error' _onck _orel _osys='-e -p' _move _mesg="$CEN_TRACE"
+    local _fign _targ _ocan _odir _oftl='error' _onck _orel _osil _osys='-e -p' _move _mesg="$CEN_TRACE"
     while [ "${1::1}" = '-' ] ; do
       case "$1" in
       --)   shift ; break ;;
@@ -1396,7 +1474,7 @@ symlink() {
       -n)   _onck='-f' ;;
       -q)   _oftl=':' ; _osys='-q' ;;
       -r)   _orel=1 ;;
-      -s)   _mesg=: ;;
+      -s)   _mesg=: ; _osil='-s' ;;
       -v)   _mesg='message' ;;
       -w)   _oftl='warning' ; _osys='-w -p' ;;
       -x)   _move=0 ;;
@@ -1428,14 +1506,14 @@ symlink() {
     # move existing link away
     if [ -e "$_link" ] ; then
         if [ "$_move" = 0 ] ; then              # always delete ...
-            remove -d -- "$_link" || return 2
+            remove $_osil -d -- "$_link" || return 2
         elif [ -h "$_link" ] ; then
             if [ -n "$_move" ] ; then
-                remove -- "$_link"              # do not dereference
+                remove $_osil -- "$_link"       # do not dereference
             elif [ "$_targ" -ef "$_link" ] ; then
                 $_mesg -a -c $"Link is current" "$_link" ; return 0
             elif [ -z "$_odir" -a -n "$_onck" ] && [ -d "$_link" ] ; then
-                remove -d -- "$_link"           # do not dereference
+                remove $_osil -d -- "$_link"           # do not dereference
             fi
         elif [ -n "$_move" ] ; then             # move it away ...
             sysrun $_osys -b -- mv -f -- "$_link" "$_link.$CEN_NAME" || return 2
@@ -1979,7 +2057,7 @@ walk() {
       --)   shift ; break ;;
       -a)   _fadd=1 ;;
       -b)   _fbro=1 ;;
-      -c)   _fexc="filter --" ;;
+      -c)   _fexc='filter --' ;;
       -d)   shift; _fdir="$1" ;;
       -e)   shift; _fext+=("$1") ;;
       -f)   shift; _ffil="$1" ;;
@@ -1987,7 +2065,7 @@ walk() {
       -l)   shift; _levl="$1" ;;
       -n)   _fnod=1 ;;
       -r)   _frec=1 ;;
-      -i)   _fexc="filter -i --" ;;
+      -i)   _fexc='filter -i --' ;;
       *)    _cen_abort - "$1"
       esac ; shift
     done
@@ -2036,18 +2114,20 @@ walk() {
                 [ -n "${CEN_WALK_DMAP[$_full]}" ] && continue
                 CEN_WALK_DMAP[$_full]="$_item"
                 _stat=0
-                if [ "$_ffil" = "false" ] ; then  # --incl/--excl
+                if [ "$_ffil" = 'false' ] ; then  # --incl/--excl
                     $_fexc "${_full##*/}" ; _stat=$?
                 fi
                 if [ "$_stat" = 0 ] ; then
                     $_fdir "$_full" "$_item" ; _stat=$?
                 fi
-                [ "$_stat" -ge 3 ] && break
-                [ "$_stat" = 0 ] && CEN_WALK_DIRS+=("$_full")
-                [ -z "$_frec" -o "$_stat" = 2 ] && continue
+                case "$_stat" in
+                0)  CEN_WALK_DIRS+=("$_full") ;;
+                1)  _stat=0 ;;
+                2)  _stat=0 ; continue ;;
+                *)  break
+                esac
                 [ "$CEN_WALK_LEVEL" -gt "$_levl" ] && continue
 
-                _stat=0
                 if [ -n "$_fhid" ] ; then
                     _cen_walk "$_item"/.[!.]* "$_item"/* || _stat=$?
                 else
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricleanup b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricleanup
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricleanup
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricleanup
@@ -1,10 +1,10 @@
-#!/bin/bash
+#!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2016-2023; BSD License"
-CEN_TITLE="Cleanup caches and logfiles"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2016-2024; "$"BSD License"
+CEN_TITLE=$"Cleanup caches and logfiles"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -r -y - "0.14:2" || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -r -t -y - '0.15:4' || exit 2
 
 # Data
 CEN_OPT_ALL=                    # see --all
@@ -28,8 +28,8 @@ do_delete() {
     # check for symlink or root folder
     ___check() {
         [ -h "$1" ] && return 1
-        [ -n "$CEN_OPT_DRYRUN" ] && trace -a "Removing files/folders: $*"
-        [ "$1" -ef "/" ] && fatal "Refusing to delete the root folder"
+        [ -n "$CEN_OPT_DRYRUN" ] && trace -a $"Removing files/folders:" "$*"
+        [ "$1" -ef "/" ] && fatal $"Refusing to delete the root folder"
         return 0
     }
 
@@ -42,13 +42,13 @@ do_delete() {
     ___fcont() {
         [ -d "$1" ] || return
         ___check "$1" || return
-        [ -z "$CEN_OPT_DRYRUN" ] && trace -a "Removing files/folders: $*"
+        [ -z "$CEN_OPT_DRYRUN" ] && trace -a $"Removing files/folders:" "$*"
         system -e -p -- find -H "$1" -xdev -mindepth 1 -type d -depth -print
         system -e -p -- find -H "$1" -xdev \
             \( -name WARNING_FOLDER_NOT_ARCHIVED -o -name CACHEDIR.TAG \) -prune -o -exec rm {} \;
     }
 
-    [ "$#" = 1 ] || fatal -t "Exactly 1 argument expected"
+    [ "$#" = 1 ] || fatal -t $"Exactly one argument expected"
     local sifs="$IFS" ; IFS= ; set -- $1 ; IFS="$sifs"
     local fldr
     for fldr in "$@" ; do
@@ -89,10 +89,10 @@ do_zero() {
 # Workers
 # ------------------------------------------------------------------------------
 run_root() {
-    message -a "Cleaning system caches"": $PWD"
+    message -a $"Cleaning system caches:" "$PWD"
 
     do_delete ".Trash-*"
-    do_delete "./tmp/"
+    do_delete './tmp/'
 
     if [ -d "./var" ] ; then
         do_delete ".$CEN_ROOT/backup/"
@@ -118,7 +118,7 @@ run_home() {
     # clean a home folder: <folder>
     ___home() {
         joinpath -p -- "$PWD" "${1#./}"
-        message -a "Cleaning user caches  : $CEN_JOINPATH"
+        message -a $"Cleaning user caches  :" "$CEN_JOINPATH"
         do_delete "$1/.xsession-errors*"
         do_delete "$1/.audacity-data"
         do_delete "$1/.davfs2/"
@@ -153,36 +153,36 @@ run_home() {
 
     # clean sub folders: <folder>
     ___walk() {
-        walk -r -l 1 -d "___home" "$1"
+        walk -r -l 1 -d ___home "$1"
     }
 
-    local path="/home"
+    local path='/home'
 
     # home subvolume
     if [ -n "$CEN_OPT_HOME" ] ; then
-        confirm -a -n "Cleanup '$PWD' caches" || return
-        ___walk "."
+        confirm -a -n -f $"Cleanup '%s' caches" "$PWD" || return
+        ___walk '.'
         [ -n "$1" ] && ___home "$1"
 
     # given user name
     elif [ "$CEN_OPT_USER" != "+" ] ; then
         [ "$CEN_OPT_USER" = "-" ] && CEN_OPT_USER="$LOGNAME"
         eval path=~$CEN_OPT_USER
-        [ "$PWD" = "/" ] || path="$PWD$path"
+        [ "$PWD" = '/' ] || path="$PWD$path"
         if [ -d "$path" ] ; then
-            confirm -a -n "Cleanup '$path' caches" || return
+            confirm -a -n -f $"Cleanup '%s' caches" "$path" || return
             folder -r -c -f "$path/.."
             ___home "./${path##*/}"
         else
-            warning "User home folder not found" ": $path"
+            warning $"User home folder not found:" "$path"
         fi
 
     # all users
     else
-        [ "$PWD" = "/" ] || path="$PWD$path"
-        confirm -a -n "Cleanup '$path' caches" || return
-        [ -d "./home" ] && ___walk "home"
-        [ -d "./root" ] && ___home "./root"
+        [ "$PWD" = '/' ] || path="$PWD$path"
+        confirm -a -n -f $"Cleanup '%s' caches" "$path" || return
+        [ -d "./home" ] && ___walk 'home'
+        [ -d "./root" ] && ___home './root'
         [ -d ".$CEN_ROOT/vbox" ] && ___home ".$CEN_ROOT/vbox"
     fi
 }
@@ -209,9 +209,9 @@ run_logs() {
     resolve -a flis -e -m -p -q -- "./root/.synaptics/log" "./var/backups"/* "./var/log/samba/cores"/*
     remove -d -- "${flis[@]}"
 
-    if [ -d "./var/log" ] ; then
+    if [ -d './var/log' ] ; then
         local curr="$PWD"
-        folder -c -f "./var/log"
+        folder -c -f './var/log'
 
         # using persistent systemd journal: remove legacy logs
         if [ -d "journal" ] ; then
@@ -238,7 +238,7 @@ run_logs() {
 run() {
     # option handling
     if [ -n "$CEN_OPT_ALL" ] ; then
-        CEN_OPT_ROOT=1 ; CEN_OPT_USER="+" ; CEN_OPT_ZERO=1
+        CEN_OPT_ROOT=1 ; CEN_OPT_USER='+' ; CEN_OPT_ZERO=1
     fi
     [ -n "$CEN_OPT_ZERO" ] && CEN_OPT_LOGS=1
 
@@ -247,21 +247,21 @@ run() {
     if ! [ "$CEN_OPT_USER" = "-" -o "$CEN_OPT_USER" = "$LOGNAME" ] ; then
         context -r
     elif [ -n "$CEN_OPT_LOGS" -o -n "$CEN_OPT_HOME" -o -n "$CEN_OPT_ROOT" ] ; then
-        fatal "Option --user conflicts with --all|--root|--home|--log"
+        fatal $"Option --user conflicts with --all|--root|--home|--log"
     fi
 
     # should not be a desktop session
     if [ -z "$CEN_OPT_BASE" ] && [ -n "$KDE_SESSION_VERSION" -o -n "$XDG_CURRENT_DESKTOP" ] ; then
-        confirm -a -n "You should not call $CEN_NAME from a desktop session. Continue" || return
+        confirm -a -n $"You should not use this tool in a desktop session. Continue" || return
     fi
 
     # do it ...
     folder -c "${CEN_OPT_BASE:-/}" || return
 
-    if [ -d "Volumes/Root" -o -d "Volumes/Home" ] ; then
-        message -a "Base folder is a BTRFS volume"
-        [ "${CEN_OPT_USER:-+}" = "+" ] || fatal "Cannot use '--user=<name>' in this context"
-        CEN_OPT_HOME=1 ; DAT_ROOT="Volumes/Root" ; DAT_HOME="Volumes/Home"
+    if [ -d 'Volumes/Root' -o -d 'Volumes/Home' ] ; then
+        message -a $"Base folder is a BTRFS volume"
+        [ "${CEN_OPT_USER:-+}" = '+' ] || fatal $"Cannot use '--user=<name>' in this context"
+        CEN_OPT_HOME=1 ; DAT_ROOT='Volumes/Root' ; DAT_HOME='Volumes/Home'
         if [ ! -d "$DAT_ROOT" ] ; then
             CEN_OPT_LOGS= ; CEN_OPT_ROOT=
         fi
@@ -277,19 +277,19 @@ run() {
     fi
 
     local mlst
-    [ -n "$CEN_OPT_ROOT" ] && mlst+="root, "
-    [ -n "$CEN_OPT_USER" ] && mlst+="home, "
-    [ -n "$CEN_OPT_LOGS" ] && mlst+="logs, "
+    [ -n "$CEN_OPT_ROOT" ] && mlst+='root, '
+    [ -n "$CEN_OPT_USER" ] && mlst+='home, '
+    [ -n "$CEN_OPT_LOGS" ] && mlst+='logs, '
     if [ -z "$mlst" ] ; then
-        message -a "Nothing to cleanup" ; return
+        message -a $"Nothing to clean up" ; return
     elif [ -n "$CEN_OPT_LOGS" -o -n "$CEN_OPT_ROOT" ] ; then
-        confirm -a -n "Cleanup '${mlst::-2}' data at '$PWD'" || return
+        confirm -a -n -f $"Cleanup '%s' data at '%s'" "${mlst::-2}" "$PWD" || return
     fi
 
     local root curr=$PWD
         if [ -n "$DAT_ROOT" ] ; then
             folder -c -f "$DAT_ROOT"
-            [ -d "root" ] && root="$PWD/root"
+            [ -d 'root' ] && root="$PWD/root"
         fi
         [ -n "$CEN_OPT_ROOT" ] && run_root
         [ -n "$CEN_OPT_LOGS" ] && run_logs
@@ -307,21 +307,21 @@ options() {
     case "$1" in
 
     -A|--all)
-        optarg "all"    CEN_OPT_ALL        ;;   # simple flag
+        optarg 'all'    -                  ;;   # simple flag
     -B|--bas|--base)
-        optarg "base"   CEN_OPT_BASE -d    ;;   # folder
+        optarg 'base'   -            -d    ;;   # folder
     -H|--hom|--home)
-        optarg "home"   CEN_OPT_HOME       ;;   # simple flag
+        optarg 'home'   -                  ;;   # simple flag
     -L|--log*)
-        optarg "logs"   CEN_OPT_LOGS       ;;   # simple flag
+        optarg 'logs'   -                  ;;   # simple flag
     -S|--sna*)
-        optarg "snap"   CEN_OPT_SNAP       ;;   # simple flag
+        optarg 'snap'   -                  ;;   # simple flag
     -R|--roo|--root)
-        optarg "root"   CEN_OPT_ROOT       ;;   # simple flag
+        optarg 'root'   -                  ;;   # simple flag
     -U|--use|--user)
-        optarg "user"   CEN_OPT_USER -t    ;;   # any text
+        optarg 'user'   -            -t    ;;   # any text
     -Z|--zer|--zero)
-        optarg "zero"   CEN_OPT_ZERO       ;;   # simple flag
+        optarg 'zero'   -                  ;;   # simple flag
     esac
 }
 
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurihass b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurihass
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurihass
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurihass
@@ -1,34 +1,117 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Dr. J. Pfenig (c) 2023-2024; BSD License"
-CEN_TITLE=$"Tool to (un)install and run Home Assistant"
+CEN_LEGAL='Dr. J. Pfenig (c) 2023-2024; '$"BSD License"
+CEN_TITLE=$"Tool to (un)install and run Homeassistant Core"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -y - '0.14:2' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -y - '0.20:4' || exit 2
 
 # Data
 DAT_BASE='/opt/HomeAssistant'
 DAT_HOME="$DAT_BASE/home"
 DAT_VENV="$DAT_BASE/homeassistant"
+DAT_ENAB="$DAT_VENV/service-enabled"    # see autorun
+DAT_SERV="$CEN_NAME"                    # service name
+
+DAT_VERSION_311='2024.3.3'              # last python 3.11 version
+DAT_VERSION_312='2024.9.3'              # known working python 3.11 version
 
 # data for extra options
-CEN_OPT_VERSION='2024.1.6'
+CEN_OPT_QUIRK=                          # installation quirks
+CEN_OPT_USER='homeassistant'
+CEN_OPT_VERSION="$DAT_VERSION_312"
+
+# ------------------------------------------------------------------------------
+# Is HA installed at all?
+# ------------------------------------------------------------------------------
+check_installed() {
+    [ -d "$DAT_VENV/bin" ] && return 0
+    message "Homeassistant not found, run '$CEN_NAME install' to install it"
+    error -s 2                          # set exit code
+    return 1
+}
+
+# ------------------------------------------------------------------------------
+#
+# ------------------------------------------------------------------------------
+vers_compare() {
+    local arg1=(${1//./ } 0 0 0) arg2=(${2//./ } 0 0 0)
+    [ "${arg1[0]}" -gt "${arg2[0]}" ] && return 2
+    [ "${arg1[0]}" -lt "${arg2[0]}" ] && return 1
+    [ "${arg1[1]}" -gt "${arg2[1]}" ] && return 2
+    [ "${arg1[1]}" -lt "${arg2[1]}" ] && return 1
+    [ "${arg1[2]}" -gt "${arg2[2]}" ] && return 2
+    [ "${arg1[2]}" -lt "${arg2[2]}" ] && return 1
+    return 0
+}
+
+# ------------------------------------------------------------------------------
+#
+# ------------------------------------------------------------------------------
+vers_quirk() {
+    system -f -c python
+
+    if [ -z "$CEN_OPT_QUIRK" ] ; then
+        CEN_OPT_QUIRK=0
+        vers_compare "$CEN_OPT_VERSION" "$DAT_VERSION_311"
+        if [ $? = 2 ] ; then
+            local vers ; system -q -r -s vers -- python -V ; vers="${vers#* }"
+            vers_compare "$vers" '3.12.0'
+            if [ $? = 1 ] ; then
+                warning -p $"Installed python is '%s' - activating --quirk=1" "$vers"
+                ((CEN_OPT_QUIRK |= 1))
+            fi
+        fi
+    fi
+
+    ((CEN_OPT_QUIRK & $1))                      # get status
+}
+
+# ------------------------------------------------------------------------------
+#
+# ------------------------------------------------------------------------------
+vers_setup() {
+    if [ "$1" = '-c' ] ; then
+        while [ -e "$DAT_VENV" ] ; do
+            confirm -y $"Remove existing python environment (recommended)" || break
+            remove -d -- "$DAT_VENV"
+            error -t || return 1 ; break
+        done
+
+        if vers_quirk 1 ; then
+            system -p -- python3.12 -m venv "$DAT_VENV" || return 1
+        else
+            system -p -- virtualenv "$DAT_VENV" || return 1
+        fi
+        message -a $"Created python environment:" "$DAT_VENV"
+    fi
+    [ -s "$DAT_VENV/bin/activate" ] && source "$DAT_VENV/bin/activate" && return 0
+    error $"Failed to activate python environment:" "$venv"
+}
 
 # ------------------------------------------------------------------------------
 # Home Assistant service: on|off|status
 # ------------------------------------------------------------------------------
 actionAutorun() {
-    folder -b 'persistent' -c -f
-    local word
+    check_installed || return
+    local word vsee="# This file is a start condition for '$DAT_SERV.service'"
+
     if ! listsearch -u -m word -- "${1:-status}" 'on' 'off' 'status' ; then
-        invoke -e "Argument must be one of: on off status" ; return
+        invoke -a 'on off status' ; return
     fi
-# TODO autologin
+
+    # we use 'service-enabled' to control if HA should run or not. This is why
+    # we only enable the service but never disable it. The service unit checks
+    # for file 'service-enabled'.
+
+    # The 'centaurisysinit' service starts '$DAT_SERV', even if not
+    # enabled, when kernel parameter 'centaurilogin=HomeAssistant' is set.
+
     case "$word" in
-    on)     create -- 'centaurihass.enabled'
-            system -q systemctl is-enabled 'centaurihass.service' || system -e -p \
-                systemctl enable "$CEN_ROOT/systemd/system/centaurihass.service"  ;;
-    off)    remove -- 'centaurihass.enabled' ;;
+    on)     create -- "$DAT_ENAB"
+            system -q systemctl is-enabled "$DAT_SERV" || system -e -p \
+                systemctl enable "$CEN_ROOT/systemd/system/$DAT_SERV.service"  ;;
+    off)    remove -- "$DAT_ENAB" ;;
     *)      actionStatus
     esac
 }
@@ -37,10 +120,32 @@ actionAutorun() {
 # Home Assistant dependencies: -no args-
 # ------------------------------------------------------------------------------
 actionDeps() {
-    system -e -u - apt-get install -y python3 python3-dev python3-venv \
+    embed -v -y centauripackage -s -y -I -L -T -X python3 python3-dev python3-venv \
         python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
         autoconf build-essential libopenjp2-7 libtiff6 libturbojpeg0-dev \
-        tzdata ffmpeg liblapack3 liblapack-dev libatlas-base-dev
+        tzdata ffmpeg liblapack3 liblapack-dev libatlas-base-dev virtualenv
+    error -t || return 1
+
+    if vers_quirk 1 ; then
+        if [ -n "$CEN_OPT_FORCE" ] || [ ! -s '/etc/apt/keyrings/deb-pascalroeleven.gpg' ] ; then
+            tmpfile -r || return 1
+            system -e  -u _apt -- wget -qO- 'https://pascalroeleven.nl/deb-pascalroeleven.gpg' \
+                >"$CEN_TMPFILE" && copy "$CEN_TMPFILE" '/etc/apt/keyrings/deb-pascalroeleven.gpg'
+
+        fi
+        error -t || return 1
+        create -c ${CEN_OPT_FORCE:+-t} -- '/etc/apt/sources.list.d/pascalroeleven.sources' <<!EOF
+Types: deb
+URIs: http://deb.pascalroeleven.nl/python3.12
+Suites: bookworm-backports
+Components: main
+Signed-By: /etc/apt/keyrings/deb-pascalroeleven.gpg
+!EOF
+        embed -t -v -y centauripackage -s -y -I -T -X -U1 python3.12 python3.12-venv python3.12-dev
+        error -t || return 1
+    fi
+
+    message -a $"Build dependencies are installed"
 }
 
 # ------------------------------------------------------------------------------
@@ -48,28 +153,60 @@ actionDeps() {
 #
 #   step 1: create folder, python, create user (needs root)
 #   step 2: build python stuff (must run as homeassistant)
+#   step 3: (optional) install mqtt broker
 # ------------------------------------------------------------------------------
 actionInstall() {
-    system -q -r -- getent passwd 'homeassistant' ||
-       system -f -p -- useradd -rm 'homeassistant' -d "$DAT_HOME" -G dialout,bluetooth
-    attributes -d -m - -o 'homeassistant:staff' -- "$DAT_BASE"
-    embed -r -t -u homeassistant -v -y -z -- \
+
+    # create HA user, add to dialout and bluetooth groups
+
+    if system -q -r -- getent passwd "$CEN_OPT_USER" ; then
+        system -e -p -- adduser "$CEN_OPT_USER" bluetooth
+        system -e -p -- adduser "$CEN_OPT_USER" dialout
+        if [ ! -d "$DAT_HOME" ] ; then
+            folder -f -m -- "$DAT_HOME"
+            copy -a "${CEN_PATHS[2]}/skel/".* "$DAT_HOME"
+            system chown -R "$CEN_OPT_USER:" "$DAT_HOME" ; system chmod 775 "$DAT_HOME"
+        fi
+    else
+       system -e -p -- useradd -rm "$CEN_OPT_USER" -d "$DAT_HOME" -G dialout,bluetooth
+    fi
+    error -t || return
+
+    # install HA
+
+    symlink "$DAT_HOME" "$CEN_ROOT/home/$CEN_OPT_USER"
+    attributes -d -m - -o "$CEN_OPT_USER:staff" -- "$DAT_BASE"
+    system -c virtualenv || actionDeps
+    embed -r -t -u "$CEN_OPT_USER" -v -y -z -- \
                    "$CEN_NAME" --version="$CEN_OPT_VERSION" setup install
+
+    # install mosquitto
+
+    local mosq
+    runservice enabled mosquitto
+    case $? in
+    0)  ;;
+    2)  warning $"The 'mosquittoo' mqtt broker service is masked" ;;
+    8)  warning $"The 'mosquittoo' mqtt broker service is disabled" ;;
+    64) confirm -y $"Also install 'mosquitto' mqtt broker" && mosq=1 ;;
+    *)  warning $"The 'mosquittoo' mqtt broker service may be broken"
+    esac
+    [ -n "$mosq" ] || return
+    embed -v -y centauripackage -s -y -I -T mosquitto mosquitto-clients
 }
 
 # ------------------------------------------------------------------------------
 # install/update Home Assistant core step 2: install|update
 # ------------------------------------------------------------------------------
 actionSetup() {
-    if [ "$USER" != 'homeassistant' ] ; then
-        invoke -e "The current user must be 'homeassistant'" ; return
+    if [ "$USER" != "$CEN_OPT_USER" ] ; then
+        invoke -e $"The current user must be '%s'" "$CEN_OPT_USER" ; return
     fi
 
     folder -c -f "$DAT_BASE"
-    system -f -p -r -- virtualenv "$DAT_VENV"
-    source "$DAT_VENV/bin/activate" || quit -e "python venv activate failed"
 
     if [ "$1" = 'install' ] ; then
+        vers_setup -c || return
         system -e -q -- python3 -m pip install wheel
         error -t || return
 
@@ -78,12 +215,13 @@ actionSetup() {
                 $'\n'"You can stop the installation now and continue later by running:" $'\n' \
                 $'\n'"    sudo $CEN_NAME --version='$CEN_OPT_VERSION' install" $'\n'" "
 
-        confirm -y "Continue to install homeassistant" || return
+        confirm -y $"Continue to install homeassistant" || return
 
         system -e -- pip3 install homeassistant=="$CEN_OPT_VERSION"
 
      else
-        confirm -y "Continue to update homeassistant" || return
+        vers_setup || return
+        confirm -y $"Continue to upgrade homeassistant" || return
         system -e -- pip3 install --upgrade homeassistant
      fi
 }
@@ -92,37 +230,61 @@ actionSetup() {
 # run Home Assistant: -no args-
 # ------------------------------------------------------------------------------
 actionRun() {
+    check_installed || return
     local verb ; [ "$CEN_VERB" -gt 1 ] && verb='-v'
-    system -e -u homeassistant -x -- "$DAT_VENV/bin/hass" $verb
+    system -e -u "$CEN_OPT_USER" -x -- "$DAT_VENV/bin/hass" $verb
 }
 
 # ------------------------------------------------------------------------------
 # Home Assistant shell: -no args-
 # ------------------------------------------------------------------------------
 actionShell() {
+    check_installed || return
     folder -c -f "$DAT_BASE"
-    system -e sudo -u homeassistant -H -s
+    system -e sudo -u "$CEN_OPT_USER" -H -s
 }
 
 # ------------------------------------------------------------------------------
 # show status: -no args-
 # ------------------------------------------------------------------------------
 actionStatus() {
-    folder -b 'persistent' -c -f
-    local word sise
+    check_installed || return
+    local word sise enab
 
-    system -q systemctl is-enabled 'centaurihass.service' &&
-        sise="enabled" || sise="not enabled"
+    system -q systemctl is-enabled "$DAT_SERV" && enab=1
 
-    [ -f 'centaurihass.enabled' ] && word="on" || word="off"
-    message -a -p "Autorun: %s   Service: %s" "$word" "$sise"
+    [ -n "$enab" ] && sise=$"enabled" || sise=$"not enabled"
+    [ -f "$DAT_ENAB" ] && word=$"on" || word=$"off"
+    message -a -p $"Autorun: %s   Service: %s" "$word" "$sise"
+
+    [ -z "$enab" ] && return
+    message -a
+    system -e systemctl status "$DAT_SERV"
 }
 
 # ------------------------------------------------------------------------------
 # run systemctl: -no args-
 # ------------------------------------------------------------------------------
 actionSystemctl() {
-    system -e -p -z systemctl "$CEN_ACTION" "$CEN_NAME"
+    check_installed || return
+
+    # centaurisysinit uses 'centaurihass --quiet --force start' ...
+    local temp
+    if [ -n "$CEN_OPT_FORCE" ] ; then
+        if [ "$CEN_ACTION" = 'start' ] && [ ! -e "$DAT_ENAB" ] ; then
+            temp=1 ; create -- "$DAT_ENAB"          # enable temporarily
+        fi
+    elif [ ! -e "$DAT_ENAB" ] ; then
+        error -m "Service '$DAT_SERV' is not enabled. Please" \
+                 "run '$CEN_NAME auto on' to enable or use option '--force'"
+        return
+    fi
+
+    local list=("$DAT_SERV") coun=30
+    [ -d '/etc/mosquitto' ] && list+=('mosquitto')
+    trace -a -c "Start services" "${list[*]}"
+    system -e -p -z systemctl --no-block "$CEN_ACTION" "${list[@]}"
+    [ -n "$temp" ] && remove -- "$DAT_ENAB"
 }
 
 # ------------------------------------------------------------------------------
@@ -130,20 +292,45 @@ actionSystemctl() {
 # ------------------------------------------------------------------------------
 actionUninst() {
     if [ ! -d "$DAT_VENV" ] ; then
-        warning "No known 'Home Assistant' installation" ; return
+        warning $"No known 'homeassistant' installation" ; return
     fi
     folder -c -f "$DAT_VENV"
-    confirm -n "Uninstall Home Assistant" || return
+    confirm -n $"Uninstall homeassistant" || return
     remove -d -- bin/ cache/ include/ lib/ share/ pyvenv.cfg LICENSE
     actionAutorun off
-    message -a "Please remove folder '$DAT_VENV' and user 'homeassistant' manually"
+    message -a -p $"Please remove folder '%s' and user '%s' manually" "$DAT_VENV" "$CEN_OPT_USER"
 }
 
 # ------------------------------------------------------------------------------
 # upgrade Home Assistant: -no args-
 # ------------------------------------------------------------------------------
 actionUpgrade() {
-    embed -r -t -u homeassistant -v -y -z -- "$CEN_NAME" setup upgrade
+    check_installed || return
+    embed -r -t -u "$CEN_OPT_USER" -v -y -z -- "$CEN_NAME" setup upgrade
+}
+
+# ------------------------------------------------------------------------------
+# Show web interface: [<url>]
+# ------------------------------------------------------------------------------
+actionWeb() {
+    context -g 1                                # always try gui mode
+    local wurl="${1:--}" mode
+    if [ "$wurl" = '-' ] ; then
+        if [ -f "$DAT_ENAB" ] && system -q systemctl is-enabled "$DAT_SERV" ; then
+            if ! embed centauriroute wait localhost 8123 30 ; then
+                error $"Local 'homeassistant' instance not responding" ; return
+            fi
+            wurl="http://localhost:8123"
+        elif nethost 'homeassistant' || nethost 'hass' ; then
+            wurl="http://$_nethost_ip:8123"
+        else
+            invoke -e $"Please specify the 'homeassistant' URL to use" ; return
+        fi
+    fi
+
+#    [ "$USER" = "$CEN_OPT_USER" ] && mode='kiosk' || mode='view'
+#    embed -x -v centaurilauncher --gui=1 --port=8123 "$mode" "$wurl"
+    embed -x -v centaurilauncher --gui=1 --geom=+:+ view "$wurl"
 }
 
 # ------------------------------------------------------------------------------
@@ -152,6 +339,10 @@ actionUpgrade() {
 options() {
     case "$1" in
 
+    -Q|--qui*)
+        optarg 'quirk'      -       -n ;;       # numeric arg
+    -U|--use|--user)
+        optarg 'user'       -       -t ;;       # any text
     -V|--vers*)
         optarg 'version'    -       -t ;;       # any text
 
@@ -167,24 +358,26 @@ actions() {
     aut*)
         invoke -r 'autorun' -        0 1 ;;     # one optional arg
     dep*)
-        invoke -r 'deps'    -          0 ;;
+        invoke -r 'deps'    -          0 ;;     # no args
     ins*)
         invoke -r 'install' -          0 ;;     # no args
     run)
         invoke -r 'run'     -          0 ;;     # no args
     set*)
-        invoke    'setup'   -          1 ;;
+        invoke    'setup'   -          1 ;;     # one optional arg
     sh*|log*)
-        invoke -r 'shell'   -          0 ;;
+        invoke -r 'shell'   -          0 ;;     # no args
     uni*)
-        invoke -r 'uninst'  -          0 ;;
+        invoke -r 'uninst'  -          0 ;;     # no args
     upg*)
-        invoke    'upgrade' -          0 ;;
+        invoke    'upgrade' -          0 ;;     # no args
+    web)
+        invoke    'web'     -        0 1 ;;     # one optional arg
 
     status)
-        invoke    -         -          0 ;;
+        invoke    -         -          0 ;;     # no args
     start|stop|restart)
-        invoke -r -  actionSystemctl   0 ;;
+        invoke -r -  actionSystemctl   0 ;;     # no args
     esac
 }
 
@@ -194,10 +387,12 @@ actions() {
 usage() {
     usageset \
         -o - \
+        -o '-Q --quirk   <bits>'  $"a bit mask of quirks to be applied" \
+        -o '-U --user    <user>'  $"specify a different user (default: homeassistant)" \
         -o '-V --version <vers>'  $"homeassistant version (default: $CEN_OPT_VERSION)" \
 
     usageset \
-        -a 'autorun      <auto>'  $"behaviour of 'centaurihass.service'" \
+        -a 'autorun      <auto>'  $"behaviour of service '$DAT_SERV'" \
         -a 'deps'                 $"install build dependencies" \
         -a 'install'              $"install homeassistant core" \
         -a 'run'                  $"run homeassistant 'hass' binary" \
@@ -205,23 +400,30 @@ usage() {
         -a 'shell'                $"open a shell as user homeassistant" \
         -a 'uninstall'            $"uninstall homeassistant" \
         -a 'upgrade'              $"upgrade homeassistant" \
+        -a 'web         [<url>]'  $"show homeassistant web interface" \
         -a - \
-        -a 'start'                $"run ""'systemctl start $CEN_NAME'" \
-        -a 'status'               $"... ""'systemctl status $CEN_NAME'" \
-        -a 'stop'                 $"... ""'systemctl stop $CEN_NAME'" \
+        -a 'start'                $"run ""'systemctl start $DAT_SERV'" \
+        -a 'status'               $"... ""'systemctl status $DAT_SERV'" \
+        -a 'stop'                 $"... ""'systemctl stop $DAT_SERV'" \
 
     usageset \
         -p '<auto>'               $"one of: on off status" \
+        -p '<bits>'               $"1 - https://github.com/pascallj/python3.12-backport'" \
+        -p '<user>'               $"linux user name" \
+        -p '<url>'                $"something like 'http://your-host:8123'" \
         -p '<vers>'               $"homeassistant version to install" \
 
     usageset \
-        -t $"To run homeassistant as a service enter:"\
+        -t $"To start Homeassistant Core at boot time as a service enter:"\
         -t - \
-        -t "    $CEN_NAME autorun on        # enable service " \
-        -t "    $CEN_NAME autorun off       # disable service " \
+        -t "°   $CEN_NAME autorun on        # "$"enable service" \
+        -t "°   $CEN_NAME autorun off       # "$"disable service" \
         -t - \
-        -t $"Action 'autorun' also creates or removes the '$CEN_NAME.enabled'" \
+        -t $"Action 'autorun' also creates or removes the '${DAT_ENAB##*/}'" \
         -t $"file that is checked by the service as a start condition." \
+        -t - \
+        -t $"Run 'centausysinit default homeassistant' if you want your machine to" \
+        -t $"start in kiosk mode with homeassistant web interface at boot time." \
 
     usageset \
         -e $"# A full build on a raspberry pi can take about one hour, in particular" \
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurilauncher b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurilauncher
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurilauncher
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurilauncher
@@ -1,11 +1,11 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Dr. J. Pfennig (c) 2022; BSD License"
+CEN_LEGAL="Dr. J. Pfennig (c) 2022-2024; BSD License"
 CEN_TITLE=$"Launcher for GUI or Console Applications"
 CEN_UTL_STIME="$EPOCHREALTIME"
 
 # Import the bash library
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -t - '0.01:1' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -g -t - '0.20:4' || exit 2
 
 embed -m _centauri_bash_dbg
 embed -c _centauri_bash_run         # dependency for standalone build
@@ -13,6 +13,7 @@ embed -c _centauri_bash_run         # dependency for standalone build
 # Data
 CEN_OPT_DESKTOP=                    # see --session
 CEN_OPT_FOLDER=                     # see --folder
+CEN_OPT_GEOMETRY=                   # see --geometry
 CEN_OPT_HOST=                       # see --host
 CEN_OPT_MODE=                       # see --mode
 CEN_OPT_PORT=                       # see --port
@@ -25,8 +26,10 @@ DAT_WEBTMP=                         # delete folder/file in quit hook
 DAT_CGIDIR=
 DAT_WEBURL=                         # set by webapp
 DAT_SYNCPIPE=                       # handle of open synchronization pipe
+DAT_MASTER=
 
 DAT_FOLDER=
+DAT_GEOM=
 DAT_HOST=                           # remote host (kiosk, browser)
 DAT_PORT=
 DAT_URL=()                          # set by application_url()
@@ -87,6 +90,135 @@ DAT_QUIT_LIST=                      # quit hook
 # centauribuilder: text ectraction - white/black list - file ; charset=binary
 #
 # ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+#
+#   URL or file arguments:  <config items> <command line items>
+#   Heuristics:             file:// http://
+#
+#   processing is from right to left
+#
+# ------------------------------------------------------------------------------
+# Add url entries to DAT_URL() array
+# ------------------------------------------------------------------------------
+url_builder() {
+    local _item
+    while [ $# -gt 0 ] ; do
+        _item="$1" ; shift
+        case "$_item" in
+        file:/)     [ -z "$DAT_HOST$DAT_PORT" ] && DAT_URL+=("$_item") ;;
+        file:/*)    DAT_URL+=("$_item") ;;
+        http://*)   DAT_URL+=("$_item") ;;
+        *//*|*\\*)  invoke -w $"Invalid URL/file syntax"": $_item" ;;
+        */*)        prettypath -n -s _item ; DAT_URL+=("file:$_item") ;;
+        *.*.*.*)    DAT_URL+=("http://$_item") ;;
+        *:*:*)      DAT_URL+=("http://$_item") ;;
+        *)          prettypath -n -s _item ; DAT_URL+=("file:$_item") ;;
+        esac
+    done
+}
+
+url_http() {
+    # host port try...
+    # --------------------------------
+    # no   no   localhost:{80,http_proxy,8123}
+    # no   no   <master>:{80,8123}
+    # no   no   duckduckgo.com
+    # no   yes  localhost:<port>
+    # no   yes  <mast>:<port>
+    # yes  no   <host>::{80,8123}
+    # yes  yes  <host>:<port>
+    # --------------------------------
+
+    ___url_try() {
+        local _host="${1:--}"
+
+        if [ "$_host" = '-' ] ; then
+            [ -z "$DAT_MASTER" ] && netquery -q -s DAT_MASTER current
+            [ -z "$DAT_MASTER" ] && netquery -q -s DAT_MASTER MASTER
+            [ -z "$DAT_MASTER" ] && return 1
+            _host="$DAT_MASTER"
+        elif [ "$_host" = '+' ] ; then
+            launcher -a _host -k '-flags:def_http' || return 1
+        fi
+
+        while [ $# -gt 1 ] ; do
+            shift ; [ -n "$1" ] || continue
+            trace -a -c "url probe" "$_host $1"
+            system -r -n -q netcat -w 1 -z "$_host" "$1" || continue
+            [ "$1" != '80' ] && _host+=":$1"
+            ___url_vurl="http://$_host" ; return 0
+        done
+        return 1
+    }
+
+    local ___url_vurl
+    system -f -c netcat
+
+    while : ; do
+        case "$DAT_HOST/$DAT_PORT" in
+        /)      ___url_try 'localhost'   80 "$DAT_PROXY" 8123 && break
+                ___url_try "$DAT_MASTER" 80              8123 && break
+                ___url_try '+'           80                   && break
+                ;;
+        /*)     ___url_try 'localhost'   "$DAT_PORT"          && break
+                ___url_try "$DAT_MASTER" "$DAT_PORT"          && break
+                ;;
+        */)     ___url_try "$DAT_HOST"    80             8123 && break
+                ;;
+        *)      ___url_try "$DAT_HOST"   "$DAT_PORT"     8123 && break
+        esac ; break
+    done
+    printf -v "$1" '%s' "$___url_vurl"
+    [ -n "$___url_vurl" ]                               # return status
+}
+
+url_finder() {
+    local _coun="${#DAT_URL[@]}" _item _file
+    trace -a -c "url finder" "entries: $_coun"
+
+    while ((_coun--)) ; do
+        _item="${DAT_URL[_coun]}"
+        trace -a -c "url entry" "$_item"
+        case "$_item" in
+            file:/)     launcher -a _file -k '-flags:def_file'
+                        for _item in "${_file[@]}" ; do
+                            trace -a -c "url file" "$_item"
+                            [ -f "$_item" ] && break
+                            _item=
+                        done
+                        if [ -n "$_item" ] ; then
+                            _item="file:$_item" ; break
+                        fi ;;
+            file:/*#*)  _file="${_item:5}"
+                        [ -f "$_file" ] && break
+                        _file="${_file%#*}"
+                        if [ -f "$_file" ] ; then
+                            _item="file:$_file" ; break
+                        fi
+                        ;;
+            file:/*)    [ -f "${_item:5}" ] && break ;;
+            http://)    url_http _item && break ;;
+            *)          break
+        esac
+        _item=
+    done
+    if [ -z "$_item" ] ; then
+        trace -a -c "url finder" "no match"
+        DAT_URL=() ; return 1
+    fi
+    trace -a -c "url finder" "$_item"
+
+    # url encoding (partial)
+    _item="${_item//%/%25}" ; _item="${_item// /%20}"
+    _item="${_item//(/%28}" ; _item="${_item//)/%29}"
+    _item="${_item//+/%2B}" ; _item="${_item//,/%3C}"
+    _item="${_item//;/%3B}" ; _item="${_item//@/%40}"
+    _item="${_item//\[/%5B}" ; _item="${_item//\]/%5D}"
+    DAT_URL=("$_item") ; return 0
+}
+
+# ------------------------------------------------------------------------------
 # Config callback for html - find default html page
 # ------------------------------------------------------------------------------
 launcher_html() {
@@ -127,25 +259,12 @@ launcher_html() {
             esac ; shift
         done
     fi
-    # the remaining args should be html files or urls
 
-    # search url/file list backwards until an existing file is found
-    local _coun="$#" _indx _strt
-    while ((_coun--)) ; do
-        _indx=$((_coun + 1))
-        _strt="${!_indx}"
-        case "$_strt" in
-            /*)     [ -s "${_strt%#*}" ] && break || _strt= ;;
-            *)      break                       # not a file, use this url
-        esac
-    done
-
-
-    if [ "${_strt:--}" != '-' ] ; then
-        application_url "$_strt" || return 1
-        trace "html url:" "$DAT_URL"
-        args+=("$DAT_URL")
-    fi
+    # the remaining args should be html files or urls ...
+    shift ; [ $# = 0 ] && set -- 'http://'
+    DAT_URL=() ; url_builder "$@"
+    url_finder || quit $"No valid URL found" "($CEN_ACTION)"
+    args+=("$DAT_URL")
 
     # wait for synchronization pipe - see 'launcher_webapp'
     if [ -n "$DAT_SYNCPIPE" ] ; then
@@ -154,9 +273,6 @@ launcher_html() {
     fi
 
     launcher -x -m "$mode" $oerr -p -- "$appl" "${args[@]}"
-
-    ### BUG Firefox 2nd instance will terminate after passing cmd to 1st instance
-
     return 0
 }
 
@@ -339,7 +455,7 @@ $CEN_DEBUG -c -- "$@"
     done
 
     $CEN_DEBUG -c -- "$*"
-    local _pqml="$1" _titl ; shift
+    local _pqml="$1" _titl _full ; shift
     local _file _resx="${1:--}" _resy="${2:--}" _zoom="${3:--}"
     shift ; shift ; shift
 
@@ -349,31 +465,41 @@ $CEN_DEBUG -c -- "$@"
     #   qt5-qtquickcontrols2
     #   qt5-webengine5
 
-    # search url/file list backwards until an existing file is found
-    local _coun="$#" _indx _strt
-    while ((_coun--)) ; do
-        _indx=$((_coun + 1))
-        _strt="${!_indx}"
-        case "$_strt" in
-            /*)     [ -s "${_strt%#*}" ] && break || _strt= ;;
-            *)      break                       # not a file, use this url
-        esac
-    done
+    # the remaining args should be html files or urls ...
+    [ $# = 0 ] && set -- 'file://' 'http://'
+    DAT_URL=() ; url_builder "$@"
+    url_finder || quit $"No valid URL found" "($CEN_ACTION)"
+
+    # no proxy when port is given...
+    if [ "$DAT_URL" != "${DAT_URL%:*}" ] ; then
+        export http_proxy=
+        export https_proxy=
+    fi
+    trace -a -c "http proxy" "${http_proxy:-<none>}" "${https_proxy:-<none>}"
 
     # qml window geometry
+
     [ "${_ainf[0]:--}" != '-' ] && _resx="${_ainf[0]}"
     [ "${_ainf[1]:--}" != '-' ] && _resy="${_ainf[1]}"
     [ "${_ainf[2]:--}" != '-' ] && _zoom="${_ainf[2]}"
+
+    [ -n "${DAT_GEOM[0]}" ] && _resx="${DAT_GEOM[0]}"
+    [ -n "${DAT_GEOM[1]}" ] && _resy="${DAT_GEOM[1]}"
+
+    [ "$_resx$_resy" = '++' ] && _full='; visibility: "FullScreen"'
     [ "$_resx" = '-' ] && _resx='(Screen.desktopAvailableWidth * 6) / 10'
     [ "$_resy" = '-' ] && _resy='(Screen.desktopAvailableHeight * 4) / 5'
+    [ "$_resx" = '+' ] && _resx='Screen.desktopAvailableWidth'
+    [ "$_resy" = '+' ] && _resy='Screen.desktopAvailableHeight'
     [ "$_zoom" = '-' ] && _zoom='Screen.pixelDensity / 4.5'
+
     if [ "${_titl:--}" = '-' ] ; then
         _titl="$CEN_NAME"
         [ -n "$CEN_EMBED" ] && _titl="$CEN_EMBED ⸺ $CEN_NAME"
     fi
 
     local _qvar='Q''t' _pipe                        # hide Qt to avoid mime type qml
-    tmpfile -n -s _file -- "launcher.qml" || return 1
+    tmpfile -n -s _file -- 'launcher.qml' || return 1
 
     # wait for synchronization pipe - see 'launcher_webapp'
     if [ -n "$DAT_SYNCPIPE" ] ; then
@@ -382,26 +508,18 @@ $CEN_DEBUG -c -- "$@"
         read -t 60 -u "$DAT_SYNCPIPE" _flag _wurl _dumy || return 1
         trace -a $"synchronization message :" "$_flag" "$_wurl"
         [ "$_flag" = 'OK' ] || return 1
-        if [ "${_wurl:--}" != '-' ] ; then
-            DAT_URL= ; _strt="$_wurl"
-        fi
     fi
 
-    if [ -z "$DAT_URL" ] ; then
-        trace -a $"generate config for qml :" "$_strt"
-        application_url "$_strt" || return 1
-    fi
-    trace -c $"qml web url" -- "$DAT_URL"
     create -r -t -c -- "$_file" 400 <<!EOF || return 1
-import ${_qvar}Quick 2.0
-import ${_qvar}Quick.Window 2.0
+import ${_qvar}Quick 2.2
+import ${_qvar}Quick.Window 2.2
 import ${_qvar}WebEngine 1.2
 Window {
     function cen_posx() { return (Screen.desktopAvailableWidth - $_resx) / 2; }
     function cen_posy() { return (Screen.desktopAvailableHeight - $_resy) / 2; }
     x: cen_posx() ; y: cen_posy()
     width: $_resx ; height: $_resy
-    visible: true
+    visible: true $_full
     title: "$_titl"
 
     WebEngineView {
@@ -416,7 +534,8 @@ Window {
    }
 }
 !EOF
-
+#cat $_file
+#quit $_mode
     case "$_mode" in
     # mode 1 makes no sense with qml, use mode=0
     0|1)
@@ -527,43 +646,69 @@ launcher_webapp() {
 # ------------------------------------------------------------------------------
 application_url() {
     local _wurl="${1:--}"
-
-    # convert argument to url
+    DAT_URL=()
     case "$_wurl" in
-        *://*)  DAT_URL="$_wurl" ; _wurl= ;;
-        *.*)    ;;
-        -)      _wurl="index.html" ;;
-        *)      _wurl="$1.html" ;;
+    *://*)  DAT_URL=("$_wurl") ; return 0
+            ;;
+    file:)  joinpath -s _wurl "$DAT_WEBDIR" "$_wurl"
+            [ -e "$_wurl" ] || _wurl='/var/www/html/index.html'
+            DAT_URL=("file://$_wurl") ; return 0
+            ;;
+    http:|-)
+            ;;
+    *.*)    prettypath -n -s _wurl || return 0
+            DAT_URL=("file://$_wurl") ; return 0
+            ;;
+    *)      _wurl=
     esac
-    if [ -z "$_wurl" ] ; then
-        :
-    elif [ "$_wurl" != '-' ] ; then
-        if [ -n "$DAT_PORT" ] ; then            # using a web server
-        ### TODO prettypath to string webdir path
-            DAT_URL=("http://${DAT_HOST:-localhost}:$DAT_PORT/$_wurl")
-        else
-            joinpath -s _wurl "$DAT_WEBDIR" "$_wurl"
-            DAT_URL=("file://$_wurl")
-        fi
+quit URL "$*"
+    # host port try...
+    # --------------------------------
+    # no   no   localhost:{80,http_proxy,8123}
+    # no   no   <master>:{80,8123}
+    # no   no   duckduckgo.com
+    # no   yes  localhost:<port>
+    # no   yes  <mast>:<port>
+    # yes  no   <host>::{80,8123}
+    # yes  yes  <host>:<port>
+    # --------------------------------
 
-    # we have a pre-set host or port
-    elif [ -n "$DAT_HOST" -o -n "$DAT_PORT" ] ; then
-        DAT_URL=("http://${DAT_HOST:-localhost}${DAT_PORT:+:$DAT_PORT}")
-    # 1st check: does localhost run a server on 80 and 8080
-    elif port_check 'localhost' 80 ||  port_check 'localhost' 8080 ; then
-        DAT_URL=("http://localhost")
-    # kiosk will try local files next
-    elif [ "$CEN_ACTION" = 'kiosk' -a -e "$CEN_ROOT/html/index.html" ] ; then
-        DAT_URL=("file://$CEN_ROOT/html/index.html")
-    # try configured server
-    elif port_check - 80 || port_check - 8080 ; then
-        DAT_URL=("http://$DAT_HOST/index.html")
-    # kiosk will finally try local files next
-    elif [ "$CEN_ACTION" != 'kiosk' -a -e "$CEN_ROOT/html/index.html" ] ; then
-        DAT_URL=("file://$CEN_ROOT/html/index.html")
-    else
-        DAT_URL=() ; return 0
-    fi
+    ___url_try() {
+        local host="$1"
+        if [ "${host:--}" = '-' ] ; then
+            [ -z "$DAT_MASTER" ] && netquery -q -s DAT_MASTER current
+            [ -z "$DAT_MASTER" ] && netquery -q -s DAT_MASTER MASTER
+            [ -z "$DAT_MASTER" ] && return 1
+            host="$DAT_MASTER"
+        elif [ "$1" = '+' ] ; then
+            launcher -a host -k '-flags:def_url' || return 1
+            DAT_URL=("http://$host:$2") ; return 0
+        fi
+        while [ $# -gt 1 ] ; do
+            shift ; [ -n "$1" ] || continue
+            system -n -q netcat -w 1 -z "$host" "$1" || continue
+            DAT_URL=("http://$host:$1") ; return 0
+        done
+        return 1
+    }
+
+    system -f -c netcat
+
+    while [ -z "$_wurl" ] ; do
+        case "$DAT_HOST/$DAT_PORT" in
+        /)       ___url_try 'localhost'   80 "$DAT_PROXY" 8123 && break
+                 ___url_try "$DAT_MASTER" 80              8123 && break
+                 ___url_try '+'           80                   && break
+                ;;
+        /*)     ___url_try 'localhost'   "$DAT_PORT"          && break
+                ___url_try "$DAT_MASTER" "$DAT_PORT"          && break
+                ;;
+        */)     ___url_try "$DAT_HOST"   80              8123 && break
+                ;;
+        *)      ___url_try "$DAT_HOST"   "$DAT_PORT"     8123 && break
+                return 0
+        esac ; break
+    done
 
     # url encoding (partial)
     DAT_URL="${DAT_URL//%/%25}" ; DAT_URL="${DAT_URL// /%20}"
@@ -662,20 +807,20 @@ options() {
     '')     DAT_FOLDER="$CEN_OPT_FOLDER"
             DAT_HOST="$CEN_OPT_HOST"
             DAT_PORT="$CEN_OPT_PORT"
+            [ -n "$CEN_OPT_GEOMETRY" ] && splitjoin -s DAT_GEOM -d ':' -i CEN_OPT_GEOMETRY
             ;;
 
     -D|--des*)
         optarg 'desktop'    -      -t ;;        # text argument
-
     -F|--fol*)
         optarg 'folder'     -      -d ;;        # folder argument
-
+    -G|--geo*)
+        optarg 'geometry'   - '((\+|-|[0-9]*):){0,3}(\+|-|([-0-9]*)?)' ;;
+        #'[-0-9:]' ;;
     -H|--hos|--host)
         optarg 'host'       -      -t ;;        # text argument
-
     -M|--mod|--mode)
         optarg 'mode'       - '[0-3]' ;;        # regex
-
     -P|--por|--port)
         optarg 'port'       -      -n ;;        # number argument
 
@@ -688,17 +833,20 @@ options() {
 actions() {
     case "$1" in
 
-    '')                                         # end processing must be ignored
-        ;;
+    '') ;;                                      # end processing must be ignored
 
     lis|list)
         invoke 'list'   -           0 1 ;;
 
-    *)                              # get list of configured actions
+    *)                                          # get list of configured actions
         local actn list
         launcher -l 3 -a list || return 1
-        listsearch -m actn -u -- "$1" "${list[@]}" || return 1
-
+        if ! listsearch -m actn -u -i list -- "$1" ; then
+            launcher -l 0 -a list || return 1
+            listsearch -m actn -g -i list  -- "$1*" &&
+                invoke -e $"The action is configured but cannot be invoked now"
+            return 1
+        fi
         list=() ; shift
         [ "${CEN_OPT_DESKTOP:--}" != '-' ] && list+=(-y "$CEN_OPT_DESKTOP")
         [ "${CEN_OPT_MODE:--}" != '-' ] && list+=(-m "$CEN_OPT_MODE")
@@ -716,7 +864,7 @@ actions() {
         done
 
         # this calls launcher() as an action
-        invoke "$actn" 'launcher' - - "${list[@]}" -- "$actn" "$@"
+        invoke "$actn" 'launcher' - - "${list[@]}" -- "$actn" "${CEN_CMDARGS[@]:1}"
         ;;
     esac
 }
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimedia b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimedia
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimedia
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimedia
@@ -4,15 +4,14 @@ CEN_LEGAL="Dr. J. Pfennig (c) 2020-2024; "$"BSD License"
 CEN_TITLE=$"Tool to wipe, partition, format and label storage media"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -t -y - '0.30:3' || exit 2
-
-### TODO --base --label 'mount' 'shell'
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -t -y - '0.40:3' || exit 2
 
 # Data
-CEN_OPT_BASE=           # see --base
+CEN_OPT_BASE='/tmp'     # see --base
 CEN_OPT_DEVICE=         # see --device
 CEN_OPT_FSTAB=          # see --fstab
 CEN_OPT_LABEL=          # see --label
+CEN_OPT_SIZE=           # see --size
 
 DAT_PARTITION=
 DAT_PARTPREF=
@@ -153,7 +152,8 @@ run_discard() {
 # copy: [<from>|-] <dest>|- [<comp>]
 # ------------------------------------------------------------------------------
 actionCopy() {
-    local from dest stat
+    system -c -f -- dd
+    local from dest
     if [ $# -gt 1 ] ; then
         if [ -b "$1" -o -c "$1" ] ; then
             from="$1"
@@ -163,7 +163,7 @@ actionCopy() {
         if [ -b "$2" ] ; then
             dest="$2"
         else
-            outfile -f -l -s dest -- "$2" || return
+            outfile -f -l -r -s dest -- "$2" || return
         fi
      else
         [ -z "$CEN_OPT_DEVICE" ] && fatal $"Missing '--device' option"
@@ -184,9 +184,43 @@ actionCopy() {
         invoke -e $"Input and output are equal" ; return 1
      fi
 
-     [ "$CEN_VERB" -ge 1 ] && stat='status=progress'
      message $"Copy data"$" '$from  ->  $dest'"
-     system -- dd if="$from" of="$dest" bs=1M $stat
+     if [ "$CEN_VERB" != 1 ] || dryrun ; then
+        if [ "$CEN_VERB" = 0 ] ; then
+            system -e -q -- dd if="$from" of="$dest" bs=1M
+        else
+            system -e -- dd if="$from" of="$dest" bs=1M status=progress
+        fi
+        return
+     fi
+
+     ___copy_dest() {
+        local poll last stat=0 list eflg
+        while IFS= read -d $'\r' -e poll ; do
+            splitjoin -s list -i poll
+            for poll in "${list[@]}" ; do
+                case "$poll" in
+                    STAT=0) ;;
+                    STAT=?) [ -n "$eflg" ] && continue ; eflg=1
+                            error -p $"Running 'dd' failed (status %s)" "${poll#*=}" ;;
+                    [0-9]*+[0-9]*)
+                            ;;
+                    [0-9]*) progress -a -l -- "$poll" ;;
+                    *dd:*)  if [ "$from" = '/dev/zero' ] ; then
+                                eflg=0 ; continue
+                            fi
+                            eflg=1 ; error -- "${poll#* }" ;;
+                    *)      message -a -- "$poll"
+                esac
+            done
+        done
+        [ "$eflg" != 1 ] && message -a $"Done."
+        return 0
+     }
+     ___copy_orig() {
+         "$@" 2>&1 ; echo -e -n "STAT=$?\r"
+     }
+     syspipe -b ___copy_orig -d ___copy_dest -- dd if="$from" of="$dest" bs=1M status=progress
 }
 
 # ------------------------------------------------------------------------------
@@ -257,35 +291,38 @@ actionFormat() {
     [ -n "$labl" ] && ftab=("LABEL=$labl") || ftab=("$DAT_PARTITION")
 
     case "$1" in
-        sys*)       ftyp="btrfs" ; fvol=2 ; args=("-K" "-f")
-                    [ -n "$labl" ] && args+=("-L" "$labl") ;;
-        vol*)       ftyp="btrfs" ; fvol=1 ; args=("-K" "-f")
-                    [ -n "$labl" ] && args+=("-L" "$labl") ;;
-        btrfs)      ftyp="btrfs" ; args=("-K" "-f")
-                    [ -n "$labl" ] && args+=("-L" "$labl") ;;
+        sys*)       ftyp='btrfs' ; fvol=2 ; args=('-K' '-f')
+                    [ -n "$CEN_OPT_SIZE" ] && args+=('-s' "$CEN_OPT_SIZE")
+                    [ -n "$labl" ] && args+=('-L' "$labl") ;;
+        vol*)       ftyp='btrfs' ; fvol=1 ; args=('-K' '-f')
+                    [ -n "$CEN_OPT_SIZE" ] && args+=('-s' "$CEN_OPT_SIZE")
+                    [ -n "$labl" ] && args+=('-L' "$labl") ;;
+        btrfs)      ftyp='btrfs' ; args=('-K' '-f')
+                    [ -n "$CEN_OPT_SIZE" ] && args+=('-s' "$CEN_OPT_SIZE")
+                    [ -n "$labl" ] && args+=('-L' "$labl") ;;
 
         f2fs)       ftyp="f2fs" ; args=("-f")
                     [ -n "$labl" ] && args+=("-l" "$labl") ;;
 
         exfat)      ftyp="exfat"
-                    [ -n "$labl" ] && args=("-n" "$labl") ;;
+                    [ -n "$labl" ] && args=('-n' "$labl") ;;
 
-        ext4)       ftyp="ext4" ; args=("-E" "nodiscard" "-m" "0")
-                    [ -n "$labl" ] && args+=("-L" "$labl")
-                    post=("tune2fs" "-c" "0" "$DAT_PARTITION") ;;
+        ext4)       ftyp="ext4" ; args=("-E" "nodiscard" "-m" 0)
+                    [ -n "$labl" ] && args+=('-L' "$labl")
+                    post=("tune2fs" "-c" 0 "$DAT_PARTITION") ;;
 
         ntfs*)      ftyp="ntfs" ; args=("-f")
-                    [ -n "$labl" ] && args+=("-L" "$labl") ;;
+                    [ -n "$labl" ] && args+=('-L' "$labl") ;;
 
         fat*|vfat)  ftyp='vfat'
-                    [ -n "$labl" ] && args+=("-n" "$labl")
+                    [ -n "$labl" ] && args+=('-n' "$labl")
                     ftab[3]='nofail' ;;
         [lr]fat)    ftyp='vfat'                             # raspi special case
-                    [ -n "$labl" ] && args+=("-n" "$labl")
+                    [ -n "$labl" ] && args+=('-n' "$labl")
                     ftab[1]='/boot' ; ftab[3]='nofail'
                     [ "$1" = 'rfat' ] && ftab[1]+='/firmware' ;;
         swap)       ftyp='swap' ; ftab[1]='none' ; ftab[3]='nofail'
-                    [ -n "$labl" ] && args+=("-L" "$labl") ;;
+                    [ -n "$labl" ] && args+=('-L' "$labl") ;;
 
         "")         invoke -e $"No filesystem type specified"
                     return ;;
@@ -320,9 +357,9 @@ actionFormat() {
     info_device "$DAT_PARTITION" || return
     ask_if_ok
     if [ -n "$labl" ] ; then
-        message -p $"Creating '%s' filesystem on '%s', label '%s'" "$ftyp" "$DAT_PARTITION" "$labl"
+        message -a -p $"Creating '%s' filesystem on '%s', label '%s'" "$ftyp" "$DAT_PARTITION" "$labl"
     else
-        message -p $"Creating '%s' filesystem on '%s', no label" "$ftyp" "$DAT_PARTITION"
+        message -a -p $"Creating '%s' filesystem on '%s', no label" "$ftyp" "$DAT_PARTITION"
     fi
 
     # remove fs signatures
@@ -431,7 +468,7 @@ actionLabel() {
 }
 
 # ------------------------------------------------------------------------------
-# list partions: -no args-
+# list partitions: -no args-
 # ------------------------------------------------------------------------------
 actionList() {
     if [ -n "$CEN_OPT_DEVICE" ] ; then
@@ -441,7 +478,57 @@ actionList() {
 }
 
 # ------------------------------------------------------------------------------
-# partion: [<kind>] <size>...
+# action mount: -no args-
+# ------------------------------------------------------------------------------
+actionMount() {
+    ___mount_part() {
+        local mopt svol
+        case "$1" in
+        *_swap) warning "Not mounting:" "$1" ; return 1 ;;
+        *_vol0) mopt='-o subvol=/' ;;
+    #   *_*)    mpnt+="/${1##*_}"
+        esac
+        message -a -p "Mount '%s' at '%s'" "$1" "$mpnt/$1"
+        folder -f -m -r -- "$mpnt/$1"
+        if findmount -l "$1" ; then
+            warning -a "Already mounted:" "$1" ; return 1
+        fi
+        system -f -p mount -L "$1" "$mpnt/$1" $mopt
+    }
+
+    local name="${CEN_OPT_LABEL%_*}" list mpnt
+    folder -f -m -s mpnt -- "$CEN_OPT_BASE/$name"
+    if [ "$name" = "$CEN_OPT_LABEL" ] ; then
+        list=("${name}_boot" "${name}_root" "${name}_vol0")
+    else
+        list=("$CEN_OPT_LABEL")
+    fi
+    for part in "${list[@]}" ; do
+        [ -b "/dev/disk/by-label/$part" ] && ___mount_part "$part"
+    done
+}
+
+# ------------------------------------------------------------------------------
+# action shell: -no args-
+# ------------------------------------------------------------------------------
+actionShell() {
+    local name="${CEN_OPT_LABEL%_*}" mpnt moun
+    if [ "$name" = "$CEN_OPT_LABEL" ] ; then
+        mpnt="$CEN_OPT_BASE/$CEN_OPT_LABEL"
+    else
+        mpnt="$CEN_OPT_BASE/$name/$CEN_OPT_LABEL"
+    fi
+    if [ ! -d "$mpnt" ] ; then
+        actionMount ; error -t || return
+        moun=1
+    fi
+    folder -c -f -- "$mpnt"
+    system -r -- bash -i
+    [ -n "$moun" ] && confirm -y -f "Unmount '%s'" "$mpnt" && actionUmount
+}
+
+# ------------------------------------------------------------------------------
+# partition: [<kind>] <size>...
 # ------------------------------------------------------------------------------
 actionPartition() {
     system -e -c 'parted' || return
@@ -453,22 +540,22 @@ actionPartition() {
     local kind numi item size=()
     case "$1" in
         msdos|dos)  kind='msdos' ; shift ;;
-        gpt)        kind="gpt"   ; shift ;;
+        gpt)        kind='gpt'   ; shift ;;
         [0-9]*|+)   ;;
-        "")         ;;
+        '')         ;;
         *)          invoke -e $"Partition table type must be 'msdos' or 'gpt': %s" "$1"
                     return
     esac
 
     if [ $# = 0 ] ; then
-        invoke -e $"Need at least one partion size (use '+' for whole device)"
+        invoke -e $"Need at least one partition size (use '+' for whole device)"
         return
     fi
 
     while [ $# -gt 0 ] ; do
-        if [ "$1" = "+" ] ; then
+        if [ "$1" = '+' ] ; then
             if [ $# = 1 ] ; then
-                size+=("0") ; break
+                size+=(0) ; break
             else
                 invoke -e $"'+' can be used for the last partition only" ; return
             fi
@@ -518,7 +605,7 @@ actionPartition() {
     system -e -p -- parted --script -a optimal "$DAT_PARTITION" mklabel "$kind" $parts
     error -t || return
 
-    message -p $"Created partition table"
+    message -a -p $"Created partition table"
     sleep 0.5
     [ -b "$DAT_PARTITION" ] || sleep 0.5
     [ -b "$DAT_PARTITION" ] || sleep 1
@@ -572,14 +659,36 @@ actionSystem() {
 # umount: -no args-
 # ------------------------------------------------------------------------------
 actionUmount() {
-    check_device -m || return
+    local part coun=0
+    folder -c -f '/'
 
-    local item coun=0
-    findmount -t - -d -- "$CEN_OPT_DEVICE"
-    for item in "${CEN_MOUNT_ARR[@]}" ; do
-        system -e -p -- umount "$item" && ((coun += 1))
-    done
-    pluralize -g -z -p $"Unmounted %s %s" "$coun" $"partion" $"partitions"
+    if [ -n "$CEN_OPT_LABEL" ] ; then
+        local name="${CEN_OPT_LABEL%_*}" list
+        local mpnt="$CEN_OPT_BASE/$name"
+        if [ ! -d "$mpnt" ] ; then
+            invoke -e "Mountpoint '%s' not found" "$mpnt" ; return
+        fi
+        if [ "$name" = "$CEN_OPT_LABEL" ] ; then
+            list=("${name}_boot" "${name}_root" "${name}_vol0")
+        else
+            list=("$CEN_OPT_LABEL")
+        fi
+        for part in "${list[@]}" ; do
+            [ -d "$mpnt/$part" ] || continue
+            trace -a -p "Unmount '%s'" "$mpnt/$part"
+            system -e -p -- umount "$mpnt/$part" && ((coun += 1))
+            remove -q "$mpnt/$part"
+        done
+        remove "$mpnt"
+
+    else
+        check_device -m || return
+        findmount -t - -d -- "$CEN_OPT_DEVICE"
+        for part in "${CEN_MOUNT_ARR[@]}" ; do
+            system -e -p -- umount "$part" && ((coun += 1))
+        done
+    fi
+    pluralize -g -z -p $"Unmounted %s %s" "$coun" $"partition" $"partitions"
 }
 
 # ------------------------------------------------------------------------------
@@ -598,17 +707,17 @@ actionZerofill() {
 # run: [run] <type>
 # ------------------------------------------------------------------------------
 actionRun() {
-    [ "$1" = "run" ] && shift
+    [ "$1" = 'run' ] && shift
     case "$1" in
-        vol*)       ftyp="volume" ;;
-        btrfs)      ftyp="btrfs" ;;
-        f2fs)       ftyp="f2fs" ;;
-        exfat)      ftyp="exfat" ;;
-        ext4)       ftyp="ext4" ;;
-        ntfs*)      ftyp="ntfs" ;;
-        fat*|vfat)  ftyp="vfat" ;;
+        vol*)       ftyp='volume' ;;
+        btrfs)      ftyp='btrfs' ;;
+        f2fs)       ftyp='f2fs' ;;
+        exfat)      ftyp='exfat' ;;
+        ext4)       ftyp='ext4' ;;
+        ntfs*)      ftyp='ntfs' ;;
+        fat*|vfat)  ftyp='vfat' ;;
 
-        "")         invoke -e $"No filesystem type specified"
+        '')         invoke -e $"No filesystem type specified"
                     return ;;
         *)          invoke -e $"Unsupported filesystem: %s" "$1"
                     return
@@ -633,13 +742,15 @@ options() {
             optarg - - -m '--device --label'
         ;;
     -B|--base)
-        optarg 'base'       -   -t  ;;          # text argument
+        optarg 'base'       -   -d  ;;          # text argument
     -D|--dev*)
         optarg 'device'     -   -t  ;;          # any text
     -F|--fst*)
         optarg 'fstab'      -   -t  ;;          # any text
     -L|--lab*)
         optarg 'label'      -   -t  ;;          # any text
+    -S|--sec*)
+        optarg 'size'       -   -n  ;;          # a number
     esac
 }
 
@@ -649,13 +760,18 @@ options() {
 actions() {
     case "$1" in
 
-    # insist in '--device' option unless the only verb is 'copy' or 'inhibit'
-    '') if [ -z "$CEN_OPT_DEVICE" ] ; then
-            listsearch -- '--' "${CEN_CMDARGS[@]//---/--}" &&
-                fatal $"Missing '--device' option"
+    # insist in '--label' or '--device' option
+    '') if [ -n "$CEN_OPT_LABEL" ] ; then
+            listsearch -- '--' "${CEN_CMDARGS[@]//---/--}" && CEN_CMDARGS=
             case "${CEN_CMDARGS::3}" in
-            cop|inh|lis|pro)    ;;
-            *)              fatal $"Missing '--device' option"
+            mou|she|umo|unm) ;;
+            *)      fatal $"Bad use of '--label' option"
+            esac
+        elif [ -z "$CEN_OPT_DEVICE" ] ; then
+            listsearch -- '--' "${CEN_CMDARGS[@]//---/--}" && CEN_CMDARGS=
+            case "${CEN_CMDARGS::3}" in
+            cop|inh|lis|pro) ;;
+            *)      fatal $"Missing '--device' option"
             esac
         else
             case "$CEN_OPT_DEVICE" in
@@ -715,21 +831,22 @@ usage() {
              -u $"Form"" (4) "$"run a shell that avoids the udisks automount problem." \
 
     usageset -o - \
-             -o '-B --base    <fldr>' $"mount base folder for form (2) actions" \
+             -o '-B --base    <fldr>' $"form (2) actions mount folder (default: $CEN_OPT_BASE)" \
              -o '-D --device  <dev>'  $"[*] block device to use" \
              -o '-L --label   <dlab>' $"[*] volume or partition label" \
              -o '-F --fstab   <file>' $"append fstab entry to file, use '-' for stdout" \
+             -o '-S --sector  <sect>' $"set sector size (used for brtfs only)" \
              -o - \
              -o $"[*] ohne of these is required by form (1) or (2) actions" \
 
     usageset -a $"••• media setup •••" \
              -a 'discard'             $"discard all data via 'blkdiscard'" \
-             -a 'zero      [<part>]'  $"zerofill device or partion" \
+             -a 'zero      [<part>]'  $"zerofill device or partition" \
              -a - \
              -a 'partition [<kind>] <size>...' \
-             -a -                     $"create a new partion table" \
+             -a -                     $"create a new partition table" \
              -a 'flag      [<part>] <flag>...' \
-             -a -                     $"set partion flags" \
+             -a -                     $"set partition flags" \
              -a 'format    [<part>] <type> [<label>]' \
              -a -                     $"format device or partition" \
              -a 'label     [<part>] <label>' \
@@ -742,9 +859,9 @@ usage() {
              -a -                     $"and format the entire medium" \
              -a - \
              -a $"••• (un-)mounting media •••" \
-             -a 'mount'               $"mount partions of the given device" \
+             -a 'mount'               $"mount partitions of the given device" \
              -a 'shell'               $"mount, run a shell and unmount" \
-             -a 'umount'              $"unmount all partions of the given device" \
+             -a 'umount'              $"unmount all partitions of the given device" \
              -a - \
              -a $"••• other/helpers •••" \
              -a 'copy      [<from>|-] <dest>|- [<cmpr>]' \
@@ -758,8 +875,9 @@ usage() {
              -p '<flag>'     $"'efi' 'boot' 'bios_grub'" \
              -p '<kind>'     $"kind of partition table: msdos|gpt" \
              -p '<label>'    $"label text" \
-             -p '<part>'     $"a partion number" \
-             -p '<size>'     $"size of partion: <number><M|G|T>" \
+             -p '<part>'     $"a partition number" \
+             -p '<sect>'     $"sector size in bytes" \
+             -p '<size>'     $"size of partition: <number><M|G|T>" \
              -p -            $"the last size can be '+' to use all space" \
              -p '<type>'     $"file system type: swap,fat,ext4,exfat,ntfs,fs2fs, btrfs or" \
              -p -            $"'volume' or 'system' to create btrfs with subvolume tree" \
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripaths b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripaths
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripaths
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripaths
@@ -1,10 +1,10 @@
-#!/bin/bash
+#!/usr/bin/bash
 # ------------------------------------------------------------------------------
 CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2007-2022; BSD License"
 CEN_TITLE=$"Resolve/symlink path shortcuts to real filesystem paths"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -r -t '-' '0.33:2' 1 || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -r -t - '0.34:3' 1 || exit 2
 
 # Options
 CEN_OPT_ABSTRACT=       # path abstraction
@@ -14,6 +14,7 @@ CEN_OPT_LIST=           # list known short names
 CEN_OPT_LOGICAL=        # logical name
 CEN_OPT_NAME=()         # link names
 CEN_OPT_PHYSICAL=       # physical name
+CEN_OPT_REMOTE=         # remote host name
 CEN_OPT_STYLE=          # output style
 CEN_OPT_SYMLINK=        # create symlink
 CEN_OPT_TABLE=          # tabular output
@@ -162,8 +163,26 @@ proc_item() {
 # The one and only action
 # ------------------------------------------------------------------------------
 run() {
+    # run remote
+    if [ -n "$CEN_OPT_REMOTE" ] ; then
+        local item acmd=('ssh' "$CEN_OPT_REMOTE" "$CEN_NAME")
+        for item in "${CEN_CMDOPTS[@]}" "${CEN_CMDARGS[@]}" ; do
+            case "$item" in
+            --debug)    ;;
+            --pager=*)  ;;
+            --remote=*) ;;
+            --trace)    ;;
+            --verbose)  ;;
+            *)          acmd+=("$item")
+            esac
+        done
+        system -s item "${acmd[@]}"
+        [ -n "$item" ] && printf '%s\n' "$item"
+        quit
+    fi
+
     # load shortcut table
-    shortpath -a DAT_CONFIG -r -m "" || return
+    shortpath -a DAT_CONFIG -r -m '' || return
 
     if [ -n "$CEN_OPT_WORK" ] ; then
         local _serr="$DAT_PRETTY_MODE" ; DAT_PRETTY_MODE="-e -f"
@@ -200,39 +219,41 @@ options() {
     case "$1" in
 
     -A|--abs*)
-        optarg "abstract"   -    ;;
+        optarg 'abstract'   -    ;;
     -D|--del*)
         CEN_RUN_MIN_ARGS=0
-        optarg "deleted"    -    ;;
+        optarg 'deleted'    -    ;;
     -E|--err*)
-        optarg "error"      CEN_OPT_ERROR - "error" ;;
+        optarg 'error'      CEN_OPT_ERROR - 'error' ;;
     -F|--fat*)
-        optarg "fatal"      CEN_OPT_ERROR - "fatal" ;;
+        optarg 'fatal'      CEN_OPT_ERROR - 'fatal' ;;
     -I|--lis|--list)
         CEN_RUN_MIN_ARGS=0
-        optarg "list"       -    ;;
+        optarg 'list'       -    ;;
     -K|--sym*)
-        optarg "symlink"    -    ;;
+        optarg 'symlink'    -    ;;
     -L|--log*)
-        optarg "logical"    -    ;;
+        optarg 'logical'    -    ;;
     -N|--nam*)
-        optarg "name"      [] -t ;;
+        optarg 'name'      [] -t ;;
     -P|--phy*)
-        optarg "physical"   -    ;;
+        optarg 'physical'   -    ;;
+    -R|--rem*)
+        optarg 'remote'     - -t ;;
     -S|--sty*)
-        optarg "style"      - -n ;;         # numeric
+        optarg 'style'      - -n ;;         # numeric
     -T|--tab*)
-        optarg "table"      -    ;;
+        optarg 'table'      -    ;;
     -U|--uni*)
-        optarg "unique"     -    ;;
+        optarg 'unique'     -    ;;
     -W|--wor*)
-        optarg "work"       - -t ;;         # text
+        optarg 'work'       - -t ;;         # text
 
     --help)                                 # input completion
         CEN_OPT_VERB=1
-        [ "$2" = "verb" ] && run ;;
+        [ "$2" = 'verb' ] && run ;;
 
-    "")                                     # end of option parsing
+    '')                                     # end of option parsing
         # implied options
         [ -n "$CEN_OPT_UNIQUE" -a -z "$CEN_OPT_PHYSICAL$CEN_OPT_ABSTRACT$CEN_OPT_DELETED" ] &&
             CEN_OPT_LOGICAL="1"
@@ -278,29 +299,28 @@ usage() {
              -o "-K --symlink         "$"create symlink from cwd to folder" \
              -o "-L --logical         "$"returned paths should be logical names" \
              -o "-N --name    <link>  "$"link name, can be repeated" \
-             -o "-P --physical        "$"returned paths should be physical" \
+             -o '-P --physical'        $"returned paths should be physical" \
+             -o '-R --remote  <host>'  $"execute command on remote host" \
              -o "-S --style   <mask>  "$"modifies path output formatting" \
              -o "-T --tabular         "$"generate tabular output" \
              -o "-U --unique          "$"remove duplicated folders" \
              -o "-W --work    <work>  "$"set working folder"
 
-    usageset -l $"arguments" \
-             -t "<name>       "$"shortcut name, to get a list run:"" $CEN_NAME --list" \
-             -t "<path>       "$"any path (must contain a '/' or follow '<name>')" \
-             -t "<link>       "$"link name, overrides short name if present" \
-             -t "<mask>       "$"bit mask, 1 := print - if missing, 2 := quoted" \
-             -t "<work>       "$"working folder, can be a short name"
+    usageset -p '<host>'        $"remote host name" \
+             -p '<name>'        $"shortcut name, to get a list run:"" $CEN_NAME --list" \
+             -p '<path>'        $"any path (must contain a '/' or follow '<name>')" \
+             -p '<link>'        $"link name, overrides short name if present" \
+             -p '<mask>'        $"bit mask, 1 := print - if missing, 2 := quoted" \
+             -p '<work>'        $"working folder, can be a short name"
 
-    usageset -l $"remark" \
-             -t $"The shortcut definitions are loaded from \"centauri-bash-lib\" which is" \
+    usageset -t $"The shortcut definitions are loaded from \"centauri-bash-lib\" which is" \
              -t $"searched at \"~/.config\" \"~\" \"\$CEN_ROOT/default\" or \"/etc/default\"."
 
-    usageset -l $"examples" \
-             -t "$CEN_NAME --list --tabular --verbose        # "$"list all names/paths" \
-             -t "$CEN_NAME temp                              # "$"current user's TMPDIR" \
-             -t "$CEN_NAME --logical automount/alpha4_work   # "$"get a logical path" \
-             -t "$CEN_NAME --work=/tmp --symlink disk data   # "$"make symlinks ..." \
-             -t "$CEN_NAME --work=/tmp disk --name=d1 data --name=d2"
+    usageset -e ". --list --tabular --verbose        # "$"list all names/paths" \
+             -e ". temp                              # "$"current user's TMPDIR" \
+             -e ". --logical automount/alpha4_work   # "$"get a logical path" \
+             -e ". --work=/tmp --symlink disk data   # "$"make symlinks ..." \
+             -e ". --work=/tmp disk --name=d1 data --name=d2"
 }
 
 # ------------------------------------------------------------------------------
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriprofile b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriprofile
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriprofile
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriprofile
@@ -4,22 +4,16 @@ CEN_TITLE="Manage KDE and Firefox profiles"
 CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2007-2024; BSD License"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -t -y - '0.40:2' || exit 2
-
-### TODO make links for centauriroaming local/roaming
-### TODO currentfile -r: use .. if not found in buster
-
-### centaurisession
-###      local   links back to local
-###      roaming go to roaming dir [Roaming must exist, make backups]
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -m sys -t -y - '0.41:3' || exit 2
 
 # options
-CEN_OPT_CREATE=             # see --create
-CEN_OPT_SELECT=0            # see --select
-CEN_OPT_USER=               # see --user
+CEN_OPT_CREATE=                     # see --create
+CEN_OPT_SELECT=0                    # see --select
+CEN_OPT_USER=                       # see --user
 
 # set by currentFile
-CURRENT_FILE=                       # result
+CURRENT_FILE=                       # result for KDE
+CURRENT_LXQT=                       # result for LxQt
 CURRENT_MOZI=                       # result
 CURRENT_PATH=                       # result: roaming profile path
 
@@ -33,12 +27,14 @@ DAT_KDE_VERS="${DAT_KDE_VERS#0}"
 DAT_KDE_VERS="${DAT_KDE_VERS#0}"    # version number like 4, 5 ...
 DAT_KDE_VERS="kde$DAT_KDE_VERS"
 
-DAT_REPODIR="$CEN_TOOLS/kde/Roaming" # default profiles in repository
+DAT_REPODIR="$CEN_TOOLS/Desktop"    # default profiles in repository
+DAT_ROAMING="$CEN_TOOLS/Roaming"    # default roaming profiles
+
 DAT_PROFILE="Roaming/Profiles/kde"  # example: $HOME/Roaming/Profiles/kde/buster
 DAT_NICKNAME="$CEN_SYS_NICKNAME"    # OS nick name
 
 # Localized data
-DAT_DESKT=($"Desktop"   "Desktop")
+DAT_DESKT=($"Desktop"   'Desktop')
 
 # ------------------------------------------------------------------------------
 # Check or create temporary folders: [-m|-n]
@@ -63,7 +59,7 @@ tempFolders() {
     }
 
     local rval omak onew osil
-    while [ "${1::1}" = "-" ] ; do
+    while [ "${1::1}" = '-' ] ; do
         case "$1" in
         --)   shift ; break ;;
         -m)   omak=-m ;;
@@ -97,34 +93,46 @@ tempFolders() {
 #           CURRENT_MOZI    found file (default: dot_mozilla...)
 #           CURRENT_PATH    (writable) profile location
 #
-# Search:   $HOME/Roaming/Profiles/kde/$DAT_NICKNAME/
+# Search:   $HOME/Roaming/Profiles/kde/$DAT_NICKNAME/       DAT_PROFILE
 #           $HOME/Roaming/Profiles/kde/
-#           $CEN_TOOLS/kde/Roaming/$LOGNAME/
-#           $CEN_TOOLS/kde/Roaming/
+#           $CEN_TOOLS/Roaming/$CEN_OPT_USER                DAT_ROAMING
+#           $CEN_TOOLS/Roaming
+#           $CEN_TOOLS/Desktop                              DAT_REPODIR
+#
+# Names:    $1
+#           $1-config.t*
+#           dot-$1.t*
 # ------------------------------------------------------------------------------
 currentFile() {
     # helper to find file: -r|-w <name> <dir>...
     ___findfile() {
         local fldr rwop="$1" ; shift
         local name="${1:--}" ; shift
-        for fldr in "$@" ; do
+        local curr="$PWD" ; CURRENT_FILE=
+        for fldr in "$@" "$DAT_ROAMING/$CEN_OPT_USER" "$DAT_ROAMING" "$DAT_REPODIR" ; do
             [ -n "$fldr" -a -d "$fldr" ] || continue
+            folder -c -f "$fldr"
             if [ -z "$CURRENT_PATH" ] ; then        # get best folder
-                [ $rwop "$fldr" ] && CURRENT_PATH="$fldr"
+                [ $rwop "$fldr" ] && CURRENT_PATH="$PWD"
             fi
-            if [ "$rwop" = "-w" ] ; then            # -w: check folder
-                [ -w "$fldr" ] || continue
-            else                                    # -r: file checked
-                [ -r "$fldr/$name" ] || continue
+            if [ "$rwop" = '-w' ] ; then            # -w: check folder
+                [ -w "$PWD" ] || continue
+            elif matchpath -o -f -- "$name" "$name-config".t* \
+                         dot[_\-]"$name"* ; then    # -r: file checked
+                name="$CEN_MATCHPATH"
+            else
+                continue
             fi
-            CURRENT_FILE="$fldr/$name" ; return 0
+            prettypath -s CURRENT_FILE -- "$PWD/$name" ; break
         done
-        CURRENT_FILE= ; return 1
+        folder -c -f "$curr"
+        trace -c 'profile' "$name -> $CURRENT_FILE"
+        [ -n "$CURRENT_FILE" ]                      # return status
     }
 
     # options
     local rwop="-r" optz
-    while [ "${1::1}" = "-" ] ; do
+    while [ "${1::1}" = '-' ] ; do
         case "$1" in
         --)   shift ; break ;;
         -)    break ;;
@@ -136,33 +144,32 @@ currentFile() {
     CURRENT_PATH=
 
     # default local files
-    if [ "$1" = "-" -o "$1" = "." -o "$1" = ".." ] ; then
+    if [ "$1" = '-' -o "$1" = '.' -o "$1" = '..' ] ; then
         local dtim ; system -e -p -r -s dtim -- date "+%Y-%m-%d"
         CURRENT_MOZI="$PWD/dot_mozilla_$dtim.tgz"
         CURRENT_FILE="$PWD/dot_${DAT_KDE_VERS}_$dtim.tgz"
 
     # default roaming file(s)
-    elif [ "${1:-+}" = "+" ] ; then
+    elif [ "${1:-+}" = '+' ] ; then
         local rpth rnik name="${2:--}"
-        [ "$name" = "-" ] && name="dot_${DAT_KDE_VERS}_default.tgz"
+        [ "$name" = '-' ] && name="$DAT_KDE_VERS"
         eval rpth="~$CEN_OPT_USER/$DAT_PROFILE"
         rnik="$rpth/$DAT_NICKNAME"
         [ -n "$CEN_OPT_CREATE" ] && folder -f -m "$rnik"
-
-        ___findfile "$rwop" "dot_mozilla.tgz" \
-                    "$rnik" "$rpth" "$DAT_REPODIR/$CEN_OPT_USER" "$DAT_REPODIR"
+        ___findfile "$rwop" 'mozilla' "$rnik" "$rpth"
         CURRENT_MOZI="$CURRENT_FILE"
 
-        ___findfile "$rwop" "$name" \
-                    "$rnik" "$rpth" "$DAT_REPODIR/$CEN_OPT_USER" "$DAT_REPODIR"
+        ___findfile "$rwop" 'lxqt' "$rnik" "$rpth"
+        CURRENT_LXQT="$CURRENT_FILE"
+
+        ___findfile "$rwop" "$name" "$rnik" "$rpth"
 
     # explicit file
     else
         local name="$1"
         [ -n "$optz" ] && name="${1%.tgz}.tgz"
         if [ "${name/\//}" = "$name" ] ; then   # no / in name ...
-            ___findfile "$rwop" "$name" \
-                        "$rpth" "$DAT_REPODIR/$CEN_OPT_USER" "$DAT_REPODIR"
+            ___findfile "$rwop" "$name" "$rpth"
             [ -z "$CURRENT_FILE" ] && CURRENT_FILE="$PWD/$name"
         else
             resolve -m -s CURRENT_FILE "$name"
@@ -198,18 +205,18 @@ updateFile() {
 }
 
 # ------------------------------------------------------------------------------
-# undo generalize: -no args-
+# undo generalize: [<folder>]
 # ------------------------------------------------------------------------------
 specialize() {
     local item from="${HOME//\//\\/}" flis fgen
     local s0_0="$from/$DAT_DESKT"   s0_1="##GEN##/Desktop"
     local s1_0="\$HOME/$DAT_DESKT"  s1_1="\$HOME/Desktop"
     local sedo="s|$s0_1|$s0_0|g ; s|$s1_1|$s1_0|g ; s/##GEN##/$from/g ; s/##USR##/$USER/g"
-
-    # typo in old profile versions...
-    for item in ".generalized_profile" ".generalsized_profile" ; do
+    local curr="$PWD"
+    [ -n "$1" ] && folder -c -f "$1"
+    for item in ".generalized_profile" ; do
         [ -e "$item" ] || continue
-        dryrun "specialize" "$item" && continue
+        dryrun "specialize" "$PWD/$item" && continue
         flis=()
         echo >> "$item"                 # last line must have \n
         while read -r fgen ; do
@@ -218,24 +225,35 @@ specialize() {
         [ -n "$flis" ] && system -e -p -- sed -i "$sedo" "${flis[@]}"
         remove "$item"
     done
+    [ -n "$1" ] && folder -c "$PWD"
 }
 
 # ------------------------------------------------------------------------------
 # apply profile settings: -see currentFile for argument-
 # ------------------------------------------------------------------------------
 actionApply() {
-    # get profile file path
-    currentFile -z "$1" || return
-    [ "$CEN_OPT_SELECT" -gt 1 ] && CURRENT_FILE="$CURRENT_MOZI"
-    [ -r "$CURRENT_FILE" ] || fatal "Cannot read: $CURRENT_FILE"
 
-    local ptxt omsg=trace ; [ "$CEN_YESNO" = "y" ] && omsg=message
-    printf -v ptxt $"Install profile settings from '%s'" "$CURRENT_FILE"
-    confirm -a "$ptxt" || return 1
-    $omsg -a -p $"Installing profile for '%s' from '%s'" "$DAT_USER_DIR" "$CURRENT_FILE"
-    system -e -p -- tar -xzf "$CURRENT_FILE" --directory="$DAT_USER_DIR" --no-same-owner
+    ___apply() {
+        [ "${1:--}" = '-' ] && return
+        confirm -y -f $"Install profile settings from '%s'" "$1" || return
+        local omsg=trace ; [ "$CEN_YESNO" = 'y' ] && omsg=message
+        $omsg -a -p $"Installing profile for '%s' from '%s'" "$DAT_USER_DIR" "$1"
+        system -e -p -- tar -xzf "$1" --directory="$DAT_USER_DIR" --no-same-owner
+        specialize "$DAT_USER_DIR/$2"           # undo generalize
+    }
 
-    specialize              # undo generalize
+    # get profile file paths
+    if [ "$1" = '+' ] ; then
+        currentFile +
+        local mask="${CEN_OPT_SELECT/0/7}"
+        ((mask & 2)) && ___apply "$CURRENT_FILE" '.kde'
+        ((mask & 1)) && ___apply "$CURRENT_MOZI" '.mozilla'
+        ((mask & 4)) && ___apply "$CURRENT_LXQT" '.config/lxqt'
+    elif currentFile -z "$1" ; then
+        ___apply "$CURRENT_FILE"
+    else
+        fatal $"Cannot find file:" "$1"
+    fi
 }
 
 # ------------------------------------------------------------------------------
@@ -395,7 +413,7 @@ actionCurrent() {
     currentFile "$1"
     local stat=
     [ -f "$CURRENT_FILE" ] || stat=$" [not found]"
-    if [ "${1:-+}" = "+" -o "$1" = "-" ] ; then
+    if [ "${1:-+}" = '+' -o "$1" = '-' ] ; then
         [ "$CEN_OPT_SELECT" = 2 ] ||
             message -a -p $"Profile:  %-50s %s" "$CURRENT_FILE" "$stat"
         stat=
@@ -464,11 +482,13 @@ actionGeneral() {
 # --select can be used to filter output of '+'.
 # ------------------------------------------------------------------------------
 actionInfo() {
-    if [ "$1" = "+" ] ; then
+    if [ "$1" = '+' ] ; then
         currentFile -w +
-        [ "$CEN_OPT_SELECT" = "2" ] || echo "${CURRENT_FILE:--}"
-        [ "$CEN_OPT_SELECT" = "1" ] || echo "${CURRENT_MOZI:--}"
-    elif [ "$1" = "-" ] ; then
+        local mask="${CEN_OPT_SELECT/0/7}"
+        ((mask & 2)) && echo "${CURRENT_FILE:--}"
+        ((mask & 1)) && echo "${CURRENT_MOZI:--}"
+        ((mask & 4)) && echo "${CURRENT_LXQT:--}"
+    elif [ "$1" = '-' ] ; then
         currentFile -w +
         echo -e "${CURRENT_PATH:--}"
     elif [ -n "$1" ] ; then
@@ -575,7 +595,7 @@ actionSave() {
 ### TODO deref tar folder args!
 
     # do we have .kde or .mozilla?
-    local tara="."
+    local tara='.'
     if [ "$CEN_OPT_SELECT" -gt 1 ] ;then
         folder -f ".mozilla"
         tara=".mozilla"
@@ -602,7 +622,7 @@ actionSizes() {
     esac
 
     for prog in "qdirstat" "k4dirstat" - ; do
-        [ "$prog" = "-" ] && fatal $"Please install 'qdirstat' or 'k4dirstat'"
+        [ "$prog" = '-' ] && fatal $"Please install 'qdirstat' or 'k4dirstat'"
         system -c "$prog" && break
     done
     system -e -p -- "$prog" "$base"
@@ -631,11 +651,11 @@ options() {
     case "$CEN_ACTION" in
 
     -C|--cre*)
-        optarg "create"     CEN_OPT_CREATE ;;
+        optarg 'create'     CEN_OPT_CREATE ;;
     -S|--sel*)
-        optarg "select"     CEN_OPT_SELECT -n ;;
+        optarg 'select'     CEN_OPT_SELECT -n ;;
     -U|--use*)
-        optarg "user"       CEN_OPT_USER -t   ;;
+        optarg 'user'       CEN_OPT_USER -t   ;;
     esac
 }
 
@@ -647,43 +667,43 @@ actions() {
     case "$CEN_ACTION" in
 
     # end option parsing, check --user option
-    "")
-        if [ "${CEN_OPT_USER:--}" = "-" ] ; then
+    '')
+        if [ "${CEN_OPT_USER:--}" = '-' ] ; then
             CEN_OPT_USER="$LOGNAME" ; DAT_USER_DIR="$HOME"
         else
             eval DAT_USER_DIR=~$CEN_OPT_USER
-            [ "${DAT_USER_DIR::1}" = "~" ] && fatal $"No such user"": $CEN_OPT_USER"
+            [ "${DAT_USER_DIR::1}" = '~' ] && fatal $"No such user"": $CEN_OPT_USER"
             message -a -p $"Home folder of user '%s' is '%s'" "$CEN_OPT_USER" "$DAT_USER_DIR"
         fi
         ;;
 
     # actions
     app*)
-        invoke "apply"   -            1 ;;
+        invoke 'apply'   -            1 ;;
     cre*)
-        invoke "create"  -            0 1 ;;
+        invoke 'create'  -            0 1 ;;
     cle*)
-        invoke "cleanup" -            0 ;;
+        invoke 'cleanup' -            0 ;;
     com*|kom*)
-        invoke "compare" -            0 ;;
+        invoke 'compare' -            0 ;;
     cur*)
-        invoke "current" -            0 1 ;;
+        invoke 'current' -            0 1 ;;
     fil*|dol*)
-        invoke "files"   -            0 ;;
+        invoke 'files'   -            0 ;;
     gen*)
-        invoke "general" -            0 ;;
+        invoke 'general' -            0 ;;
     inf|info)
-        invoke "info"    -            0 1 ;;
+        invoke 'info'    -            0 1 ;;
     ini*)
         invoke 'init'    -            1 ;;
     loa|load)
-        invoke "load"    -            0 2 ;;
+        invoke 'load'    -            0 2 ;;
     sav|save)
-        invoke "save"    -            0 1 ;;
+        invoke 'save'    -            0 1 ;;
     siz*)
-        invoke "sizes"   -            0 1 ;;
+        invoke 'sizes'   -            0 1 ;;
     swa|swap)
-        invoke "swap"    -            0 ;;
+        invoke 'swap'    -            0 ;;
     esac
 }
 
@@ -720,20 +740,21 @@ actions:
        info    [<file>]     machine readable version of 'current'
        compare              compare 'old' and 'new' folders
        files                open dolphin to show 'old' and 'new'
-       sizes   [old|new]    run qdirstat/k4dirstat to show sizes
-       cleanup              delete 'old' and 'new' foldes
+       sizes   [old|new]    run 'qdirstat' to show sizes
+       cleanup              delete 'old' and 'new' folders
 
 arguments:
-       <mode>               0:= all 1:=ignore .mozialla 2:=only .mozilla
+       <mode>               0:= all  1:=ignore mozilla  2:=mozilla  4:=lxqt
        <user>               user name (action save may not work if roaming)
        <file>               a path or -:=to use local file  +:=to use profile
 
 profile: the search-order for profiles is:
 
-       $HOME/Roaming/Profiles/kde/$DAT_NICKNAME/
-       $HOME/Roaming/Profiles/kde/
-       $CEN_TOOLS/kde/Roaming/$LOGNAME/
-       $CEN_TOOLS/kde/Roaming/
+       • $HOME/$DAT_PROFILE/$DAT_NICKNAME/
+       • $HOME/$DAT_PROFILE/
+       • $DAT_ROAMING/$LOGNAME/
+       • $DAT_ROAMING/
+       • $DAT_REPODIR/
 
 examples:
        $CEN_NAME create scratch    # create profile as 'scratch.tgz'
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriraspi b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriraspi
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriraspi
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriraspi
@@ -4,13 +4,14 @@ CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2009-2024; "$"BSD License"
 CEN_TITLE=$"Tool to manage 'Raspberry Pi' boot configurations"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -m mnt -t -y - '0.24:2' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -m mnt -t -y - '0.25:4' || exit 2
 
 # Data
 
 CEN_OPT_BOOT=               # see --boot
 CEN_OPT_DEVICE=             # see --device
 CEN_OPT_HOST="$HOSTNAME"    # see --host
+CEN_OPT_IFNAMES=            # see --ifnames
 CEN_OPT_LEGACY=             # see --legacy
 CEN_OPT_NOCHECK=            # see --nocheck
 CEN_OPT_ROOT=               # see --root
@@ -18,6 +19,7 @@ CEN_OPT_UUID=               # see --uuid
 
 DAT_UPDTHOOK="/etc/initramfs/post-update.d/$CEN_NAME"
 DAT_ASK_QUIT=
+DAT_ENTRY_CURR=             # see actionEntry, current boot
 
 # ------------------------------------------------------------------------------
 # ask once to quit: <confirm arguments>
@@ -49,12 +51,13 @@ do_file() {
 # ------------------------------------------------------------------------------
 do_folder() {
     if [ -n "$CEN_OPT_DEVICE" ] ; then
+        local part
         case "$CEN_OPT_DEVICE" in
-            */*)    ;;                          # path
+            */*)    part="*1" ;;                # path, add partition #1
             *_*)    ;;                          # full label
             *)      CEN_OPT_DEVICE+='_boot'     # host name
         esac
-        automount -k $"raspberry storage" -- "$CEN_OPT_DEVICE"
+        automount -k $"raspberry storage" -- "$CEN_OPT_DEVICE"$part
         [ -z "$CEN_OPT_BOOT" ] && CEN_OPT_BOOT="$CEN_MOUNT_DIR"
     elif [ -z "$CEN_OPT_BOOT" ] ; then
         do_legacy && CEN_OPT_BOOT='/boot' || CEN_OPT_BOOT='/boot/firmware'
@@ -81,10 +84,10 @@ do_compare() {
     local targ="$1" item ; shift
     for item in "$@" ; do
         if system -r -q -- cmp --quiet "$targ" "$item" ; then
-            [ "$hook" = "-" ] && return 0
+            [ "$hook" = '-' ] && return 0
             $hook "$targ" "$item" 0
         else
-            [ "$hook" = "-" ] && return 1
+            [ "$hook" = '-' ] && return 1
             $hook "$targ" "$item" 1
         fi
     done
@@ -118,7 +121,7 @@ $CEN_TOOLS/$CEN_NAME initrd update "\$2"
 # ------------------------------------------------------------------------------
 do_legacy() {
     if [ -z "$CEN_OPT_LEGACY" ] ; then
-        sysversion -u
+        sysversion -u -o -f
         [ "${CEN_SYS_VERSION%%.*}" -gt 11 ] && CEN_OPT_LEGACY=0 || CEN_OPT_LEGACY=1
         [ "$CEN_OPT_LEGACY" = 0 ] || warning "Running in legacy mode"
     fi
@@ -216,7 +219,7 @@ actionConfig() {
         warning -a $"Missing PARTUUID:" "$puid"
     fi
 
-    # warn is label does not match HOSTNAME
+    # warn if label does not match HOSTNAME
     if [ -n "$slbl" -a -z "$CEN_OPT_NOCHECK" ] ; then
         if [ "${slbl%_*}" != "$CEN_OPT_HOST" ] ; then
             warning "Label '$slbl' does not match hostname"
@@ -253,12 +256,15 @@ actionCopy() {
 actionEntry() {
     # auto-generate default entries ...
     if [ "$1" = '-' ] ; then
-        local name args
+        local name args hdir
         shift ; name="${1:--}" ; [ "$name" = '-' ] && set -- '+' "${@:2}"
         args=("$@") ; args[1]='splash'
         actionEntry 'default' "${args[@]}"
         netquery 'server' "$CEN_OPT_HOST" && actionEntry 'server' "${args[@]}"
-        [ -e '/home/local/.autologin' ] && actionEntry 'bootmenu' "${args[@]}"
+        for name in 'local' 'kiosk' 'clock' ; do
+            eval hdir=~$name
+            [ -d "$hdir" ] && actionEntry 'bootmenu' "${args[@]}"
+        done
         args[1]='nosplash'
         for name in 'router' 'repeater' 'switch' 'extender' ; do
             netoption "$name" "$CEN_OPT_HOST" && actionEntry "$name" "${args[@]}"
@@ -272,6 +278,11 @@ actionEntry() {
     do_folder -n
     local line name="$1" ramd args=("root=${2:-+}") ; shift ; shift
 
+    if [ -z "$DAT_ENTRY_CURR" ] && do_compare - 'cmdline.txt' "cmdline-$name.txt" ; then
+        DAT_ENTRY_CURR="cmdline-$name.txt"
+        trace -a -c "current boot" "$DAT_ENTRY_CURR"
+    fi
+
     if [ "$args" = 'root=-' ] ; then                # generate no root=
         do_ask_quit "Not creating a 'root=' boot parameter. Really continue"
         args=()
@@ -282,28 +293,30 @@ actionEntry() {
         elif [ -b "/dev/disk/by-label/${CEN_OPT_HOST}_root" ] ; then
             fsty='ext4' ; args=("root=LABEL=${CEN_OPT_HOST}_root")
         else
-            invoke -e "Cannot autotdetect root, please specify as argument" ; return
+            invoke -e "Cannot autodetect root, please specify as argument" ; return
         fi
         do_ask_quit -f "Booting '%s' from '%s' filesystem. Continue" "$CEN_OPT_HOST" "$fsty"
     fi
+    args+=('fsck.repair=yes')
 
     if [[ "$args" =~ LABEL=.*_vol[0-9] ]] ; then    # btrfs config
-        args+=(rootflags=subvol=/Volumes/Root)
+        args+=('rootflags=subvol=/Volumes/Root')
         if do_legacy ; then                         # pre bookworm layout
             args+=(initrd=0) ; ramd=1
         fi
-    elif [ -n "$args" ] ; then                      # ext4 config
+   fi
 
- #### TODO always ...
-        args+=('fsck.repair=yes')
-    fi
-
-    # other methods are not reliable on raspberry pi os ...
-    if netoption 'sysdnames' "$CEN_OPT_HOST" ; then
-        args+=('net.ifnames=1')
-    else
-        args+=('net.ifnames=0')
-    fi
+    local ifna
+    case "$CEN_OPT_IFNAMES" in
+    0)  ifna=0 ;;
+    1)  ifna=1 ;;
+    *)  if  [ "$DAT_ETCDIR/systemd/network/99-default.link" -ef '/dev/null' ] ; then
+            ifna=0
+        elif netoption 'sysdnames' "$CEN_OPT_HOST" ; then
+            ifna=1
+        fi
+    esac
+    [ -n "$ifna" ] && args+=("net.ifnames=$ifna")
 
     case "${1:-splash}" in
     -)          ;;
@@ -351,6 +364,10 @@ actionEntry() {
     do_name name "$name"                                # simplify entry name
     args+=("$@") ; line="${args[*]}"
     create -t -v line -- "cmdline-$name.txt"
+    if [ "${DAT_ENTRY_CURR:--}" != '-' ] ; then
+        copy "$DAT_ENTRY_CURR" 'cmdline.txt'
+        DAT_ENTRY_CURR='-'
+    fi
 
     # create default files and a config file
     local cmdf='cmdline-default.txt'
@@ -411,7 +428,7 @@ actionRemove() {
 }
 
 # ------------------------------------------------------------------------------
-# set root: <config>|-|. <label>|-
+# set root: <config>|-|. <label>|-|.
 #
 #   config: <name>  use cmdline-<name>.txt
 #           -       use cmdline-default.txt
@@ -421,123 +438,92 @@ actionRemove() {
 #           <label> example: cent9_root     -> root=LABEL=<label>
 #           <uuid>  example: abcd1234-03    -> root=PARTUUID=<uuid>
 #           -       1st try 'rootfs' 2 try <hostname>_(vol0|root|rootfs)
-####           .       use PARTUUID
+#           .       use PARTUUID
 # ------------------------------------------------------------------------------
 actionRoot() {
-    do_folder
-
+    do_folder -n
     local conf="${1:-.}" ; shift
     local iden="${1:--}" ; shift
+
     [ "$conf" = '.' ] && conf= ; [ "$conf" = '-' ] && conf='default'
     conf="cmdline${conf:+-}$conf.txt"
 
-    if ! [ -e "$conf" ] ; then
+    local item list puid labl karg
+
+    # parse kernel command line, get 'root=' into 1st position
+    if ! readline -a list -i "$conf" ; then
         error $"No such configuration:" "$conf" ; return
     fi
-
-    # no label arg, try rootfs or default to <host>
-    local item part
-    #if [ "$iden" = '.' ] ; then
-    #    local list indx=0
-    #    if [ -z "$CEN_OPT_DEVICE" ] ; then
-    #        error "Option '--device' missing" ; return
-    #    fi
-    #    system -e -p -a list -- blkid --probe -o value -s TYPE -s UUID "$CEN_OPT_DEVICE" || return
-    #    while [ -n "${list[indx]}" ] ; do
-    #        if [ "${list[indx]}" = 'ext4' -o "${list[indx]}" = 'btrfs' ] ; then
-    #            iden="${list[indx+1]}" ; part="/dev/disk/by-partuuid/$iden"
-    #            message -a -p "Found 'PARTUUID=%s' with '%s' filesystem" "$iden" "${list[indx]}"
-    #            break
-    #        fi
-    #        ((indx += 2))
-    #    done
-    #    if [ "$iden" = '.' ] ; then
-    #        error 'UUID not found' ; return
-    #    fi
-    if [ "$iden" = '-' ] ; then
-        if [ -b "/dev/disk/by-label/rootfs" ] ; then
-            part="/dev/disk/by-label/rootfs"
-        else
-            iden="$CEN_OPT_HOST"
-        fi
-
-    # check for device, PARTUUID and label
-    elif [ -b "$iden" ] ; then
-        part="$iden"
-    elif [ -b "/dev/disk/by-partuuid/$iden" ] ; then
-        part="/dev/disk/by-partuuid/$iden"
-    elif [ -b "/dev/disk/by-label/$iden" ] ; then
-        part="/dev/disk/by-label/$iden"
-    fi
-
-    # not yet found, try <host>_label, <host>_root, <host>_rootfs
-    [ -z "$part" ] &&
-        for item in "${CEN_OPT_HOST}_$iden" "${iden}_vol0" "${iden}_root" "${iden}_rootfs" ; do
-            [ -b "/dev/disk/by-label/$item" ] || continue
-            part="/dev/disk/by-label/$item" ; break
-        done
-    trace -a "Config: $conf  Partition: $part"
-
-    # get puid for label
-    local karg kuid kcmd puid labl
-    if [ -e "$part" ] ; then
-        for labl in "/dev/disk/by-label/"* '' ; do
-            [ "$labl" -ef "$part" ] && break
-        done
-        labl="${labl##*/}"
-        for puid in "/dev/disk/by-partuuid/"* '' ; do
-            [ "$puid" -ef "$part" ] && break
-        done
-    fi
-
-    if [ -z "$puid" ] ; then
-        if [ -n "$CEN_OPT_FORCE" ] ; then
-            trace -p $"Partition '%s' not found, ignored" "$iden"
-            part="$iden"
-        else
-            error -p $"Partition '%s' not found" "$iden" ; return
-        fi
-    else
-        puid="${puid##*/}"
-        message -a -p $"Found PARTUUID '%s' with label '%s'" "$puid" "${labl:-<none>}"
-    fi
-
-    # modify kernel command line
-    read -a karg <"$conf"
-    for item in "${karg[@]}" ; do
-        case "$item" in
-            root=LABEL=*)
-                kuid="${item##*=}" ; part="${part##*/}"
-                if [ "$CEN_OPT_UUID" = 1 ] ; then
-                    confirm -y -a -f $"Change root PARTUUID from '%s' to '%s'" "$kuid" "$puid" || return
-                    item="root=PARTUUID=$puid"
-                elif [ "$kuid" = "$part" ] ; then
-                    message -a $"Root LABEL is current, no update" ; return
-                else
-                    confirm -y -a -f $"Change root LABEL from '%s' to '%s'" "$kuid" "$part" || return
-                    item="root=LABEL=$part"
-                fi
-                ;;
-            root=PARTUUID=*)
-                kuid="${item##*=}"
-                if [ "$kuid" = "$puid" ] ; then
-                    message -a $"Root PARTUUID is current, no update" ; return
-                else
-                    confirm -y -a -f $"Change root PARTUUID from '%s' to '%s'" "$kuid" "$puid" || return
-                    item="root=PARTUUID=$puid"
-                fi
-                ;;
-        esac
-        kcmd+=" $item"
+    karg=('')
+    for item in "${list[@]}" ; do
+        [ "${item::5}" = 'root=' ] && karg="$item" || karg+=("$item")
     done
-
-    if [ -z "$kuid" ] ; then
-        error $"Found no 'root=PARTUUID' or 'root=LABEL=...' in kernel command line"
-        return
+    if [ -z "$karg" ] ; then
+        error $"Invalid configuration:" "$conf" ; return
     fi
-    kcmd="${kcmd:1}"
-    create -t -v kcmd -- "$conf"
-    message -a "Updated:" "$conf" # (PWD=$PWD)"
+
+    ___root_puuid() {
+        if [ "$CEN_OPT_UUID" = 0 ] ; then
+            ___root_label ; return
+        fi
+        for item in "${CEN_OPT_HOST}_vol0" "${CEN_OPT_HOST}_root" 'rootfs' ; do
+            if [ -b "/dev/disk/by-label/$item" ] ; then
+                item="/dev/disk/by-label/$item"
+                for puid in '/dev/disk/by-partuuid/'* ; do
+                    if [ "$puid" -ef "$item" ] ; then
+                        puid="${puid##*/}"
+                        iden="PARTUUID=$puid" ; return 0
+                    fi
+                done
+            fi
+        done
+        invoke -e $"Could not auto-detect the root partition uuid" ; return 1
+    }
+
+    ___root_label() {
+        if [ "$CEN_OPT_UUID" = 1 ] ; then
+            ___root_puuid ; return
+        fi
+        for labl in "${CEN_OPT_HOST}_vol0" "${CEN_OPT_HOST}_root" 'rootfs' ; do
+            if [ -b "/dev/disk/by-label/$labl" ] ; then
+                iden="LABEL=$labl"
+                return 0
+            fi
+        done
+        invoke -e $"Could not auto-detect the root partition label" ; return 1
+    }
+
+    ___root_check() {
+        [ -n "$1" ] || return 0
+        [ -b "/dev/disk/by-$2/$1" ] && return 0
+        invoke -e "$3" "$1" ; return 1
+    }
+
+    case "$iden" in
+    .)          ___root_puuid || return ;;
+    -)          ___root_label || return ;;
+    /*)         ;;
+    LABEL=*)    labl="${iden#*=}" ;;
+    PARTUUID=*) puid="${iden#*=}" ;;
+    *_*)        labl="$iden" ; iden="LABEL=$iden" ;;
+    *)          if [ -n "${iden//[-a-fA-F0-9]/}" ] ; then
+                    invoke -e "Invalid boot parameter:" "$iden" ; return
+                fi
+                puid="$iden" ; iden="PARTUUID=$iden"
+    esac
+
+    if [ -z "$CEN_OPT_NOCHECK" ] ; then
+        ___root_check "$labl" 'label'    $"Label '%s' not found" || return
+        ___root_check "$puid" 'partuuid' $"Partition uuid '%s' not found" || return
+    fi
+
+    if [ "$karg" = "root=$iden" ] ; then
+        message -a -p $"Boot configuration '%s' not modified" "${karg#root=}"
+    elif confirm -n -f "Use '%s' as boot contfiguration" "$iden" ; then
+        karg="root=$iden"
+        echo create -t -v kcmd -- "$conf"
+        message -a "Updated:" "$conf"
+    fi
 }
 
 # ------------------------------------------------------------------------------
@@ -567,6 +553,8 @@ options() {
         optarg 'boot'        -   -d  ;;         # existing folder
     -D|--dev*)
         optarg 'device'      -   -t  ;;         # any text
+    -F|--ifn*)
+        optarg 'ifnames'     -   -o  ;;         # ternary
     -H|--hos*)
         optarg 'host'        -   -t  ;;         # any text
     -L|--leg*)
@@ -613,6 +601,7 @@ usage() {
     usageset -o - \
        -o '-B --boot    <fldr>' $"path of boot folder         (default: /boot)" \
        -o '-D --device  <name>' $"raspberry boot device" \
+       -o '-F --ifnames <nmod>' $"systemd interface naming    (default: auto)" \
        -o '-H --host    <host>' $"override host name" \
        -o '-L --legacy  <auto>' $"pre-bookworm boot layout    (default: auto)" \
        -o '-N --nocheck'        $"don't check boot partition" \
@@ -629,8 +618,9 @@ usage() {
        -a -                     $"default parameters and 'nosplash' to disable plymouth)" \
        -a 'initrd <event>'      $"(booted system) manage initrd file" \
        -a 'remove <config>'     $"remove the given configuration" \
-       -a 'root   [<config>|-|. [<label>|<host>|<uuid>|-]]' \
-       -a -                     $"set 'root=' in kernel command line" \
+       -a 'root   [<config>|-|. [<label>|<host>|<uuid>|-|.]]' \
+       -a -                     $"set 'root=' in kernel command line. Use '-' for default" \
+       -a -                     $"and '.' to keep current setting." \
        -a 'show'                $"Show current boot configuration"
 
     usageset \
@@ -641,6 +631,7 @@ usage() {
        -p '<event>'     $"'create', 'update' or 'remove' (uninstall hook)" \
        -p '<fldr>'      $"any existing folder (must contain 'overlays')" \
        -p '<host>'      $"target host name (default: $HOSTNAME)" \
+       -p '<nmod>'      $"systemd naming mode: 0|off 1|on 2|auto" \
        -p '<name>'      $"system name, label or blockdevice" \
        -p '<overlay>'   $"an overlay file name (for config-*.txt)" \
        -p '<root>'      $"parameter for root=... (use '-' to disable, '+' for default)"
@@ -668,12 +659,14 @@ usage() {
        -t "$CEN_NAME --device /dev/sda1 config hdmi # set config 'hdmi'" \
        -t "$CEN_NAME --boot /mnt/boot show          # explicit folder" \
        -t - \
-       -t "$CEN_NAME entry server worm3_vol0        # create a cmdline file" \
+       -t "$CEN_NAME entry -                        # create default cmdline files" \
+       -t "$CEN_NAME entry server worm3_vol0        # create specific cmdline file" \
        -t "$CEN_NAME config server                  # select 'server' config" \
        -t - \
        -t "$CEN_NAME root                           # boot from <host>_root" \
-       -t "$CEN_NAME root . raspi4                  # boot from raspi4_root" \
-       -t "$CEN_NAME root - 5d50dd2e-03             # set default PARTUUID" \
+       -t "$CEN_NAME root . raspi4                  # boot via label raspi4_root" \
+       -t "$CEN_NAME root - .                       # boot via current PARTUUID" \
+       -t "$CEN_NAME root - 5d50dd2e-03             # boot via specific PARTUUID" \
        -t "$CEN_NAME root sdcard /dev/sdb3          # set sdcard config" \
        -t - \
        -t "$CEN_NAME initrd                         # create/update, set hook"
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore
@@ -3,7 +3,7 @@
 CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2017-2024; BSD License"
 CEN_TITLE="Restore a centauribackup, optionally cloning an existing machine"
 
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -m bat -r -y - '0.60:2' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -m bat -r -y - '0.60:3' || exit 2
 
 # Options
 
@@ -248,9 +248,10 @@ do_marker() {
 # ------------------------------------------------------------------------------
 do_rewrite() {
     local fnam="$1" ; shift
-    if [ -n "$CEN_OPT_DRYRUN" ] ; then
-        message -a "dryrun: not rewriting: $fnam" ; return 0
-    fi
+  #  if [ -n "$CEN_OPT_DRYRUN" ] ; then
+  #      message -a "dryrun: not rewriting: $fnam" ; return 0
+  #  fi
+    dryrun -s "Not rewriting: $fnam" && return 0
     if [ ! -r "$fnam" ] ; then
         warning "Cannot rewrite: $fnam" ; return 1
     fi
@@ -279,7 +280,7 @@ do_rename() {
     if matchpath -d -o -s vroot "$vroot-$CEN_FLG_DIST" "$vroot" ; then
         base="$PWD"
         matchpath -d -o -p -s home "$vhome-$CEN_FLG_DIST" "$vhome" ||
-            fatal "Missing home volume"
+            fatal "Missing 'Home' volume"
         folder -c -f "$vroot"
 
     elif [ -z "$CEN_OPT_DRYRUN" -a ! -d 'etc' ] ; then
@@ -294,7 +295,7 @@ do_rename() {
         return 0
     fi
 
-    local orig='<unknown>' conf="${CEN_ROOT:1}/default/centaurinetcfg"
+    local item orig='<unknown>' conf="${CEN_ROOT:1}/default/centaurinetcfg"
     [ -r 'etc/hostname' ] && orig="$(< etc/hostname)"
     if [ "$orig" = "$name" ] ; then
         if [ -z "${CEN_FLG_CLONE[1]}" ] ; then
@@ -307,15 +308,16 @@ do_rename() {
         message -a "Rename machine: $orig => $name"
     fi
 
-    do_marker "$base" 'vol0' ; do_marker "$home" "home" ; do_marker '.'
+    do_marker "$base" 'vol0' ; do_marker "$home" 'home' ; do_marker '.'
     do_machine_id
     confirm -n -b "Generate new ssh host keys" &&
         embed -i -v centaurikeys -y -q hostkeys 'etc/ssh'
 
-    # remove persistent device names
+    # remove persistent device names (legacy)
     remove -f "etc/udev/rules.d/"*-persistent-*
 
-    # clean samba cache
+    # clean dhcp and samba caches
+    remove -f 'var/lib/dhcp'/*
     remove -f 'var/lib/samba/wins.dat' 'var/cache/samba/browse.dat'
 
     # generate network configuration
@@ -331,9 +333,10 @@ do_rename() {
 
     # create resume
     do_label "$name"
-    if [ -d "etc/initramfs-tools/conf.d" ] ; then
+    if [ -d 'etc/initramfs-tools/conf.d' ] ; then
         if [ -z "$CEN_OPT_DRYRUN" ] ; then
-            echo "resume=LABEL=$CEN_DAT_LSWAP" > "etc/initramfs-tools/conf.d/resume"
+            item="resume=LABEL=$CEN_DAT_LSWAP"
+            create -t -v item -- 'etc/initramfs-tools/conf.d/resume'
             message -a "Run 'update-initramfs -u' manually to make hibernate work"
         fi
     fi
@@ -355,7 +358,7 @@ do_update() {
     local sgrb="${CEN_FLG_CLONE[3]:--}"             # 4th --clone is path of grub.cfg
     [ "$sboo" = '+' ] && sboo="$name"
     [ "$sdsk" = '+' ] && sdsk="$name"
-    trace -c -a 'update boot' "boot-label=%s  root-label=%s  grub-path=%s" "$sboo" "$sdsk" "$sgrb"
+    trace -a -c -p 'update boot' "boot-label=%s  root-label=%s  grub-path=%s" "$sboo" "$sdsk" "$sgrb"
 
     # grub: <boot-mpt>/efi/grub
     # load: <boot-mpt>/efi/loader/entries
@@ -394,7 +397,7 @@ do_update() {
     elif [ -d "$mpnt/EFI" ] ; then              # just to be sure
         firm='-' ; load="$mpnt/loader/entries" ; sgrb="$mpnt/grub"
     elif [ -d "$mpnt/grub" ] ; then
-        firm='-' ; sgrb="$mpnt" ; load='-'
+        firm='-' ; sgrb="$mpnt/grub" ; load='-'
     else
         firm="$mpnt" ; sgrb='-' ; load='-'
     fi
@@ -421,7 +424,7 @@ do_update() {
         stab+="; s/^(UUID=[-a-zA-Z0-9 ]*\/ )/LABEL=${sdsk}_root \/ /g"
         stab+="; s/^(UUID=[-a-zA-Z0-9 ]*none )/LABEL=${sdsk}_swap none /g"
         what+=('etc/fstab')
-        do_rewrite "etc/fstab" "$stab"
+        do_rewrite 'etc/fstab' "$stab"
     fi
 
     if [ "$firm" != '-' ] && [ -e "$firm/cmdline.txt" ] ; then
@@ -431,15 +434,15 @@ do_update() {
         what+=('firmware/cmdline.txt')
         do_rewrite "$firm/cmdline.txt" "$stab"
     elif [ "$sgrb" != '-' ] && [ ! -h "$sgrb" ] ; then
-        if netoption 'sysdnames' "$name" ; then
-            stab="s/^set ifnames=.*/set ifnames=/; "
-            remove '/etc/systemd/network/99-default.link'
+        if [ -z "$2" ] ; then                   # only if root is known, see fstab update
+            :
+        elif netoption 'sysdnames' "$name" ; then
+            remove 'etc/systemd/network/99-default.link'
         else
-            stab="s/^set ifnames=.*/set ifnames=0/; "
-            # stab=                     # this leaves some corner cases (virtio?)
-            symlink -n '/dev/null' '/etc/systemd/network/99-default.link'
+            symlink -n '/dev/null' 'etc/systemd/network/99-default.link'
         fi
-        stab+="s/^set myname=.*/set myname=$sdsk/"
+        [ "${sdsk:-}" = '-' ] && stab="$name" || stab="$sdsk"
+        stab="s/^set myname=.*/set myname=$stab/"
         what+=('grub/grub.cfg')
         do_rewrite "$sgrb/grub.cfg" "$stab"
     fi
@@ -478,12 +481,14 @@ do_restore() {
     *.tar.bz2)  ;;
     *.tar.lzo)  ;;
     *.tar.lzma) ;;
+    *.tar.zstd) ;;
     *.img)      isimg=1 ;;
     *.img.xz)   isimg=1 ; xpand='xzcat' ;;
     *.img.gz)   isimg=1 ; xpand='zcat' ;;
     *.img.bz2)  isimg=1 ; xpand='bzcat' ;;
     *.img.lzo)  isimg=1 ; xpand='lzop -cd' ;;
     *.img.lzma) isimg=1 ; xpand='lzcat' ;;
+    *.img.zstd) isimg=1 ; xpand='zstdcat' ;;
     *.img.*)    fatal "Unknown image compression: $file" ;;
     *)          fatal "Unknown archive type or compression: $file" ;;
     esac
@@ -626,21 +631,21 @@ do_sysrest() {
 
     if [ -n "$CEN_FLG_PART" ] ; then
        message -a "Mounting '$CEN_FLG_PART' at '$CEN_FLG_MOUNT' ..."
-       [ -z "$CEN_FLG_EXTFS" ] && fmount="-o subvol=/"
+       [ -z "$CEN_FLG_EXTFS" ] && fmount='-o subvol=/'
        system -f -p -r -- mount "$CEN_FLG_PART" "$CEN_FLG_MOUNT" $fmount
     fi
 
     folder -c -f "$CEN_FLG_MOUNT" ; CEN_FLG_MOUNT="$PWD"
-    local proot='/' phome="/home" puser="/usr"
+    local proot='/' phome='/home' puser='/usr'
     if [ -z "$CEN_FLG_EXTFS" ] ; then
         local vroot="$CEN_DAT_VROOT" vhome="$CEN_DAT_VHOME"
         if matchpath -d -o -s proot "$vroot-$CEN_FLG_DIST" "$vroot" ; then
             puser="$proot/usr"
             matchpath -d -o -s phome "$vhome-$CEN_FLG_DIST" "$vhome" ||
-                fatal "Missing home volume"
+                fatal "Missing 'Home' volume"
             message -a "btrfs volumes: $proot $puser $phome"
         elif [ -n "$CEN_FLG_DIST" ] ; then
-            fatal "Missing root volume:" "$vroot-$CEN_FLG_DIST"
+            fatal "Missing 'Root' volume:" "$vroot-$CEN_FLG_DIST"
         fi
     fi
 
@@ -650,17 +655,17 @@ do_sysrest() {
        confirm -a "Restore data to $CEN_FLG_MOUNT" || quit -t
        # restore but exclude grub stuff
        do_restore "$proot"  "$froot" \
-            "--exclude=./boot/grub/locale"  \
-            "--exclude=./boot/grub/fonts"   \
-            "--exclude=./boot/grub/i386-pc" \
-            "--exclude=./boot/grub/x86_64-efi" \
-            "--exclude=./boot/grub/grubenv" \
-            "--exclude=./boot/grub/*~"      \
-            "--exclude=./boot/grub/*.o"     \
-            "--exclude=./boot/grub/*.img"   \
-            "--exclude=./boot/grub/*.pf2"   \
-            "--exclude=./boot/grub/*.mod"   \
-            "--exclude=./boot/grub/*.lst"
+            '--exclude=./boot/grub/locale'  \
+            '--exclude=./boot/grub/fonts'   \
+            '--exclude=./boot/grub/i386-pc' \
+            '--exclude=./boot/grub/x86_64-efi' \
+            '--exclude=./boot/grub/grubenv' \
+            '--exclude=./boot/grub/*~'      \
+            '--exclude=./boot/grub/*.o'     \
+            '--exclude=./boot/grub/*.img'   \
+            '--exclude=./boot/grub/*.pf2'   \
+            '--exclude=./boot/grub/*.mod'   \
+            '--exclude=./boot/grub/*.lst'
        # create required folders
        do_fixup
     fi
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets
@@ -16,8 +16,8 @@ CEN_SVC_SHORT="Get Domain Server and secrets"
 ### END INIT INFO
 
 # Import the bash library, set name and version (--dryrun NOT FULLY IMPLEMENTED)
-PATH+=":/usr/local/bin"
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.56:2' || exit 2
+PATH+=':/usr/local/bin'
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.57:2' || exit 2
 
 # Extra option data
 CEN_OPT_NOHOOK=                         # see --nohook
@@ -46,7 +46,7 @@ DAT_DIR_SECRETS="$CEN_ROOT/secrets"             # main secrets folder
 DAT_DIR_DOWNLOAD="$DAT_DIR_TEMP/secrets-load"   # temporary download folder
 DAT_DIR_FAKE="$DAT_DIR_TEMP/secrets-fake"       # server fake data folder
 DAT_DIR_LOCAL="$DAT_DIR_SECRETS/local"          # server static data folder
-DAT_DIR_STATIC="$DAT_DIR_SECRETS/data"          # ... (sent to clients)
+DAT_DIR_STATIC="$DAT_DIR_SECRETS/data"  # ... (sent to clients)
 
 DAT_MACHINE_DIR="$CEN_ROOT/machines"    # per-machine secrets folder
 DAT_MACHINE_ID=                         # machine-id
@@ -74,7 +74,7 @@ umask 022
 # -----------------------------------------------------------------------------
 is_static() {
     # status is known already?
-    [ "$CEN_SECRETS_MODE" = "static" ] && return 0
+    [ "$CEN_SECRETS_MODE" = 'static' ] && return 0
     [ "${CEN_SECRETS_MODE:-unknown}" != "unknown" ] && return 1
     [ "$1" = "-r" ] && return 1
 
@@ -83,19 +83,19 @@ is_static() {
 
     # the data folder makes secrets 'static', e.g. not downloaded
     if [ -d "$DAT_DIR_STATIC" ] ; then
-        CEN_SECRETS_MODE="static"
+        CEN_SECRETS_MODE='static'
         remove -d "$DAT_DIR_SECRETS/import"
 
         if [ ! -d "$DAT_MACHINE_DIR" ] ; then
             netquery MASTER && folder -m -f "$DAT_MACHINE_DIR" 770 root:wheel
         fi
     else
-        CEN_SECRETS_MODE="download"
+        CEN_SECRETS_MODE='download'
         folder -m -f "$DAT_DIR_DOWNLOAD" 711 root:root
         symlink -m -n -r "$DAT_DIR_DOWNLOAD" "$DAT_DIR_SECRETS/import"
     fi
 
-    [ "$CEN_SECRETS_MODE" = "static" ]      # return status
+    [ "$CEN_SECRETS_MODE" = 'static' ]      # return status
 }
 
 # -----------------------------------------------------------------------------
@@ -115,13 +115,13 @@ do_active() {
     # special case: am I a server?
     local inam="$HOSTNAME.$CEN_NET_DOMAIN"
     if [ "$inam" = "$svr1" ] ; then             # I am primary, check secondary
-        svr1="$svr2" ; svr2="--"
+        svr1="$svr2" ; svr2='--'
     elif [ "$inam" = "$svr2" ] ; then           # I am secondary, check primary
-        svr2="--"
+        svr2='--'
     fi
 
     # yes, I am a server
-    if [ "$svr2" = "--" ] ; then
+    if [ "$svr2" = '--' ] ; then
         [ "$DAT_HOST" != "${DAT_SERVER[0]}" -a "$DAT_HOST" != "${DAT_SERVER[1]}" ] &&
             error "I am a server - ignoring server argument: $DAT_HOST"
         if [ "${svr1:--}" = '-' ] ; then
@@ -157,7 +157,7 @@ do_active() {
     fi
     while ! ___ifwait "${ilst[@]}" ; do
         # do not wait in smart or router mode (these use networkmanage orr dhcp hooks)
-        nettemp "centauriswitch" && . "$_nettemp"
+        nettemp -s 'centauriswitch'
         if ! [ "$DAT_SWITCH_MODE" = 'smart' -o  "$DAT_SWITCH_MODE" = 'router' ] ; then
             message "No interface is up - waiting..."
             timer -w 3 ; ___ifwait "${ilst[@]}" && break
@@ -175,7 +175,7 @@ do_active() {
     if [ -n "$DAT_PORT_POLL" -a "$CEN_OPT_POLL" != "ping" ] ; then
 
         # i am server - check 2nd server only for running ldap
-        if [ "$svr2" = "--" ] ; then
+        if [ "$svr2" = '--' ] ; then
             type -t -f netcat >/dev/null 2>&1 ||
                 fatal "Required 'netcat' is no installed"
             pri1="netcat -z -w3 $svr1 $DAT_PORT_POLL"
@@ -213,9 +213,9 @@ do_active() {
         # progress repeort  (phase 0 := initial call)
         if [ "$1" -gt 0 ] ; then
             local mesg="$svr1"
-            [ "$1" -gt 1 -a "$svr2" != "--" ] && mesg+=" $svr2"
+            [ "$1" -gt 1 -a "$svr2" != '--' ] && mesg+=" $svr2"
             message -i "Retry server check: $mesg"
-            progress "." ; [ -n "$wait" ] && sleep "$wait"
+            progress '.' ; [ -n "$wait" ] && sleep "$wait"
         fi
 
         # primary command   (phase 1 := primary server. 1st cmd only)
@@ -244,19 +244,19 @@ do_active() {
     # polling
     local hnam                                # set by __active
     if [ -n "$svr1" ] ; then
-        trace "Checking for server [$svr1${svr2:+ }$svr2]"
+        trace -a -c "Check for server" "[$svr1${svr2:+ }$svr2]"
         __active 0  || __active 1 || __active 2 || __active 2 || __active 3 || hnam=
     fi
     if [ -n "$hnam" ] ; then
-        message "Server is active: $hnam"
+        message -a -c "Server is active" "$hnam"
         DAT_ACTIVE="$hnam" ; DAT_HOST="$hnam" ; return 0
     fi
-    if [ "$svr2" = "--" ] ; then
+    if [ "$svr2" = '--' ] ; then
         message "Server '$svr1' not active, I am MASTER"
         DAT_BLOCKED1="$svr1"
         DAT_ACTIVE="$inam" ; DAT_HOST="$inam" ; return 0
     fi
-    trace -i "No active server"
+    trace -a "No active server"
     DAT_BLOCKED1="$svr1" ; DAT_BLOCKED2="$svr2" ; DAT_ACTIVE=
 
     hnam="${DAT_CENTAURINAME[1]:--}"
@@ -502,23 +502,29 @@ do_dirinit() {
 # ------------------------------------------------------------------------------
 _do_names=
 do_names() {
-    local oref otyp qval nick
+    local otyp qval nick
     _do_names=
 
     while [ "${1::1}" = '-' ] ; do
         case "$1" in
         --)     shift ; break ;;
-        -r)     oref=1 ;;
-        -p)     otyp="p" ;;
-        -s)     otyp="s" ;;
-        *)      fatal "do_names bad arg: $1"
+        -r)     CEN_NET_ROLE= ; DAT_CENTAURINAME= ;;
+        -p)     otyp='p' ;;
+        -s)     otyp='s' ;;
+        *)      fatal -t '-' "$1"
         esac ; shift
     done
 
     # initial load or refresh data
-    if [ -n "$oref" -o -z "${DAT_CENTAURINAME[0]}" ] ; then
-        embed -a DAT_CENTAURINAME -r centauriname --qual --nick --homedns --active --server
+    if [ -z "$DAT_CENTAURINAME" ] ; then
+        netquery -f -q -s \
+                       DAT_CENTAURINAME[0] 'server'
+        netquery -q -s DAT_CENTAURINAME[1] 'homedns'
+        netquery -q -s DAT_CENTAURINAME[2] 'MASTER'
+        netquery -q -s DAT_CENTAURINAME[3] 'primary'
+        netquery -q -s DAT_CENTAURINAME[4] 'secondary'
         DAT_ACTIVE="${DAT_CENTAURINAME[2]}"
+        [ -z "${DAT_CENTAURINAME[1]}" ] && DAT_CENTAURINAME[1]='-'
     fi
 
     # explicit name given - override homedns
@@ -539,17 +545,17 @@ do_names() {
 
     # use only servers if homedns matches any (generic) server name or is 'local'
     local item fsrv hdns="${DAT_CENTAURINAME[1]}"
-    [ "$hdns" = '-' -a -z "$1" ] && return 1    # need hdns or override
+    [ -z "$hdns" -a -z "$1" ] && return 1       # need hdns or override
     for item in 'local' "${DAT_CENTAURINAME[3]}" "${DAT_CENTAURINAME[4]}" ; do
         [ "$item" = "$hdns" ] || continue
         fsrv=1 ; break
     done
 
     # what to return
-    if [ "$otyp" = "p" ] ; then
+    if [ "$otyp" = 'p' ] ; then
         [ -z "$fsrv" ] && return 1
         qval="${DAT_CENTAURINAME[3]:--}"        # primary
-    elif [ "$otyp" = "s" ] ; then
+    elif [ "$otyp" = 's' ] ; then
         [ -z "$fsrv" ] && return 1
         qval="${DAT_CENTAURINAME[4]:--}"        # secondary
     else
@@ -590,7 +596,7 @@ do_secrets() {
     __secrets() {
         if [ "$1" != '-' ] ; then
             message -i "Retry secrets load from: $DAT_HOST"
-            progress "." ; sleep 2
+            progress '.' ; sleep 2
         fi
 
         dryrun "echo $HOSTNAME $DAT_COOKIE $DAT_MACHINE_ID |"\
@@ -655,11 +661,11 @@ do_secrets() {
 # ------------------------------------------------------------------------------
 do_server() {
     # get options
-    local maid refr coun
-    if [ "$1" = "-m" ] ; then                   # machine id only
+    local maid refr coun mesg
+    if [ "$1" = '-m' ] ; then                   # machine id only
         maid=1 ; shift
-    elif [ "$1" = "-r" ] ; then                 # refresh host
-        refr="-r" ; shift
+    elif [ "$1" = '-r' ] ; then                 # refresh host
+        refr='-r' ; shift
     fi
     if [ "${1::1}" = '-' ] ; then               # invalid arg -or- local
         DAT_HOST= ; DAT_SERVER=()
@@ -669,21 +675,22 @@ do_server() {
     # get machine id
     if [ -z "$DAT_MACHINE_ID" ] ; then
         local dmid='/var/lib/dbus/machine-id'
-        if [ ! "/etc/machine-id" -ef "$dmid" ] ; then
+        if [ ! '/etc/machine-id' -ef "$dmid" ] ; then
             error "$dmid should be a symlink to /etc/machine-id"
             return 1
         fi
-        [ -r "/etc/machine-id" ] &&
-            DAT_MACHINE_ID="$(< /var/lib/dbus/machine-id)"
+        readline -w -s DAT_MACHINE_ID -i '/etc/machine-id'
     fi
     [ -n "$maid" ] && return 0
 
-    for ((coun=0 ; coun < 15 ; coun++)) ; do
-        [ "$coun" = 0 ] || timer -w 1
+    mesg="Waiting for dhcp to provide a name server"
+    while : ; do
+        ((coun++)) && timer -w 1
 
         # get a known server - if any
         do_names $refr -p "$1" ; DAT_SERVER[0]="$_do_names"
         do_names       -s "$1" ; DAT_SERVER[1]="$_do_names"
+
         if   [ -n "${DAT_SERVER[0]}" ] ; then
             DAT_HOST="${DAT_SERVER[0]}"
         elif [ -n "${DAT_SERVER[1]}" ] ; then
@@ -692,7 +699,7 @@ do_server() {
             do_names "$1" ; DAT_HOST="$_do_names"
             # have no known server
             if [ -z "$DAT_HOST" ] ; then
-                nettemp "centauriswitch" && . "$_nettemp"
+                nettemp -s 'centauriswitch'
                 if  [ "$DAT_SWITCH_MODE" = 'static' ] ; then
                     DAT_SERVER[0]="${DAT_CENTAURINAME[3]}"
                     DAT_SERVER[1]="${DAT_CENTAURINAME[4]}"
@@ -701,7 +708,11 @@ do_server() {
                 fi
                 [ "$CEN_ACTION" = 'auto' ] || break
                 [ "$DAT_SWITCH_MODE" = 'router' ] && break
-                message -a "Waiting to get name server from dhcp" $coun
+                case "$coun" in
+                1)      message -a "$mesg" ;;
+                6|11)   message -a -p "%s since %ss" "$mesg" $((coun-1)) ;;
+                16)     message -a "Timeout waiting for dhcp" ; break
+                esac
                 continue
             fi
         fi
@@ -720,10 +731,10 @@ do_status() {
         [ -n "$CEN_SECRETS_MODE" ] && return 0          # already loaded
         CEN_SECRETS_HOST=
         CEN_SECRETS_WHAT=
-        CEN_SECRETS_MODE="unknown"
+        CEN_SECRETS_MODE='unknown'
         CEN_SECRETS_IFACE=
         [ -r "$DAT_DIR_TEMP/$CEN_NAME" ] || return 1
-        . "$DAT_DIR_TEMP/$CEN_NAME" ;       return 0
+        source "$DAT_DIR_TEMP/$CEN_NAME" ;  return 0
     fi
 
     # check temp dir (created via sys module)
@@ -732,7 +743,7 @@ do_status() {
     # prepare data
     [ "$2" = '-' ] || CEN_SECRETS_HOST="$2"
     [ "$3" = '-' ] || CEN_SECRETS_WHAT="$3"
-    [ -n "$CEN_SECRETS_MODE" ] || CEN_SECRETS_MODE="unknown"
+    [ -n "$CEN_SECRETS_MODE" ] || CEN_SECRETS_MODE='unknown'
     dryrun do_status "$*" && return 0
 
     # write
@@ -744,12 +755,13 @@ ${CEN_SECRETS_MODE@A}
 ${CEN_OPT_IFACE@A}"
     create -h - -t -v mesg -- "$DAT_DIR_TEMP/$CEN_NAME"
 
-    # update /data folder. Args are: <mode> <server> <nick>
-    local what="${CEN_SECRETS_WHAT:-UNKNOWN}"
+    # update network neighborhood folder. Args are: <mode> <server> <nick>
+    local neig what="${CEN_SECRETS_WHAT:-UNKNOWN}"
     if [ "$what" = 'UNKNOWN' ] ; then               # home/guest network offline
-        if ! [ '/data/home' -ef '/home' ] ; then
-            embed -v centauridata --quiet update "$what" &
-        fi
+        shortpath -a neig -e 'network' &&
+            if ! [ "$neig/home" -ef '/home' ] ; then
+                embed -v centauridata --quiet update "$what" &
+            fi
     else                                            # home/guest network online
         embed -v centauridata --quiet update "$what" "$CEN_SECRETS_HOST" "$DAT_CENTAURINAME" &
     fi
@@ -800,8 +812,8 @@ actionMachines() {
     done
 
     # create/protect folders
-    folder -m "@other" 770 "root:wheel"
-    system -e -p -- chown "root:wheel" . "${dirs[@]}"
+    folder -m "@other" 770 'root:wheel'
+    system -e -p -- chown 'root:wheel' . "${dirs[@]}"
     system -e -p -- chmod 770 . "${dirs[@]}"
 
     # update keytabs
@@ -817,14 +829,17 @@ actionMachines() {
 actionRegister() {
     do_server -r "$1" || return                 # get home server
     local sdir="$DAT_MACHINE_DIR/$HOSTNAME"
-    local verb ; [ "$CEN_VERB" -gt 1 ] && verb='-v'
-
-    sysversion -u || return
-    message -p "Register host '%s (%s)' at server '%s'" "$HOSTNAME" "$CEN_SYS_NICKNAME" "$DAT_HOST"
-    [ -n "$CEN_SYS_NICKNAME" ] && verb+=" --nick $CEN_SYS_NICKNAME"
-    [ -n "$CEN_OPT_FORCE" ] && verb+=" --force"
-    system -e -- ssh -x "root@$DAT_HOST" \
-        centaurimachines $verb --add "$HOSTNAME/$DAT_MACHINE_ID"
+    local opts=() conf
+    netquery -s conf 'config'
+    sysversion -u                               # best efford, ignore errors
+    message -p "Register host '%s (%s)' at server '%s'" \
+        "$HOSTNAME" "$CEN_SYS_NICKNAME:$conf" "$DAT_HOST"
+    optmake -a opts -b 'verbose'
+    optmake -a opts -b 'force'
+    optmake -a opts -n 'nick'   "$CEN_SYS_NICKNAME"
+    optmake -a opts -n 'domain' "$conf"
+    optmake -a opts -n 'add'    "$HOSTNAME/$DAT_MACHINE_ID"
+    system -e -- ssh -x "root@$DAT_HOST" centaurimachines "${opts[@]}"
 }
 
 # -----------------------------------------------------------------------------
@@ -889,6 +904,8 @@ actionSecrets() {
 
     # create or update /etc/samba/smbpasswd
     ___mkpasswd() {
+# TODO check of 'option addc'   netoption 'addc' "$HOSTNAME"
+        netquery server && return 0                     # not for a server
         local file='/etc/samba/smbpass.conf'
         if [ ! -e "$file" ] || ! system -q -c 'pdbedit' ; then
             warning "Missing samba config:" "$file" ; return
@@ -914,7 +931,7 @@ actionSecrets() {
     # load passwords from seed, make secrets files: <seed>
     ___useseed() {
         local padm ptru ppub prep psyn proo ploc
-        do_passwords "$1"
+        do_passwords "$1" || { error "Failed to read seed:" "$1" ; return ; }
         do_passwords proo 'root'
         do_passwords ploc 'local'
         do_passwords ptru 'smbtrust'
@@ -977,8 +994,8 @@ actionServer() {
         fi
         folder -c -f "$mdir"
 
-        [ -f "krb5.keytab" ] && sadd="--add-file=./krb5.keytab "
-        [ -f "repository.conf" ] && sadd+="--add-file=./repository.conf "
+        [ -f 'krb5.keytab' ] && sadd="--add-file=./krb5.keytab "
+        [ -f 'repository.conf' ] && sadd+="--add-file=./repository.conf "
 
     # no machine dir (are we a guest server?)
     else
@@ -1073,31 +1090,31 @@ actions() {
     stop)
         invoke -        actionInit      0 ;;
     sta*)
-        invoke "status" -               0 ;;
+        invoke 'status' -               0 ;;
 
     # mode switching
     aut*)
-        invoke "auto"   -               0 ;;
+        invoke 'auto'   -               0 ;;
     cli*)
-        invoke "client" actionStart   0 1 ;;
+        invoke 'client' actionStart   0 1 ;;
     loc*)
         invoke 'local'  actionStart     0 ;;
 
     # other commands
     ini*)
-        invoke "init"     -           0 1 ;;
+        invoke 'init'     -           0 1 ;;
     mac*)
-        invoke "machines" -             0 ;;
+        invoke 'machines' -             0 ;;
     reg*)
-        invoke "register" -           0 1 ;;
+        invoke 'register' -           0 1 ;;
     lda|ldap)
-        invoke "ldap"     actionSecrets   ;;
+        invoke 'ldap'     actionSecrets   ;;
     sam*)
-        invoke "samba"    actionSecrets 2 ;;
+        invoke 'samba'    actionSecrets 2 ;;
     sec*)
-        invoke "secrets"  -             1 ;;
+        invoke 'secrets'  -             1 ;;
     ser*)
-        invoke "server"   -             0 ;;
+        invoke 'server'   -             0 ;;
     esac
 }
 
@@ -1130,7 +1147,7 @@ usage() {
        -a "auto                 Find an active server and download secrets." \
        -a "                     Does nothing if secrets and state are current" \
        -a "client   [<server>]  Find/check an active server and download secrets." \
-       -a "                     The default server is: "${_do_names:--}"" \
+       -a "                     The default server is: ""${_do_names:--}" \
        -a "                     No <server> arg: check if server is still valid" \
        -a "local                drop current secrets, init secrets to defaults" \
 
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriswap b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriswap
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriswap
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriswap
@@ -1,6 +1,6 @@
 #!/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2016-2022; BSD License"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2016-2024; BSD License"
 CEN_TITLE="Swap File/Partition Tool and Service"
 
 ### BEGIN INIT INFO
@@ -16,10 +16,10 @@ CEN_TITLE="Swap File/Partition Tool and Service"
 ### TODO zwap support - echo 1 > /sys/modules/zswap/enabled ... max_percentage
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v -y "$0" "0.24" || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v -y - '0.25:3' || exit 2
 
 CEN_SVC_SHORT="Swap File/Partition Service"
-CEN_SVC_WANTED_BY="multi-user.target"
+CEN_SVC_WANTED_BY='multi-user.target'
 
 CEN_OPT_BASE=                   # see --base
 CEN_OPT_TARGET=                 # see --target
@@ -43,7 +43,7 @@ swap_location() {
     CEN_DAT_LDEST= ; CEN_DAT_TDEST=             # destination location/type
 
     # destination type options
-    while [ "${1::1}" = "-" ] ; do
+    while [ "${1::1}" = '-' ] ; do
       case "$1" in
       -)    break ;;
       --)   shift ; break ;;
@@ -71,7 +71,7 @@ swap_location() {
     fi
 
     # new swap location
-    if [ "${1:--}" = "-" ] ; then
+    if [ "${1:--}" = '-' ] ; then
         CEN_DAT_LDEST="${CEN_DAT_LCURR:-$CEN_DAT_SWAP}"
         # do not use current if type does not match
         [ -n  "$CEN_DAT_TCURR" -a "$CEN_DAT_TCURR" != "$CEN_DAT_TDEST" ] &&
@@ -87,7 +87,7 @@ swap_location() {
                 ;;
     folder)     [ -d "$CEN_DAT_LDEST" ] && return 0
                 ;;
-    "")         return 0 ;;
+    '')         return 0 ;;
     *)          [ -h "$CEN_DAT_SWAP" -a "$CEN_DAT_SWAP" = "$CEN_DAT_LDEST" ] && return 0
                 [ -b "$CEN_DAT_LDEST" -o -d "$CEN_DAT_LDEST" ] || return 0
     esac
@@ -100,7 +100,7 @@ swap_delete() {
     if [ -z "$CEN_OPT_BASE" ] ; then
         message -a "Disable swapping ..."
         system -q swapoff -a
-        [ "$1" = "-d" ] && return 0
+        [ "$1" = '-d' ] && return 0
     fi
 
     [ -n "$CEN_DAT_LCURR" -a -z "$CEN_OPT_TARGET" ] || return 0
@@ -116,10 +116,10 @@ swap_delete() {
 
     # remove swap file
     if [ -e "$fdel" ] ; then
-        message -a "Delete existing swap file: $fdel"
+        message -a "Delete existing swap file:" "$fdel"
         remove -- "$fdel"
         if [ -e "$fdel" -a -z "$CEN_OPT_DRYRUN" ] ; then
-            error "Failed to delete swap file: $fdel"
+            error "Failed to delete swap file:" "$fdel"
             return 1
         fi
     fi
@@ -149,7 +149,7 @@ swap_create() {
         remove -- "$1"
 
         message -a "New swapfile: $1 ($smsg)"
-        if [ "$2" = "0"  -o "$CEN_ACTION" = "legacy" ] ; then
+        if [ "$2" = "0"  -o "$CEN_ACTION" = 'legacy' ] ; then
             system -e -p touch "$1"
             error -t || return 1
             [ "$2" = "0" -o "$2" -gt 512 ] && ___legacy_alloc "$1" "$2" 512
@@ -163,14 +163,14 @@ swap_create() {
         [ "$1" -ef "$CEN_DAT_SWAP" ] || symlink -n -- "${CEN_OPT_TARGET:-$1}" "$CEN_DAT_SWAP"
         error -t || return 1
 
-        [ "$CEN_ACTION" = "start" -o -n "$CEN_OPT_BASE" ] && return 0
+        [ "$CEN_ACTION" = 'start' -o -n "$CEN_OPT_BASE" ] && return 0
         message -a "Enable swapping ..."
         system -e -p swapon "$1"
         error -t                                        # return status
     }
 
     if [ "$1" = "-p" ] ; then
-        local labl="${2:--}" ; [ "$2" = "-" ] && labl="${HOSTNAME}_swap"
+        local labl="${2:--}" ; [ "$2" = '-' ] && labl="${HOSTNAME}_swap"
         message -a "New swap device: $CEN_DAT_LDEST  (Label=$labl)"
         system -e -p mkswap -L "$labl" "$CEN_DAT_LDEST"
         if error -t && [ -z "$CEN_OPT_BASE" ] ; then
@@ -209,7 +209,7 @@ swap_create() {
 swap_stat() {
     [ -n "$CEN_OPT_TARGET" ] && return
     local pfmt="%-7s swap location: %-20s %s\n"
-    if [ "$CEN_OPT_BASE" = "-" ] ; then
+    if [ "$CEN_OPT_BASE" = '-' ] ; then
         :
     elif [ -n "$CEN_DAT_LCURR" ] ; then
         message -a -p "$pfmt" "Current" "$CEN_DAT_LCURR" "Type: ${CEN_DAT_TCURR:--unknown-}"
@@ -281,12 +281,12 @@ find_swap() {
 
 # check if swap is configured in fstab: [-w|-e]
 check_fstab() {
-    [ "$CEN_OPT_BASE" = "-" ] && return 0
+    [ "$CEN_OPT_BASE" = '-' ] && return 0
     [ -r "$CEN_OPT_BASE/etc/fstab" ] || return 0
 
     local mtyp=message madd
-    [ "$1" = "-e" ] && mtyp=error
-    [ "$1" = "-w" ] && mtyp=warning
+    [ "$1" = '-e' ] && mtyp=error
+    [ "$1" = '-w' ] && mtyp=warning
 
     local mdev mmnt ftyp mxxx
     while read mdev mmnt ftyp mxxx ; do
@@ -321,11 +321,16 @@ actionShare() {
 actionNone() {
     check_fstab -w
     if swap_location ; then
-        [ "$CEN_DAT_LCURR" = '/dev/null' ] && return
-        swap_stat
-        swap_delete
+        if [ "$CEN_DAT_LCURR" != '/dev/null' ] ; then
+            swap_stat
+            swap_delete
+        fi
     fi
-    symlink -x -- '/dev/null' "$CEN_DAT_SWAP"
+    if [ "$CEN_ACTION" = 'void' ] ; then
+        symlink -x -- '/dev/null' "$CEN_DAT_SWAP"
+    else
+        remove "$CEN_DAT_SWAP"
+    fi
 }
 
 # ------------------------------------------------------------------------------
@@ -346,8 +351,8 @@ actionFile() {
 actionSwap() {
     check_fstab -e || return
 
-    local driv labl part="-"
-    if [ "${1:--}" = "-" ] ; then
+    local driv labl part='-'
+    if [ "${1:--}" = '-' ] ; then
         shift
     elif [ "${1::1}" = "/" ] ; then           # partion argument
         part="$1" ; shift
@@ -355,12 +360,12 @@ actionSwap() {
     labl="${1:--}"
 
     # try by label
-    if [ "$part" = "-" -a "$labl" = "-" ] ; then
+    if [ "$part" = '-' -a "$labl" = '-' ] ; then
         if ! find_swap ; then
              error "Cannot find a swap device" ; return 1
         fi
         part="$_find_swap"
-    elif [ "$part" = "-" ] ; then
+    elif [ "$part" = '-' ] ; then
         driv="/dev/disk/by-label/$labl"
         if ! [ -b "$driv" ] ; then
             error "Cannot find device for label: $labl" ; return 1
@@ -451,17 +456,17 @@ actionStop() {
 options() {
     case "$1" in
 
-    "") if [ "${CEN_OPT_BASE:--}" != "-" ] ; then
+    '') if [ "${CEN_OPT_BASE:--}" != '-' ] ; then
             folder -c -f "$CEN_OPT_BASE"
-            CEN_OPT_BASE="$PWD" ; [ "$CEN_OPT_BASE" = "/" ] && CEN_OPT_BASE=
+            CEN_OPT_BASE="$PWD" ; [ "$CEN_OPT_BASE" = '/' ] && CEN_OPT_BASE=
             CEN_DAT_SWAP="$CEN_OPT_BASE$CEN_DAT_SWAP"
-            message -a "Base folder:" "${CEN_OPT_BASE:-/}"
+            message -a -c "Base folder" "${CEN_OPT_BASE:-/}"
         fi
         ;;
     -B|--bas|--base)
-        optarg "base"     CEN_OPT_BASE    -t ;;         # text
+        optarg 'base'     CEN_OPT_BASE    -t ;;         # text
     -T|--tar*)
-        optarg "target"   CEN_OPT_TARGET  -t ;;         # text
+        optarg 'target'   CEN_OPT_TARGET  -t ;;         # text
 
     esac
 }
@@ -478,19 +483,21 @@ actions() {
     stop)
         invoke -        -            0 ;;
     sta|stat|sta*)
-        invoke "status" -            0 ;;
+        invoke 'status' -            0 ;;
 
     # other commands
     non*)
-        invoke "none"   -            0 ;;
+        invoke 'none'   -            0 ;;
     fil*)
-        invoke "file"   -            0 2 ;;
+        invoke 'file'   -            0 2 ;;
     leg*)
-        invoke "legacy" actionFile   0 2 ;;
+        invoke 'legacy' actionFile   0 2 ;;
     sha*)
-        invoke "share"  -            1 ;;
+        invoke 'share'  -            1 ;;
     swa*)
-        invoke "swap"   -            0 2 ;;
+        invoke 'swap'   -            0 2 ;;
+    voi|void)
+        invoke 'void'   actionNone   0 ;;
     esac
 }
 
@@ -500,16 +507,17 @@ actions() {
 usage() {
     usageset \
     -o - \
-    -o "-B --base   <fldr>   "$"mount folder for target system (no swapon/swapoff)" \
-    -o "-T --target <dest>   "$"override link target for /.centauri"
+    -o '-B --base   <fldr>'   $"mount folder for target system (no swapon/swapoff)" \
+    -o '-T --target <dest>'   $"override link target for /.centauri"
     usageset \
-    -a "none                 "$"disable service (link $CEN_DAT_SWAP to /dev/null)" \
-    -a "file   [<path>|- [<mbyte>]" \
-    -a "                     "$"create swap file, '-' for default location" \
-    -a "legacy ...           "$"like 'file' if fallocate fails (fat32 etc.)" \
-    -a "share  <part>        "$"share a partition for windows/linux swap files" \
-    -a "swap   [<part>|-] [<label>]" \
-    -a "                     "$"create/label swap partition, '-' try to find"
+    -a 'none'                 $"disable service (link '$CEN_DAT_SWAP' to /dev/null)" \
+    -a 'file   [<path>|- [<mbyte>]' \
+    -a -                      $"create swap file, '-' for default location" \
+    -a 'legacy ...'           $"like 'file' if fallocate fails (fat32 etc.)" \
+    -a 'share  <part>'        $"share a partition for windows/linux swap files" \
+    -a 'swap   [<part>|-] [<label>]' \
+    -a -                      $"create/label swap partition, '-' try to find" \
+    -a 'void'                 $"reset configuration (remove '$CEN_DAT_SWAP' link)"
     usageset \
     -t $"Creates either a real swapfile (action: file) --or-- a link to a mounted folder" \
     -t $"on a (vfat)partition with a swapfile (action: share)  --or--  a link to a swap" \
