fake credetials, updates, incomplete source

diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net
@@ -744,7 +744,11 @@ _cen_net_maprule() {
     CEN_NET_IFMAP=() ; set -f
     for _item in "${CEN_NET_IFACES[@]}" ; do
         set -- $_item
-        [[ "$HOSTNAME" == $2 ]] || continue
+        case "$2" in
+            $HOSTNAME)  ;;
+            *[?*\[]*)   [[ "$HOSTNAME" == $2 ]] || continue ;;
+            *)          continue
+        esac
         [ "$3" = '-' ] && break                 # stop rule
         if [ "${3/:/}" != "$3" ] ; then         # mac rule
             warning -c $"not implemented" -- "iface $_item"
@@ -1872,7 +1876,7 @@ netquery() {
 # ------------------------------------------------------------------------------
 # netresolv - Read or write an /etc/resolv.conf file
 #
-# Call:     (1) netresolv -r
+# Call:     (1) netresolv -r [<what>]
 #           (2) netresolv [-d <host>] [<domain>|- [<server>|-...]]
 #
 # Options:  -d  specify the 1st nameserver
@@ -1881,6 +1885,7 @@ netquery() {
 # Arguments:<host>     a fully qualified host name
 #           <domain>   the DNS domain name
 #           <server>   a fully qualifed DNS server name
+#           <what>     read filter: search|domain|nameserver
 #
 #.Examples: netresolv              # write configured defaults to resolv.conf
 #.          netresolv -d alpha     # put alpha at 1st place
@@ -1893,18 +1898,23 @@ netresolv() {
 
     # read resolv.conf
     if [ "$1" = '-r' ] ; then
-        _netresolv=('')
-        [ -r "$conf" ] || return 1
+        _netresolv=()
+        if [ ! -r "$conf" ] ; then
+            error $"Cannot read file:" "$conf" ; return 1
+        fi
         local keyw valu xxxx
         while read -r keyw valu xxxx ; do
+            [ -n "$2" ] && [ "$keyw" != "$2" ] && continue
             case "$keyw" in
-            search|domain)
-                _netresolv[0]="${valu:--}" ;;
+            domain)                             # must preceed nameserver
+                _netresolv=("${valu:--}") ;;
+            search)                             # fallback only ...
+                [ -z "$_netresolv" ] && _netresolv+=("${valu:--}") ;;
             nameserver)
                 _netresolv+=("${valu:--}")
             esac
         done < "$conf"
-        return 0
+        [ -n "$_netresolv" ] && return 0 ; return 1 # failure if no data
     fi
 
     # default host
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_sys b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_sys
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_sys
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_sys
@@ -43,10 +43,10 @@
 #,      [[syssetup()]]
 #,      °  └── [[_centauri_bash_ext]]
 #
-# Copyright Dr. J. Pfennig (c) 2019-2024
+# Copyright Dr. J. Pfennig (c) 2019-2025
 # ------------------------------------------------------------------------------
 
-CEN_MODULES['_centauri_bash_sys']='0.28:4'
+CEN_MODULES['_centauri_bash_sys']='0.29:4'
 
 CEN_SYS_STATE_DIR="$CEN_ROOT/persistent"    # non-volatile
 CEN_SYS_CACHE_DIR="$CEN_ROOT/transient"     # volatile
@@ -68,6 +68,13 @@ CEN_SYS_PLASMA=                 # kde plasma version (sortable)
 CEN_SYS_QTVERS=                 # qt version (sortable)
 
 # ------------------------------------------------------------------------------
+# data from _cen_ins_archinfo
+# ------------------------------------------------------------------------------
+
+CEN_SYS_CPU_ARCH=               # amd64 arm64 armhf
+CEN_SYS_PLATFORM=               # x86|arm (pc)  rpi (raspi2-5)  r32 (raspi1-2)
+
+# ------------------------------------------------------------------------------
 # default data for sysconfig (overridden by config file)
 # ------------------------------------------------------------------------------
 
@@ -81,28 +88,37 @@ CEN_PATH_REXP=()                # list of path replacements
 CEN_ROOTDEFS=()                 # see _cen_sys_rootdefs
 
 # ------------------------------------------------------------------------------
+# call function in _centauri_bash_ins: <func> <arg>...
+# ------------------------------------------------------------------------------
+_cen_ins_call() {
+    $CEN_TRACE2 -a -c 'installer call' "$*"
+    [ -z "${CEN_MODULES['_centauri_bash_ins']}" ] && embed -m '_centauri_bash_ins'
+    _cen_ins_$1 "${@:2}"
+}
+
+# ------------------------------------------------------------------------------
 # fill CEN_ROOTDEFS from CEN_INSTALL: [<rootdefs>]
 # ------------------------------------------------------------------------------
 _cen_sys_rootdefs() {
     [ -n "$CEN_ROOTDEFS" -a "${1:--}" = '-' ] && return 0
-    embed -m '_centauri_bash_ins'
-    _cen_ins_chksystemd
-    _cen_ins_rootdefs "$1"
+    _cen_ins_call chksystemd
+    _cen_ins_call rootdefs "$1"
 }
 
 # ------------------------------------------------------------------------------
 # sysversion - determine os/kde versions, read/write version file
 #
-# Call:     sysversion [-e|-f] [-k] [-m] [-o] [-r|-u|-w]
+# Call:     sysversion [-e|-f] [-a] [-k] [-m|-v] [-o] [-r|-u|-w]
 #
-# Options:  -e  report error when information cannot be obtained
+# Options:  -a  get hardware architecture and platform
+#           -e  report error when information cannot be obtained
 #           -f  make errors fatal
 #           -k  get kde and plasma version, see remarks about kde/plasma
 #           -m  print version info via [[message()]]
 #           -o  get os version
 #           -r  cache read only, return **false** for no cached data
 #           -u  update cache if needed
-#           -m  print version info via [[trace()]]
+#           -v  print version info via [[trace()]]
 #           -w  refresh information and write cache
 #
 # Variables:The function tries to obtain the following data:
@@ -117,6 +133,9 @@ _cen_sys_rootdefs() {
 #,          CEN_SYS_KDEVERS  -  KDE main version (sortable)
 #,          CEN_SYS_PLASMA   -  KDE plasma version (sortable)
 #,          CEN_SYS_QTVERS   -  QT version (sortable)
+#
+#,          CEN_SYS_CPU_ARCH -  amd64 arm64 armhf
+#,          CEN_SYS_PLATFORM -  x86|arm (pc)  rpi (raspi2-5)  r32 (raspi1-2)
 #
 # Storage:  The root user only uses the shared cache:
 #
@@ -163,13 +182,14 @@ sysversion() {
 
     ### main ###
 
-    local _flgk _flgo _flgu _flgw _fpla _otra _oerr=':' _errk
+    local _flgk _flgo _flgu _flgw _fpla _oarc _otra _oerr=':' _errk
     if [ $# = 0 ] ; then                            # do nothing if state is loaded
         [ -n "$CEN_SYS_VERSION" -a -n "$CEN_SYS_KDEVERS" ] && return 0
         _flgo=1 ; _flgk=1 ; _flgu=1
     else
         while [ $# -gt 0 ] ; do
         case "$1" in
+        -a)   _oarc=1 ;;
         -e)   _oerr='error' ;;
         -f)   _oerr='fatal'  ;;
         -k)   _flgk=1 ; _errk=1
@@ -186,6 +206,12 @@ sysversion() {
         [ "$EUID" = 0 -a "$_flgw" != 0 ] && _flgu=1 # root does implicit update
         [ -z "$_flgk$_flgo$_flgr" ] && {  _flgk=1 ; _flgo=1 ; }
     fi
+
+    if [ -n "$_oarc" ] ; then
+        _cen_ins_call archinfo $_otra CEN_SYS_CPU_ARCH CEN_SYS_PLATFORM ||
+            _oerr $"Unsuported architecture" "$CEN_SYS_CPU_ARCH"
+    fi
+
     # 1st step: try to read, prefer system file
 
     if [ "$_flgw" = 1 -o -n "$_otra" ] ; then       # opt -w|-m skip read
@@ -227,20 +253,19 @@ sysversion() {
         [ -n "$_flgo$_flgk" ] && $CEN_TRACE -a -c -p ' ' $"Get %s version" "$_text"
     fi
 
-    embed -m '_centauri_bash_ins'
     if [ -n "$_flgo" ] ; then
-        _cen_ins_version -s
+        _cen_ins_call version -s
         if [ "${CEN_SYS_NICKNAME:--}" = '-' ] ; then
             $_oerr $"Linux distribution unknown" ; return 1
         fi
     fi
     if [ -n "$_flgk" ] ; then
-        _cen_ins_version -k
+        _cen_ins_call version -k
         if [ "$CEN_SYS_KDEVERS" = '-' ] ; then
             $_oerr $"No KDE version found" ; [ -n "$_errk" ] && return 1
         fi
     fi
-    [ -n "$_otra" ] && _cen_ins_version $_otra
+    [ -n "$_otra" ] && _cen_ins_call version $_otra
 
     if [ "$_flgw" != 1 ] ; then                     # opt -w always writes
         [ -z "$_flgu" ] && return 0                 # opt -u wanted to update
@@ -249,7 +274,7 @@ sysversion() {
 
     $CEN_TRACE -a -c -p ' ' $"Update '%s'" "$CEN_SYS_STATE_FILE"
     folder -m "${CEN_SYS_STATE_FILE%/*}" '775'
-    _cen_ins_version -w                             # return state
+    _cen_ins_call version -w                        # return state
 }
 
 # ------------------------------------------------------------------------------
@@ -316,13 +341,13 @@ syssetup() {
     done
 
     # initial install config is expected in CEN_ROOTDEFS
-    _cen_sys_rootdefs "${2:-$1}" || return 1        # also load _centauri_bash_ins
+    _cen_sys_rootdefs "${2:-$1}" || return 1
 
     if [ "$_updt" = '-n' ] ; then                   # copy library files
         [ "${1:--}" = '-' ] && fatal $"Missing argument:" '<orig>'
         [ "${2:--}" = '-' ] && fatal $"Missing argument:" '<dest>'
         folder -c -f -- "${1:-$CEN_ROOT}" ; shift
-        _cen_ins_files ; return                     # return status
+        _cen_ins_call files ; return                # return status
     fi || :
 
     # sysconfig, is called twice during setup as the config file may have changed
@@ -336,8 +361,8 @@ syssetup() {
     splitjoin -j CEN_INSTALL -d ':' -i CEN_ROOTDEFS
     $CEN_TRACE -a $"Installation configuration:" "${CEN_INSTALL[@]#$CEN_PATHS}"
 
-    _cen_ins_library $_remv $_updt $_usrv       # run update/install
-     _stat=$? ; [ "$_stat" = 128 ] && return 128 # cancelled
+    _cen_ins_call library $_remv $_updt $_usrv      # run update/install
+     _stat=$? ; [ "$_stat" = 128 ] && return 128    # cancelled
 
     if [ -z "$_remv" -a "$_updt" != '-t' ] ; then
         local _fold="$PWD"
@@ -427,7 +452,7 @@ sysinfo() {
         uninst*)    _iopt='-r' ;;
         update)     _iopt='-u' ;;
         detailed)   _dopt=1 ;;
-        ver*)       sysversion -f -m -u ; quit ;;
+        ver*)       sysversion -a -m -u ; quit ;;
         *)          ___cen_sys_help -f
     esac
 
@@ -497,7 +522,7 @@ sysconfig() {
     # reader callback: <line>
     ___cen_sys_read() {
         set -f ; eval set -- $1 ; set +f ; local _skey="$1" ; shift
-        $CEN_TRACE2 "[library] $_skey $*"
+        $CEN_TRACE2 -a  -c '[library]' "$_skey $*"
         local _sifs="$IFS"
 
         # reset statements
@@ -517,10 +542,10 @@ sysconfig() {
             obsolete)  CEN_SYS_OBSOLETE+=("$@") ;;
             service)   CEN_SYS_SERVICE+=("$@") ;;
             defaults)  ;;                               # obsolete, ignore
-            repath )   configfile -w "sysconfig" 3 + $#
+            repath )   configfile -w 'sysconfig' 3 + $#
                        IFS=$'\a' CEN_PATH_REXP+=("$*") ; IFS="$_sifs"
                        ;;
-            *)         configfile -w "sysconfig"
+            *)         configfile -w 'sysconfig'
         esac
         return 0
     }
@@ -546,31 +571,27 @@ sysconfig() {
     folder -f -- "$CEN_ROOT"
     [ -w "$CEN_ROOT" ] || fatal $"You are not allowed to alter this installation"
 
-    {   embed -m '_centauri_bash_run'                       # load modules ext/iom/run
-        CEN_SYS_INCLUDE=() ; CEN_SYS_EXCLUDE=() ; CEN_SYS_OBSOLETE=()
-        CEN_SYS_SERVICE=() ; CEN_PATH_REXP=()
-        _cen_run_config -p "${CEN_PATHS[6]}/centauri-bash-lib" \
-                        -r ___cen_sys_read 'library' || _stat=$?
-        shortpath -q || _stat=$?                            # init paths cache
+    embed -m '_centauri_bash_run'                       # load modules ext/iom/run
+    CEN_SYS_INCLUDE=() ; CEN_SYS_EXCLUDE=() ; CEN_SYS_OBSOLETE=()
+    CEN_SYS_SERVICE=() ; CEN_PATH_REXP=()
+    _cen_run_config -p "${CEN_PATHS[6]}/centauri-bash-lib" \
+                    -r ___cen_sys_read 'library' || _stat=$?
+    shortpath -q || _stat=$?                            # init paths cache
 
-        if [ -n "$_popt" -a -d "$CEN_TOOLS" ] ; then        # generate proxy
-            local _parr _prox
-            _cen_run_config -v _parr 'proxy'
-            splitjoin -j _prox -n -i _parr
-            embed -m '_centauri_bash_ins'
-            _cen_ins_proxy "$_prox" || _stat=$?
-        fi || :
+    if [ -n "$_popt" -a -d "$CEN_TOOLS" ] ; then        # generate proxy
+        local _parr _prox
+        _cen_run_config -v _parr 'proxy'
+        splitjoin -j _prox -n -i _parr
+        _cen_ins_call proxy "$_prox" || _stat=$?
+    fi || :
 
-        if [ -n "$_copt" -a -d "$CEN_LIBRARY" ] ; then      # bash completion
-            embed -m '_centauri_bash_ins'
-            _cen_ins_completion || _stat=$?
-        fi
+    if [ -n "$_copt" -a -d "$CEN_LIBRARY" ] ; then      # bash completion
+        _cen_ins_call completion || _stat=$?
+    fi
 
-        if [ -n "$_sopt" ] ; then                           # systemd check
-            embed -m '_centauri_bash_ins'
-            _cen_ins_chksystemd || _stat=$?
-        fi
-    } || :
+    if [ -n "$_sopt" ] ; then                           # systemd check
+        _cen_ins_call chksystemd || _stat=$?
+    fi
     return $_stat
 }
 
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriclock b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriclock
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriclock
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriclock
@@ -1,22 +1,244 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Dr. J. Pfennig (c) 2024; all rights reserved"
-CEN_TITLE=$"Template using command line verbs (action syntax)"
+CEN_LEGAL="Dr. J. Pfennig (c) 2024-2025; all rights reserved"
+CEN_TITLE=$"An extendable HTML based Day-Time-Clock"
 
 # Import the bash library
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -g - '0.10:3' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -g - '0.12:5' || exit 2
 
 #context -v 2                       # debug output
 
-# Data
+# Options and data
+
+CEN_OPT_BASE=                       # base folder
+CEN_OPT_EXEC=                       # startup tool
+CEN_OPT_HTML=                       # HTML file
 CEN_OPT_INVERT=                     # coordinate inversion
+CEN_OPT_LANG=                       # language
+CEN_OPT_SCALE=                      # scaling
+CEN_OPT_TIMER=                      # timer
+
 DAT_DPMS_OFF=                       # see actionTimer
 DAT_UNCLUTTER=
 
+# started as an appliance?
+
 if [ "$CEN_NAME" = '.centauristartup' ] ; then
-    CEN_NAME='centauriclock'
-    [ $# = 0 ] && set -- run
+    CEN_NAME='centauriclock' ; CEN_OPT_BASE='-' ;  CEN_OPT_TIMER=1
+    [ $# = 0 ] && set -- run --gui=0
 fi
+
+
+DAT_BASEDIR="~/.local/$CEN_NAME"    # defaults ...
+DAT_HTMLTXT="$CEN_NAME.html"
+DAT_SIZEPNT='10vw'
+DAT_STARTUP="${CEN_NAME}.bash"
+DAT_LANGGUI='en'
+
+case "${LANG,,}" in                 # get internal language code...
+*_us*)  DAT_LANGGUI='us' ;;
+en*)    ;;
+de*)    DAT_LANGGUI='de' ;;
+fr*)    DAT_LANGGUI='fr' ;;
+*)      DAT_LANGGUI="${LANG::2}"
+esac
+
+# ------------------------------------------------------------------------------
+# Create clock html: <path>
+# ------------------------------------------------------------------------------
+create_html() {
+    create -f -c -- "$1" <<!EOF
+<!DOCTYPE html>
+<html lang="en" class='croot'>
+<head>
+  <meta charset="UTF-8">
+  <title>JavaScript Digital Clock</title>
+  <style>
+    body {
+      margin: 0;
+      padding: 0;
+      height: 100vh;
+    }
+
+    /* layout is based on unit 'rem', so font and font-size must be set here */
+    .croot {
+      /* Noto Sans: is a tabular font and can be downloaded from Google, it is
+            not installed by default.
+         Quicksand: very nice font, but not tabular. This is why we use two
+            cells to display hour and minute.
+         sans-serif: used as a fall-back (typically aliased to 'DejaVu Sans'.
+
+         font-size: use '10vw' for nice automatic scaling on 16:9 displays
+      */
+      font-family: "Noto Sans", "Quicksand", "sans-serif";
+      font-size: 10vw;
+      font-variant-numeric: tabular-nums;
+      overflow: hidden;
+    }
+
+    .cclock {
+      width: 100%;
+      height: 100%;
+      display: flex;
+      flex-direction: column;
+      justify-content: center;
+      align-items: center;
+      background-color: black;
+    }
+
+    .ctime {
+      font-size: 3.9rem;
+      font-weight: bold;
+      color: #ccf;
+      margin-top: calc(10vh - 2.0rem);
+      margin-bottom: calc(15vh - 1.5rem);
+    }
+    .cdigit {
+      display: inline-block;
+      width: 46vw;
+    }
+    .cdsepa {
+      display: inline-block;
+      font-size: 2.5rem;
+      line-height: 0.6rem;
+      width: 6vw;
+    }
+
+    .csecs {
+        color: #00ffff;
+        width: 95%;
+      margin-bottom: calc(20vh - 1.2rem);
+    }
+    .csecs-bar {
+        height: 0.12rem;
+        background-color: beige;
+        border-radius: 0.1rem;
+    }
+
+    .cidate {
+      color: #aff;
+      font-size: 0.7rem;
+      text-align: center;
+      margin-top: calc(20vh - 0.8rem);
+    }
+  </style>
+</head>
+
+<body>
+<div class="cclock">
+  <div class="ctime">
+    <span id="ahour" class="cdigit" style="text-align: right;">--</span><span id="asepa" class="cdsepa">:</br>&nbsp;</span><span id="aminu" class="cdigit">--</span>
+  </div>
+  <div class="csecs"><div id="asecs" class="csecs-bar"></div></div>
+  <div class="cidate"></div>
+</div>
+
+<script>
+// query parameter: language and font scaling
+var lang='de'
+var ourl = window.location.search.substring(1);
+var aurl = ourl.split('&');
+for (var indx = 0; indx < aurl.length; indx++)
+{ var kval = aurl[indx].split('=');
+  switch(kval[0]) {
+    case 'lang':
+      lang = kval[1].substring(0,2)
+    case 'rsiz':
+      document.querySelector('.croot').style.fontSize = kval[1];
+  }
+}
+delete ourl; delete aurl; delete kval; delete indx
+
+// more global variables
+var htmld = document.firstElementChild;
+htmld.setAttribute('onkeydown', 'keydown(event)');
+htmld.setAttribute('ontouchstart', 'touch(event)');
+
+var vhour = document.getElementById("ahour");
+var vminu = document.getElementById("aminu");
+var vdate = document.getElementById("adate");
+
+// store day and month name in an array
+switch (lang) {
+  case 'de':
+    var dayNames = 'Montag Dienstag Mittwoch Donnerstag Freitag Sonnabend Sonntag';
+    var monthNames = 'Januar Februar März April Mai Juni' +
+                     'Juli August September Oktober November Dezember' ; break;
+  case 'fr':
+    var dayNames = 'Lundi Mardi Mercredi Jeudi Vendredi Samedi Dimanche';
+    var monthNames = 'Janvier Février Mars Avril Mai Juin' +
+                     'Juillet Août Septembre Octobre Novembre Décembre'; break;
+  default:
+    var dayNames = 'Monday Tuesday Wednesday Thursday Friday Saturday Sunday';
+    var monthNames = 'January February March April May June ' +
+                     'July August September October November December';
+}
+dayNames = dayNames.split(' ')
+monthNames = monthNames.split(' ')
+
+// get progress bar element
+var sbar = document.getElementById("asecs");
+var last_minutes
+
+function updateClock() {
+  // Get the current time, day , month and year
+  var now = new Date();
+  var minutes = now.getMinutes();
+  var seconds = now.getSeconds();
+
+  sbar.style.width = (seconds * 100 / 59) + '%';
+  if ( minutes == last_minutes ) return
+  last_minutes = minutes
+
+  var hours = now.getHours();
+  var day = now.getDay();               // BEWARE: 0:=sunday WHY THE HELL!
+  var date = now.getDate();
+  var month = now.getMonth();
+  var year = now.getFullYear();
+
+  // fix the idiotic day-of-week according to ISO standard
+  day = day > 0 ? day - 1 : 6
+
+  // format date and time
+  minutes = minutes < 10 ? '0' + minutes : minutes;
+  seconds = seconds < 10 ? '0' + seconds : seconds;
+
+  // display date and time
+  var line1 = dayNames[day] ; var line2 = monthNames[month]
+  switch (lang) {
+    case 'de': line2 = date + '. '+ line2 + ' ' + year; break;
+    case 'en': line2 = date + ' ' + line2 + ' ' + year; break
+    case 'fr': line1 = line1 + ' ' + date; line2 = line2 + ' ' + year; break;
+    case 'us': hours = hours % 12 || 12;
+               line2 = date + ' ' + line2 + ' ' + year; break;
+    default:  line1 = dayNames[day];
+              month = (month < 9) ? '0' + (month+1) : month + 1;
+              data = (date < 10) ? '0' + date : date;
+              line2 = year + '-' + month + '-' + date;
+  }
+
+  vhour.innerHTML = hours; vminu.innerHTML = minutes;
+  document.querySelector('.cidate').innerHTML = line1 + ' ' + line2;
+}
+
+// keys q/Escape and touch are handled in qml code via console logging
+function keydown(event) {
+  switch(event.key) {
+    case 'q':
+    case 'Escape': console.log("QUIT"); break;
+  }
+}
+function touch(event) {
+  console.log("EXIT") ;
+}
+
+// main script part ...
+updateClock();
+setInterval(updateClock, 1000);
+
+</script></body>
+!EOF
+}
 
 # ------------------------------------------------------------------------------
 # action run: -no args-
@@ -26,7 +248,7 @@ actionRun() {
 
     if [ -z "$CEN_OPT_INVERT" -a -e '/sys/class/backlight/10-0045/brightness' ] ; then
         CEN_OPT_INVERT=1
-        message -a "Assuming input coordinates to be inverted"
+        message -a $"Assuming input coordinates to be inverted"
     fi
 
     [ "$CEN_OPT_INVERT" = 1 ] && sysrun -e xinput set-prop 'Virtual Core Pointer' \
@@ -36,19 +258,74 @@ actionRun() {
         # beware: only system() can be used in a sub-shell
         system -e -x unclutter &
     else
-        warning "Please install 'unclutter' to hide the mouse cursor"
+        warning $"Please install 'unclutter' to hide the mouse cursor"
     fi
 
-    # for clock user only, in background
-    if [ "$USER" = 'clock' ] ; then
+    local stmp surl
+
+    [ -n "$CEN_OPT_HTML" ] && DAT_HTMLTXT="$CEN_OPT_HTML"
+
+    # configuration folder
+    if [ "$CEN_OPT_BASE" = '-' ] ; then
+        eval CEN_OPT_BASE="$DAT_BASEDIR"
+        folder -f -m -c -- "$CEN_OPT_BASE"
+        surl="$DAT_HTMLTXT"
+    else
+       [ -z "$CEN_OPT_BASE" ] && eval CEN_OPT_BASE="$DAT_BASEDIR"
+    fi
+    if folder -q -c -- "$CEN_OPT_BASE" ; then
+        surl="$DAT_HTMLTXT"
+    else
+        warning "Missing configuration:" "$CEN_OPT_BASE"
+        surl=
+    fi
+    if [ -z "$surl" ] ; then
+        if [ "${DAT_HTMLTXT::1}" = '/' ] ; then
+            surl="$DAT_HTMLTXT"
+        else
+            tmpfile -f -b - -n -s stmp ; surl="${stmp%/*}/${DAT_HTMLTXT##*/}"
+        fi
+    fi
+    # TODO update using --force
+    create_html "$surl"
+
+    # run startup tool
+
+    [ -n "$CEN_OPT_EXEC" ] && DAT_STARTUP="$CEN_OPT_EXEC"
+
+     # without --exec the startup tool is optional
+    if PATH=".:$PATH" system -c "$DAT_STARTUP" ; then
+        trace -a -c "Run startup tool" "$DAT_STARTUP"
+    elif [ -z "$CEN_OPT_EXEC" ] ; then      # no startup skript ...
+        DAT_STARTUP='false'
+        trace -a "No startup tool to be executed"
+    fi
+
+    # this can intentionally be fatal if --exec=<tool> is invalid
+    if [ "$DAT_STARTUP" != 'false' ] ; then
+        sysrun -g 1 -f -p -- "$DAT_STARTUP" || quit -- $"Stopped by startup tool"
+    fi
+
+    local args=( '-A' "lang=${CEN_OPT_LANG:-$DAT_LANGGUI}"
+                 '-A' "rsiz=${CEN_OPT_SCALE:-$DAT_SIZEPNT}"
+                 'viewer' "$surl"
+               )
+
+    # start timer, run in background, no cleanups
+    if [ "$CEN_OPT_TIMER" = 1 ] ; then
         sysrun -q systemd-run --user --on-calendar='*-*-* *:00:20' "$CEN_NAME" timer &
+        disown $!                                       # avoid hanging on startup
         DAT_DPMS_OFF='dpms off --' ; actionTimer &
         quit -h                                         # must run quit hooks ...
-        embed -x -v -z centaurilauncher --gui=1 clock
+        embed -x -v -z centaurilauncher --terminal "${args[@]}"
     fi
 
     # ... other user (no background, no timer)
-    embed -v -z centaurilauncher --terminal clock
+    embed -v -z centaurilauncher --terminal "${args[@]}"
+    if [ "$DAT_STARTUP" != 'false' ] ; then
+        message "Terminating workers ..."
+        sysrun -e -p -- pkill -s0 -A        # ouch...
+    fi
 }
 
 # ------------------------------------------------------------------------------
@@ -63,18 +340,30 @@ actionTimer() {
     printf -v hour "%(%H)T" -1 ; [ "$hour" != 0 ] && hour="${hour#0}"
     printf -v zone "%(%Z)T" -1
     [ "$zone" = 'CEST' ] || ((hour += 1))
-    message "Brightness timer:" "$zone ${hour}h -> ${bval[hour]}"
+    trace $"Brightness timer:" "$zone ${hour}h -> ${bval[hour]}"
     embed -v -z centauripower --force $DAT_DPMS_OFF brightness "${bval[hour]}"
 }
 
 # ------------------------------------------------------------------------------
-# implement option parsing: <option> [<argument>]
+# option parsing: <option> [<argument>]
 # ------------------------------------------------------------------------------
 options() {
     case "$1" in
 
+    -B|--bas|--base)
+        optarg 'base'           -    -t ;;          # text
+    -E|--exe*)
+        optarg 'exec'           -    -t ;;          # text
+    -H|--htm|--html)
+        optarg 'html'           -    -t ;;          # text
     -I|--inv*)
         optarg 'invert'         -    -o ;;          # on|off|auto
+    -L|--lan*)
+        optarg 'lang'           -    -t ;;          # text
+    -S|--sca*)
+        optarg 'scale'          -    -t ;;          # text
+    -T|--tim*)
+        optarg 'timer'          -    -o ;;          # on|off|auto
 
     esac
 }
@@ -88,6 +377,9 @@ actions() {
         invoke 'run'    -           0   ;;      # no args
     tim*)
         invoke 'timer'  -           0   ;;      # no args
+
+# TODO 'run start|status|stop'  or a systemd --user service?
+
     esac
 }
 
@@ -96,14 +388,52 @@ actions() {
 # ------------------------------------------------------------------------------
 usage() {
     usageset \
+        -h '' \
+        -h $"The clock can work stand-alone, using internal HTML-code. For display" \
+        -h $"it runs \"centaurilauncher\" and to adjust display brightness following" \
+        -h $"the day-time it uses \"centauripower\" via systemd timer." \
+        -h '' \
+        -h $"Optionally or if run as an appliance (see \"centauristartup\") a config" \
+        -h $"folder can be used to provide different HTML-code or to run a tool at" \
+        -h $"startup, example: display additional weather information." \
+
+    usageset \
         -o - \
-        -o '-I --invert  <mode>' $"invert input coordinates (on|off|auto)" \
+        -o '-B --base    <fldr>' $"Set configuration folder (default: $DAT_BASEDIR)" \
+        -o '-E --exec    <tool>' $"Optional startup tool    (default: $DAT_STARTUP)" \
+        -o '-H --html    <html>' $"Override configured HTML (default: $DAT_HTMLTXT)" \
+        -o '-I --invert  <mode>' $"Invert mouse/touch input coordinates" \
+        -o '-L --lang    <code>' $"Override language to use (default: $DAT_LANGGUI)" \
+        -o '-S --scale   <pnts>' $"Font and layout scaling  (default: $DAT_SIZEPNT)" \
+        -o '-T --timer   <mode>' $"Use of a systemd-timer to control brightness" \
+
+    usageset \
+        -p '<code>'              $"Supported are: \"de\" \"en\" \"fr\" (24h) and \"us\" (12h)" \
+        -p '<fldr>'              $"Path of configuration and data folder" \
+        -p '<html>'              $"Path to the HTML file that gets shown" \
+        -p '<mode>'              $"Use one of: on|1  off|0  auto (default)" \
+        -p '<pnts>'              $"Font size used as reference for scaling" \
+        -p '<tool>'              $"Tool/script executed at startup, \"-\" to ignore" \
 
     usageset \
         -a 'run'                 $"start clock (implied for '.centauristartup' symlink)" \
-        -a 'timer'               $"called by brightness timer" \
+        -a 'timer'               $"used by brightness timer to run 'centauripower'" \
+
+    usageset \
+        -t $"Action \"run\" executes <tool> at startup (if existing). This is used to" \
+        -t $"initialize the environment. If <tool> returns an error execution stops." \
+        -t $"" \
+        -t $"A non-existing \"$DAT_BASEDIR\" is ignored, using \"--base=-\"" \
+        -t $"would initialize the folder. Option \"--timer=on\" causes the clock to"\
+        -t $"run in background. In appliance mode \"--base=-\" and \"--timer=on\" are" \
+        -t $"implied." \
 
 }
+
+#   show=$(PATH="$CEN_TOOLS/Display/weewx/weewx2hass:$PATH" type -p weewx2watch)
+#   sysfind weewx2show || return 0
+#   [ -w clock-data.js ] || return 0
+#   weewx2show &
 
 # ------------------------------------------------------------------------------
 # Finally call the library to execute the script
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
@@ -15,7 +15,7 @@ CEN_SVC_SHORT="Interface/Route Configuration"
 ### END INIT INFO
 
 # Import the bash library, set name and version
-PATH+=":/usr/local/bin:${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.44:4' || exit 2
+PATH+=":/usr/local/bin:${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.45:4' || exit 2
 
 # don't run as a service if centauriswitch is active
 inhibit "Inhibited by centauriswitch"
@@ -785,24 +785,6 @@ do_extender() {
         fi
     }
 
-#    ___extender_dhcp() {
-#        # daemon running?
-#        if pidfile -c -s ppid -- "$namd" ; then
-#            case "$mode" in
-#            2)  message -a "dhcp-helper is running (pid=$ppid)" ; return 0 ;;
-#            1)  message -a "dhcp-helper is already running (pid=$ppid)" ; return 0 ;;
-#            esac
-#        fi
-#
-#        case "$mode" in
-#        2)  message -a "dhcp-helper not running" ;;
-#        1)  system -e -p -- dhcp-helper -r "$CEN_ROOT/transient/$namd.pid" \
-#                                        -i "$iout" -b "$iins" || return 1 ;;
-#        *)  pidfile -d -k - -- "$namd"
-#        esac
-#        return 0
-#    }
-
     ___extender_masq() {
         # daemon running?
         if pidfile -c -s ppid -- "$namd" ; then
@@ -819,10 +801,11 @@ do_extender() {
             fi
             nethost -- "$CEN_NET_SERVER_GEN"
             pidfile -n -- "$namd"
-            # using dhcp broadcasts via <itnk>, no-dns ...
+            # using dhcp as generic server via <itnk>, disable dns ...
+                    # could use dns broadcasts if all subnets have the same netmask
+                    # remove _nethost_ip to enable broacasts
             system -e -p -- dnsmasq -C /dev/null --pid-file="$CEN_PIDFILE" \
-                         --port=0 --dhcp-relay="${_netgetip%/*}","$iins" || return 1 ;;
-#                         --dhcp-relay="$_netgetip","$_nethost_ip" || return 1 ;;
+                         --port=0 --dhcp-relay="${_netgetip%/*},$_nethost_ip,$iins" || return 1 ;;
         *)  pidfile -d -k - -- "$namd"
         esac
         return 0
@@ -1216,7 +1199,7 @@ do_open() {
     # set '4addr' mode of wlan client in bridge
     local wdev="${DAT_OPEN_WLAN%% *}" wcfg="${DAT_OPEN_WLAN#* }"
     [ "$wcfg" = "$wdev" ] && wcfg="$CEN_NAME"
-    if [ -z "$wdev" ] ; then
+    if [ "${wdev:-none}" ] ; then
         trace -a "No WLAN configured" ; wdev='none'
     elif ! netiface -k -s wdev -x -- "$wdev" ; then
         warning "Configured WLAN not found:" "$DAT_OPEN_WLAN" ; wdev='none'
@@ -1540,19 +1523,17 @@ do_dial() {
             case "$_args" in
                 gsm*|mod*)
                         _wdev='/dev/gsmmodem'  ; _defs=('gsmmodem' "$CEN_NAME") ;;
-                rout*)  _wdev='/dev/lterouter' ; _defs=('eth2') ;;
-                teth*)  _wdev='/dev/usbrouter' ; _defs=('usb0' - - 1400) ;;
+                rout*)  _wdev='/dev/lterouter' ; _defs=('eth2|eth1') ;;
+                teth*)  _wdev='/dev/usbrouter' ; _defs=('usb0|eth1' - - 1400) ;;
                 wlan)   _wdev="/sys/class/net/${_args[1]:-wlan0}" ; _defs=() ;;
                 none)   ddev= ; return 0 ;;
                 [a-z]*) _wdev="/dev/usbrouter-$_args" ; _defs=('usb0' - - 1400) ;;
                 *)      warning "Unsupported dial configuration:" "$dial" ; continue ;;
             esac
             [ -e "$_wdev" ] || continue                 # must have device
-                                                        # get kernel interface name
-            netiface -k -s ddev -- "${_args[1]:-${_defs[0]}}"
-            if [ -z "$ddev" ] ; then
-                ddev="${_args[1]:-${_defs[0]}}" ; return 5
-            fi
+            splitjoin -d '|' -x ___dial_kiface -- \
+                    "${_args[1]:-${_defs[0]}}"          # kernel iface name from list
+            [ -z "$ddev" ] && break                     # mapping failed or not found
             dcfg[0]="${_args[2]:-${_defs[1]:--}}"       # config or gateway
             dcfg[1]="${_args[3]:-${_defs[2]:--}}"       # host ip
             dcfg[2]="${_args[4]:-${_defs[3]:--}}"       # mtu
@@ -1564,6 +1545,14 @@ do_dial() {
             return 0
         done
         dial= ; ddev= ; return 1
+    }
+
+    ___dial_kiface() {
+        if netiface -k -s ddev -x -- "$1" ; then
+            trace -a -c -p 'dial iface' "'%s' -> '%s' OK" "$1" "$ddev" ; return 1
+        else
+            trace -a -c -p 'dial iface' "'%s' -> '%s' No device" "$1" "${ddev:-<unknown>}" ; return 0
+        fi
     }
 
     # --------------------------------------------------------------------------
@@ -1607,7 +1596,7 @@ do_dial() {
                 ;;
     [a-z]*)     kind="Router" ; ___dial_router ; stat=$?
                 ;;
-    '')         stat=4 ;;
+    '')         stat=4 ;;           # see ___dial_device
     *)          stat=6 ;;
     esac
 
@@ -1959,8 +1948,8 @@ actionIpv6() {
 
     if [ "$mode" = 'chk' ] ; then
         local item know=0               # 0 no change,  1 disable IPv6, 2 IPv6 ok
-        netresolv -r
-        for item in "${_netresolv[@]:1}" ; do
+        netresolv -r 'nameserver'
+        for item in "${_netresolv[@]}" ; do
             $CEN_TRACE2 -a -c "IPv6 dns server" "$item"
             nethost -- "$item" || continue                  # unknown host
             know=1
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurisecrets
@@ -1,6 +1,6 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2007-2024; BSD License"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2007-2025; BSD License"
 CEN_TITLE="Service to find a Domain Server and download Secrets"
 CEN_SVC_SHORT="Get Domain Server and secrets"
 
@@ -17,7 +17,7 @@ CEN_SVC_SHORT="Get Domain Server and secrets"
 
 # Import the bash library, set name and version (--dryrun NOT FULLY IMPLEMENTED)
 PATH+=':/usr/local/bin'
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.59:4' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.60:4' || exit 2
 
 # Extra option data
 CEN_OPT_NOHOOK=                         # see --nohook
@@ -130,19 +130,19 @@ do_active() {
     # yes, I am a server
     if [ "$svr2" = '--' ] ; then
         [ "$DAT_HOST" != "${DAT_SERVER[0]}" -a "$DAT_HOST" != "${DAT_SERVER[1]}" ] &&
-            error "I am a server - ignoring server argument: $DAT_HOST"
+            error $"I am a server - ignoring server argument:" "$DAT_HOST"
         if [ "${svr1:--}" = '-' ] ; then
-            trace "I am the one and only server - skip check"
+            trace $"I am the one and only server - skip check"
             DAT_HOST="$inam" ; DAT_ACTIVE="$inam" ; return 0
         fi
-        trace "I am a server - checking '$svr1'"
+        trace -p $"I am a server - checking '%s'" "$svr1"
 
     # I am not server. Do we need to check?
     elif [ "$DAT_HOST" = "$DAT_ACTIVE" ] ; then
-        message "Have active server: '$DAT_ACTIVE' - skip check"
+        message -p $"Have active server: '%s' - skip check" "$DAT_ACTIVE"
         return 0
     else
-        trace -i "Configured servers  [${svr1:--none-}${svr2:+ }$svr2]"
+        trace -a $"Configured servers" "[${svr1:-$"--none-"}${svr2:+ }$svr2]"
     fi
     DAT_ACTIVE=                                 # ignore current svr
 
@@ -158,7 +158,7 @@ do_active() {
     local ilst
     matchpath -a ilst -r -- /sys/class/net/e[nt]*/operstate /sys/class/net/wl*/operstate
     if [ -z "$ilst" ] ; then
-        warning "No configured interface"
+        warning $"No configured interface"
         DAT_BLOCKED1="$svr1" ; DAT_BLOCKED2="$svr2" ; DAT_ACTIVE=
         return 1
     fi
@@ -166,25 +166,25 @@ do_active() {
         # do not wait in smart or router mode (these use networkmanage orr dhcp hooks)
         nettemp -s 'centauriswitch'
         if ! [ "$DAT_SWITCH_MODE" = 'smart' -o  "$DAT_SWITCH_MODE" = 'router' ] ; then
-            message "No interface is up - waiting..."
+            message $"No interface is up - waiting..."
             timer -w 3 ; ___ifwait "${ilst[@]}" && break
             timer -w 3 ; ___ifwait "${ilst[@]}" && break
             timer -w 4 ; ___ifwait "${ilst[@]}" && break
         fi
-        message "No interface is up"
+        message $"No interface is up"
         DAT_BLOCKED1="$svr1" ; DAT_BLOCKED2="$svr2" ; DAT_ACTIVE=
         return 1
     done
 
     # get primary/secondary check commands
-    local pri1 pri2="false"                     # for server 1/2
-    local sec1 sec2="false"                     # alternate check
-    if [ -n "$DAT_PORT_POLL" -a "$CEN_OPT_POLL" != "ping" ] ; then
+    local pri1 pri2='false'                     # for server 1/2
+    local sec1 sec2='false'                     # alternate check
+    if [ -n "$DAT_PORT_POLL" -a "$CEN_OPT_POLL" != 'ping' ] ; then
 
         # i am server - check 2nd server only for running ldap
         if [ "$svr2" = '--' ] ; then
             type -t -f netcat >/dev/null 2>&1 ||
-                fatal "Required 'netcat' is no installed"
+                fatal $"Tool 'netcat' is required but not installed"
             pri1="netcat -z -w3 $svr1 $DAT_PORT_POLL"
 
         # check both servers, prefer netcat
@@ -602,32 +602,33 @@ do_passwords() {
 # Download secrets: -no args-       # wants a qualified host name in DAT_HOST
 # ------------------------------------------------------------------------------
 do_secrets() {
+    local __secrets_prompt                      # used in ___secrets()
 
     # helper to load data and to sleep
     __secrets() {
         if [ "$1" != '-' ] ; then
-            message -i "Retry secrets load from: $DAT_HOST"
+            message -i $"Retry secrets load from:" "$DAT_HOST"
             progress '.' ; sleep 2
         fi
 
-        dryrun "echo $HOSTNAME $DAT_COOKIE $DAT_MACHINE_ID |"\
+        dryrun "echo $__secrets_prompt |"\
                "netcat -q6 -w5 -v $DAT_HOST $CEN_NET_PORT_SECR" && return
-        echo -e "$HOSTNAME $DAT_COOKIE $DAT_MACHINE_ID" |
+        echo -e "$__secrets_prompt" |
             netcat -q6 -w5 -v $DAT_HOST $CEN_NET_PORT_SECR 2>/dev/null |
             tar --directory "$DAT_DIR_DOWNLOAD" -xz --numeric-owner . 2>/dev/null
     }
 
     # check call
     if is_static ; then
-        trace "Secrets folder is static, do not download"
+        trace $"Secrets folder is static, do not download"
         [ -n "$DAT_ACTIVE" ] ; return           # return status
     fi
-    [ -z "$DAT_HOST" ] && fatal "No host name"
+    [ -z "$DAT_HOST" ] && fatal $"Host name missing"
     if [ "$DAT_HOST" = "$DAT_BLOCKED1" -o "$DAT_HOST" = "$DAT_BLOCKED2" ] ; then
-        warning "No secrets for '$DAT_HOST', failed server check"
+        warning -p $"No secrets for '%s', failed server check" "$DAT_HOST"
         return 1
     elif [ "$DAT_HOST" = "$HOSTNAME" -o "$DAT_HOST" = "$HOSTNAME.$CEN_NET_DOMAIN" ] ;then
-        trace "Secrets from 'localhost', reinit to defaults"
+        trace $"Secrets from 'localhost', reinit to defaults"
         do_dirinit ; do_default ; return 0
     fi
 
@@ -637,13 +638,17 @@ do_secrets() {
     local isok=1 stat="$DAT_DIR_DOWNLOAD/.status"
     if [ -z "$CEN_OPT_FORCE" ] && readline -i "$stat" ; then
         if [ "$CEN_READLINE" = "$DAT_HOST" ] ; then
-            message -i "Secrets are current:" "$DAT_HOST"
-            CEN_OPT_NOHOOK=1; return 0              # do not run centauriswitch
+            message -i $"Secrets are current:" "$DAT_HOST"
+            CEN_OPT_NOHOOK=1; return 0          # do not run centauriswitch
         fi
-        trace "Secrets not current:" "$CEN_READLINE"
+        trace -a $"Secrets not current:" "$CEN_READLINE"
     fi
     do_dirinit
-    trace "Loading secrets from:" "$DAT_HOST"
+
+    sysversion -u                               # best efford, ignore errors
+    __secrets_prompt="$HOSTNAME $DAT_COOKIE $DAT_MACHINE_ID $CEN_SYS_NICKNAME"
+    trace -a -c $"Loading secrets" "$DAT_HOST ($CEN_SYS_NICKNAME)"
+
     if [ "${DAT_ACTIVE:--}" = '-' ] ; then
         __secrets - || __secrets || __secrets || __secrets || __secrets || __secrets || isok=
     else
@@ -652,14 +657,14 @@ do_secrets() {
 
     # report success or failure
     if [ -n "$isok" ] ; then
-        message -i "Loaded secrets from:" "$DAT_HOST"
+        message -a $"Loaded secrets from:" "$DAT_HOST ($CEN_SYS_NICKNAME)"
         [ -s "$DAT_DIR_DOWNLOAD/rsync_public" ] ||
-            warning -i "Server granted limited access only"
+            warning -a $"Server granted limited access only"
         do_dirinit -u               # update links
         create -t -v DAT_HOST -- "$stat"
         return 0
     fi
-    error "Failed to load secrets from:" "$DAT_HOST"
+    error $"Failed to load secrets from:" "$DAT_HOST"
     remove -- "$stat"
     return 1
 }
@@ -981,55 +986,62 @@ actionSecrets() {
 # ------------------------------------------------------------------------------
 actionServer() {
     CEN_OPT_SYSLOG=2 ; JOURNAL_STREAM=          # do not garble tar stream
-    local host cookie guid
-    read host cookie guid
+
+    # the client sends a cookie and 3 parameters
+    local host cookie guid dist
+    read host cookie guid dist
     if [ "$cookie" != "$DAT_COOKIE" ] ; then
-        error "Client '${host:-<empty>}' with invalid cookie, got: ${cookie:-<empty>}"
+        error -p $"Client '%s' with invalid cookie, got:" \
+                "${host:-$"<empty>"}" "${cookie:-$"<empty>"}"
         return
     fi
 
+    if [ -z "$dist" ] ; then
+        sysversion -u                           # best efford, ignore errors
+        dist="$CEN_SYS_NICKNAME"
+    fi
+    local smid sdir sadd mdir="$DAT_MACHINE_DIR/$dist/$host"
+
     # we have a machine dir (server-side staging repositories)
     if [ -d "$DAT_MACHINE_DIR" ] ; then
-
-        local smid sdir sadd mdir="$DAT_MACHINE_DIR/$host"
+        # pre-triexie fallback
+        [ -d "$mdir" ] || mdir="$DAT_MACHINE_DIR/$host"
         if [ -r "$mdir/machine-id" ] ; then
             smid=$(<"$mdir/machine-id")
             if [ "$smid" != "$guid" ] ; then
-                error "Host sent bad secret:" "$host"
+                error $"Host sent bad secret:" "$host"
                 mdir="$DAT_MACHINE_DIR/@other"
             fi
         else
-            mdir="$DAT_MACHINE_DIR/@other"
-            [ -d "$mdir" ] || folder -f -m "$mdir" 770 "root:wheel"
-            warning "Host is not registered:" "$host"
+            mdir="$DAT_MACHINE_DIR/$dist/@other"
+            [ -d "$mdir" ] || folder -f -m "$mdir" 770 'root:wheel'
+            warning $"Host is not registered:" "$host ($dist)"
         fi
         folder -c -f "$mdir"
 
-        [ -f 'krb5.keytab' ] && sadd="--add-file=./krb5.keytab "
-        [ -f 'repository.conf' ] && sadd+="--add-file=./repository.conf "
+        [ -f 'krb5.keytab' ] && sadd='--add-file=./krb5.keytab '
+        [ -f 'repository.conf' ] && sadd+='--add-file=./repository.conf '
 
     # no machine dir (are we a guest server?)
-    else
-        local mdir sdir
-        [ ! -d "$DAT_DIR_STATIC" ] &&
-            invoke -e "Not a server and missing '%s' folder" "$DAT_DIR_STATIC"
+    elif [ ! -d "$DAT_DIR_STATIC" ] ; then
+        invoke -e $"Not a server and missing '%s' folder" "$DAT_DIR_STATIC"
     fi
 
     # create fake folder if needed
     if [ -d "$DAT_DIR_STATIC" -a "$mdir" != "$DAT_MACHINE_DIR/@other" ] ; then
         sdir="$DAT_DIR_STATIC"
     else
-        warning "No server data, using fake"
+        warning $"No server data, using fake"
         sdir="$DAT_DIR_FAKE" ; folder -f -m "$sdir"
         if ! matchpath -e -o -- "$sdir"/* ; then
-            message "Populating fake data"
+            message -a $"Populating fake data"
             do_default -f
         fi
     fi
     [ '/root/.ssh/id_rsa.pub' -nt "$sdir/ssh_server_key.pub" ] &&
         copy -u '/root/.ssh/id_rsa.pub' "$sdir/ssh_server_key.pub"
-    tar -cz $sadd --directory="$sdir" .
-    message "Sent secret data to: $host"
+    system -e -- tar -cz $sadd --directory="$sdir" .
+    message -a $"Sent secret data to:" "$host ($dist)"
 }
 
 # -----------------------------------------------------------------------------
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauritime b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauritime
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauritime
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauritime
@@ -1,11 +1,11 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2012-2024; BSD License"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2012-2025; BSD License"
 CEN_TITLE=$"Date/Time operations on files and folders"
 # ------------------------------------------------------------------------------
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -g -i -m tra -s -t -y - '0.48:2' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -g -i -m tra -s -t -y - '0.49:4' || exit 2
 
 # Data
 CEN_OPT_CHANGE=         # see --change
@@ -826,14 +826,14 @@ actionCheck() {
     if [ -r "$mark" ] ; then
         read rsum rxxx < "$mark"
         if [ "$rsum" = "${msum%% *}" ] ; then
-            [ -z "$CEN_OPT_SILENT" ] && message -a "Found no changes: $path"
-            [ -n "${CEN_CMDARGS[CEN_CMDINDX]}" ] && trace -a "Additional commands skipped"
+            [ -z "$CEN_OPT_SILENT" ] && message -a -c $"Found no changes" "$path"
+            [ -n "${CEN_CMDARGS[CEN_CMDINDX]}" ] && trace -a $"Additional commands skipped"
             error -s 1 ; quit
         fi
     fi
-    message -a "Data has changed: $path"
-    echo 2>/dev/null "${msum%% *} $path" >"$mark" || error "Cannot write: $mark"
-    error -t && trace -a "Updated status: $mark"
+    message -a -c $"Data has changed" "$path"
+    echo 2>/dev/null "${msum%% *} $path" >"$mark" || error $"Cannot write:" "$mark"
+    error -t && trace -a -c $"Updated status" "$mark"
 }
 
 # ------------------------------------------------------------------------------
