API 5 almost all files uploaded

diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_svc b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_svc
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_svc
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_svc
@@ -116,10 +116,10 @@
 #.          myservice setup status
 #.          myservice setup uninstall
 #
-# Copyright Dr. J. Pfennig (c) 2015-2024
+# Copyright Dr. J. Pfennig (c) 2015-2025
 # ------------------------------------------------------------------------------
 
-CEN_MODULES['_centauri_bash_svc']='0.37:4'
+CEN_MODULES['_centauri_bash_svc']='0.38:4'
 
 CEN_IS_SERVICE=                 # used by _cen_svc_action (internal)
 
@@ -330,23 +330,25 @@ inhibit() {
 # ------------------------------------------------------------------------------
 # pidfile - create/delete PID file, check status, terminate process
 #
-# Call:     (1) pidfile -w <pid>|- [--] [[<path>/]<name>]
-#           (2) pidfile [-c|-d|-n] [-s vnam] [--] [[<path>/]<name>]
-#           (3) pidfile [-d] -k <signal> [-s vpid] [--] [[<path>/]<name>]
+# Call:     (1) pidfile [-f <file>] -w <pid>|- [--] [[<path>/]<prog>]
+#           (2) pidfile [-f <file>] [-c|-d|-n] [-s vnam] [--] [[<path>/]<prog>]
+#           (3) pidfile [-f <file>] [-d] -k <signal>|- [--] [[<path>/]<prog>]
 #
 #+          Form (1) creates a pid file, form (2) returns pid file information or
 #           deletes a pid file. A signal can be sent to a process using form (3).
 #
 # Options:  -c  check if saved PID is still running
 #           -d  delete the PID file
+#           -f  PID file path to be used
 #           -k  send a signal to the saved PID
 #           -n  get PID file name and return
 #           -r  use extension .run instead of .pid
 #           -s  save the PID (empty string on error)
 #           -w  create a PID file
 #
-# Arguments:<name>    PID file name (default is $CEN_NAME)
-#           <path>    path starting with "/", enables validation
+# Arguments:<file>    overrides the automatically generated PID file path
+#           <prog>    executable file name (default is $CEN_NAME)
+#           <path>    executable path (absolute path enables validation)
 #           <pid>     PID of main process or "0" for oneshot
 #           <signal>  signal name/number to be sent (default is SIGTERM)
 #           <vnam>    variable name
@@ -360,31 +362,40 @@ inhibit() {
 #
 #+This function implements the standard PID file actions and is used to
 # implement service state handling. The function itself does not register
-# any hook to catch signals or to remove the pidfile.
+# any hook to catch signals or to remove the PID file.
 #
 #+Using a full path as program name argument enables a validation against the
 # process name to prevent killing a process using a stale pid file. The code
 # checks if "/proc/<pid>/exe" is the same file as the given path. For bash all
 # paths will match.
+#
+#.Examples: system -f -p -- some_tool &
+#.          pidfile -w $? -- some_tool      # create some_tool.pid file
+#.          ...
+#.          pidfile -d -k HUP -- some_tool  # send signal, delete pid file
+#
+#.          system -f -p -- other_tool --pidfile /tmp/pid-file
+#.          ...
+#.          pidfile -d -f /tmp/pid-file -k  # send SIGTERM, delete pid file
 # ------------------------------------------------------------------------------
 CEN_PIDFILE=
 pidfile() {
     CEN_PIDFILE=
-    local _flgd _flgs _flgw _fsav _fext=".pid"
+    local _file _flgd _flgs _flgw _fsav _fext='.pid'
     while [ "${1::1}" = '-' ] ; do
       case "$1" in
       --)   shift ; break ;;
       -c)   ;;
       -d)   _flgd=1 ;;
+      -f)   shift ; _file="$1" ;;
       -k)   shift ; _flgs="${1:--}" ;;
       -n)   _flgw='-' ;;
-      -r)   _fext=".run" ;;
-      -s)   shift ; _fsav="${1:--}" ; printf -v "$_fsav" '0' ;;
-### TODO -u for user/private pid
+      -r)   _fext='.run' ;;
+      -s)   shift ; _fsav="${1:--}" ; printf -v "$_fsav" 0 ;;
       -w)   shift ; _flgw="${1:--}" ; [ "$_flgw" = '-' ] && _flgw=$$ ;;
 
       # internal use: <pid> <program> <pidfile>
-      -v)   shift ; [ "${2::1}" = "/" ] || return 0     # no check
+      -v)   shift ; [ "${2::1}" = '/' ] || return 0     # no check
             [ "${1:-0}" = 0 ] && return 0               # nothing to check
             [ "/proc/$1/exe" -ef "$2" ] && return 0     # success
             [ "/proc/$1/exe" -ef "$BASH" ] && return 0
@@ -395,10 +406,13 @@ pidfile() {
       esac ; shift
     done
 
-    local _name="${1:-$CEN_NAME}" _file="$CEN_ROOT/transient" _temp
-    [ -w "$_file" ] || _file="/run"
-    [ -w "$_file" ] || _file="${TMPDIR:-$TMP}"
-    _file+="/${_name##*/}$_fext"
+    local _name="${1:-$CEN_NAME}" _kpid
+    if [ "${_file:--}" = '-' ] ; then
+        _file="$CEN_ROOT/transient"
+        [ -w "$_file" ] || _file='/run'
+        [ -w "$_file" ] || _file="${TMPDIR:-$TMP}"
+        _file+="/${_name##*/}$_fext"
+    fi
 
     if [ -n "$_flgw" ] ; then                           # write pid file...
         if [ "$_flgw" != '-' ] ; then
@@ -411,29 +425,29 @@ pidfile() {
         $CEN_TRACE "pidfile: no file:" "$_file"
         return 1
     elif [ -z "$_flgd" -o -n "$_flgs" ] ; then            # read PID file
-        if ! read _temp 2>/dev/null <"$_file" ; then
+        if ! read _kpid 2>/dev/null <"$_file" ; then
             $CEN_TRACE "pidfile: cannot read:" "$_file"
             return 1
         fi
-        [ "$_fsav" ] && printf -v "$_fsav" '%s' "$_temp"
+        [ "$_fsav" ] && printf -v "$_fsav" '%s' "$_kpid"
     fi
 
     if [ -n "$_flgd" -o -n "$_flgs" ] ; then
-        pidfile -v "$_temp" "$_name" "$_file" || return 3   # wrong process
+        pidfile -v "$_kpid" "$_name" "$_file" || return 3   # wrong process
         [ -n "$_flgd" ] && remove -r -- "$_file"
-        [ "${_temp:-0}" = 0 ] && return 0               # nothing to kill
-        [ "${_flgs:--}" = '-' ] && _flgs="SIGTERM"
-        $CEN_TRACE "pidfile: send signal:" "$_flgs $_temp"
+        [ "${_kpid:-0}" = 0 ] && return 0               # nothing to kill
+        [ "${_flgs:--}" = '-' ] && _flgs='SIGTERM'
+        $CEN_TRACE "pidfile: send signal:" "$_flgs $_kpid"
         [ -z "${_flgs//[0-9]/}" ] && _flgs="-n $_flgs" || _flgs="-s $_flgs"
-        kill $_flgs $_temp 2>/dev/null ; return        # return status
+        kill $_flgs $_kpid 2>/dev/null ; return         # return status
     fi
 
-    [ -z "$_temp" ] && return 1                         # no PID file
-    if [ "$_temp" != 0 ] ; then
-        if ! kill -0 "$_temp" 2>/dev/null ; then        # PID not valid
+    [ -z "$_kpid" ] && return 1                         # no PID file
+    if [ "$_kpid" != 0 ] ; then
+        if ! kill -0 "$_kpid" 2>/dev/null ; then        # PID not valid
             remove -r -- "$_file" ; return 2            # delete stale pid file
         fi
-        pidfile -v "$_temp" "$_name" "$_file" || return 3   # wrong process
+        pidfile -v "$_kpid" "$_name" "$_file" || return 3   # wrong process
     fi
     CEN_PIDFILE="$_file"; return 0                      # return ok
 }
@@ -731,6 +745,8 @@ runsysddir() {
 #           runservice [-u] [-e|-f] [-v] **sytemd** <name>...   # systemd services
 #           runservice [-u] [-e|-f] [-v] **masked** <name>...   # masked services
 #
+#           runservice **level** [<lmin>]                       # get/check runlevel
+#
 # Options:  -d  run as a daemon, needs no root priviledge or service install
 #           -e  report errors
 #           -f  make errors fatal
@@ -742,6 +758,7 @@ runsysddir() {
 #
 # Arguments:<verb>  **start**|**stop**|**reload**|**restart**
 #           <name>  A service, target or unit name (**NOT** a path)
+#           <lmin>  Check for a minimum runlevel
 #
 #+Return:   The **status** command returns **true** if the service is active. On
 #           error a status bit mask is returned, see below.
@@ -753,6 +770,10 @@ runsysddir() {
 #           masked. On error a status bit mask is returned, see below. The **systemd**
 #           and **masked** commands behave like **test** but check for a systemd unit
 #           or a systemd masked symlink instead.
+#
+#+          **runlevel** saves the current level into RUN_SERVICE. The implementation
+#           uses 'systemd is-active runlevelN.target'. It returns **true** if <lmin> is
+#           less or equal the current level (<lmin> defaults to 1).
 #
 #+          All other verbs return **true** on success or a status bit mask otherwise,
 #           see below.
@@ -820,14 +841,23 @@ runservice() {
 
     # check verb
     case "$_scmd" in
-    start|stop|restart|reload|status|enabled)  ;;
-    systemd|masked) [ "$_oerr" = 'trace' ] && _oerr=':'
-                    _ssys=1 ;;                      # systemd only
-    test)           [ "$_oerr" = 'trace' ] && _oerr=':' ;;
-    *)
-        [ $# = 0 ] || _cen_abort - "$_scmd"
-        # single argument: assume "test"
-        set -- "$_scmd" ; _scmd='test'
+    start|stop|restart|reload|status|enabled)
+            ;;
+    systemd|masked)
+            [ "$_oerr" = 'trace' ] && _oerr=':'
+            _ssys=1                                     # systemd only
+            ;;
+    test)   [ "$_oerr" = 'trace' ] && _oerr=':'
+            ;;
+    level)  for CEN_RUNSERVICE in 5 4 3 2 1 0 ; do
+                [ "$CEN_RUNSERVICE" = 0 ] && return 1
+                sysrun -q -r systemctl is-active "runlevel$CEN_RUNSERVICE.target" && break
+            done
+            [ "${1:-1}" -le "$CEN_RUNSERVICE" ] ; return  # return status
+            ;;
+    *)      [ $# = 0 ] || _cen_abort - "$_scmd"
+            # single argument: assume "test"
+            set -- "$_scmd" ; _scmd='test'
     esac
 
     # test if services exist and are not masked
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricron b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricron
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricron
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauricron
@@ -1,13 +1,13 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
 CEN_TITLE="Tool to run Centauri Cron Jobs"
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2013-2024; BSD License"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2013-2025; BSD License"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -s - '0.34:4' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -s - '0.35:4' || exit 2
 
 # Data
-DAT_LOGDIR="/var/log"
+DAT_LOGDIR='/var/log'
 DAT_MIDNIGHT=
 DAT_TRIM_FLAG=
 DAT_UNMOUNT_FLAG=
@@ -17,6 +17,7 @@ DAT_OFS_OUTPUT=0                        # initial file size
 DAT_QUIT_LIST=                          # for exit_hook
 DAT_KEEP_PIDFILE=                       # don't delete pidfile
 DAT_ROLE=                               # from CEN_NET_ROLE
+DAT_RUNLEVEL=                           # see runlevel_check
 
 # data for extra options
 CEN_OPT_APPEND=                         # see --append
@@ -37,19 +38,19 @@ export PATH="$CEN_TOOLS:$PATH"
 default_hourly() {
     ### update private repositories
     [ -e "$CEN_ROOT/machines/rsyncd.conf" ] &&
-        execute -s 3 centaurimachines -U -s
+        execute -r 4 -s 3 centaurimachines -U -s
 
     if [ "$DAT_ROLE" != 'UNKNOWN' ] ; then
 
         ### process mail send queue
-        execute -s 2 centaurimail --silent queue
+        execute -r 4 -s 2 centaurimail --silent queue
     fi
 
     ### update network folder
-    execute -s 2 centauridata update
+    execute -r 4 -s 2 centauridata update
 
     ### umount stale encfs
-    execute -s 2 centauriencfs cleanup
+    execute -r 4 -s 2 centauriencfs cleanup
 
     ### umount autofs volumes and spindown disks
     DAT_UNMOUNT_FLAG=1
@@ -80,13 +81,13 @@ default_daily() {
         header "Update Mail and Repository"
 
         ### run a cyrus db check
-        execute -s 5 centaurimail --silent backup
+        execute -r 4 -s 5 centaurimail --silent backup
 
         ### process mail send queue
-        execute -s 5 centaurimail --silent queue
+        execute -r 4 -s 5 centaurimail --silent queue
 
         ### fetch mail, prune delivery
-        execute -s 5 centaurimail --zombie --silent fetch -- prune -- index
+        execute -r 4 -s 5 centaurimail --zombie --silent fetch -- prune -- index
 
         ### synchronize config files
         execute -s 5 centauriconfig cron
@@ -114,7 +115,7 @@ default_weekly() {
     execute -s 5 centauridata week
 
     ### run short or long selftests
-    execute -s 6 centaurismart -s test run
+    execute -r 4 -s 6 centaurismart -s test run
 
     # repeat some daily actions ...
 
@@ -137,7 +138,7 @@ default_monthly() {
     execute -s 5 centauridata month
 
     ### set flag for long selftests
-    execute -s 6 centaurismart -s test long
+    execute -r 4 -s 6 centaurismart -s test long
 
     # repeat some daily actions ...
 
@@ -198,24 +199,32 @@ nodefault() {
 }
 
 header() {
-    [ "$CEN_ACTION" = "hourly" ] && return
-    [ -z "$CEN_AUTOIND" ] && message -i " "
+    [ "$CEN_ACTION" = 'hourly' ] && return
+    #[ -z "$CEN_AUTOIND" ] &&
+    message -i ' '
     message -- "=== $* (status $CEN_EXIT) ==="
-    message -a " " ; CEN_AUTOIND=
+    message -i ; CEN_AUTOIND=
 }
 
-# find a script and run: [-c|-s <status>] <name> <arg>...
+# find a script and run: [-c|-s <status>] [-o] [-r <minl>] <name> <arg>...
 execute() {
-    local stat=9 sbak="$CEN_EXIT" path fopt
-    while [ "${1::1}" = "-" ] ; do
+    local stat=9 sbak="$CEN_EXIT" path fopt minl
+    while [ "${1::1}" = '-' ] ; do
         case "$1" in
         --)   shift ; break ;;
         -c)   stat='-' ;;                           # ignore error
         -o)   fopt=1 ;;
+        -r)   shift ; minl="$1" ;;
         -s)   shift ; stat="$1" ;;                  # status to set on error
         *)    _cen_abort - "$1"
         esac ; shift
     done
+
+    # check minimum runlevel
+    if [ "${minl:--}" != '-' ] && ! runlevel_check "$minl" ; then
+        trace -c "Runlevel to low" "$*"
+        return 1
+    fi
 
     # use the PATH variable to locate a centauri script for embedding
     if sysfind -s path -p "$CEN_TOOLS:$CEN_TOOLS/utilities" -- "$1" ; then
@@ -232,7 +241,7 @@ execute() {
     [ -z "$stat" ] && return 0
     if [ "$stat" = '-' ] ; then                     # reset error
         CEN_EXIT="$sbak"
-        [ "$CEN_EXIT" = "0" ] && error -c
+        [ "$CEN_EXIT" = 0 ] && error -c
     else
         status "$stat" "$path"
     fi
@@ -257,7 +266,7 @@ status() {
 # ------------------------------------------------------------------------------
 logger_mesg() {
     local fqui fsta mesg faci="cron.info"
-    while [ "${1::1}" = "-" ] ; do
+    while [ "${1::1}" = '-' ] ; do
       case "$1" in
       --)   shift ; break ;;
       -q)   fqui=1 ;;
@@ -333,7 +342,7 @@ list_function() {
     }
 
     # used recursively for user and default function
-    if [ "$1" != "-" ] ; then
+    if [ "$1" != '-' ] ; then
         [ -n "$2" ] && message "The user hook implementation is:"
         local line sifs="$IFS" ; IFS=$'\n'
         while read line ; do
@@ -345,9 +354,17 @@ $(___list "$1")
     fi
 
     # default function
-    [ "${2:--}" = "-" ] && return
+    [ "${2:--}" = '-' ] && return
     message "The default implementation is:"
     list_function "$2"
+}
+
+# check for a minimum runlevel: <minl>
+runlevel_check() {
+    if [ -z "$DAT_RUNLEVEL" ] ; then
+        runservice level ; DAT_RUNLEVEL="$CEN_RUNSERVICE"
+    fi
+    [ "$1" -le "$DAT_RUNLEVEL" ]                # return status
 }
 
 # ------------------------------------------------------------------------------
@@ -444,7 +461,7 @@ trimssd() {
         trace -a "Mounted: $irun -> $CEN_MOUNT_DEV ($idev)"
 
         [ -r "/sys/block/$idev/queue/rotational" ] || continue
-        [ "$(</sys/block/$idev/queue/rotational)" = "0" ] || continue
+        [ "$(</sys/block/$idev/queue/rotational)" = 0 ] || continue
         ((icnt += 1)) ; ivol+=("$irun")
     done
 
@@ -577,13 +594,13 @@ options() {
         trace -a -c "network role" "$DAT_ROLE" ;;
 
     -A|--app*)
-        optarg "append"     CEN_OPT_APPEND ;;               # a simple flag
+        optarg 'append'     -                 ;;            # a simple flag
     -C|--con*)
-        optarg "config"     CEN_OPT_CONFIG -t ;;            # any text
+        optarg 'config'     -              -t ;;            # any text
     -L|--log*)
-        optarg "logmax"     CEN_OPT_LOGMAX -n ;;            # a number
+        optarg 'logmax'     -              -n ;;            # a number
     -O|--out*)
-        optarg "output"     CEN_OPT_OUTPUT -t ;;            # any text
+        optarg 'output'     -              -t ;;            # any text
 
     esac
 }
@@ -595,7 +612,7 @@ actions() {
     case "$CEN_ACTION" in
 
     # before 1st action ...
-    "") context -r
+    '') context -r
         [ -r "$CEN_OPT_CONFIG" ] || fatal "Cannot read: $CEN_OPT_CONFIG"
         . "$CEN_OPT_CONFIG" || fatal "Failed to load: $CEN_OPT_CONFIG"
         DAT_QUIT_LIST="$CEN_HOOK_QUIT" ; CEN_HOOK_QUIT=exit_hook
@@ -610,7 +627,7 @@ actions() {
         CEN_OPT_SYSLOG=0                        # disable auto syslog output
 
         # where to write
-        if [ "$CEN_OPT_OUTPUT" = "-"  -o -n "$CEN_OPT_DRYRUN" ] ; then
+        if [ "$CEN_OPT_OUTPUT" = '-'  -o -n "$CEN_OPT_DRYRUN" ] ; then
             CEN_OPT_OUTPUT=
         elif [ -z "$CEN_OPT_OUTPUT" ] ; then
             system -f -p -s CEN_OPT_OUTPUT -- mktemp --tmpdir "${CEN_NAME}_XXXXXX"
@@ -622,27 +639,27 @@ actions() {
         fi ;;
 
     hou*)
-        invoke "hourly"    actionCron 0 ;;      # no args
+        invoke 'hourly'    actionCron 0 ;;      # no args
     da[iy]*)
-        invoke "daily"     actionCron 0 ;;      # no args
+        invoke 'daily'     actionCron 0 ;;      # no args
     wee*)
-        invoke "weekly"    actionCron 0 ;;      # no args
+        invoke 'weekly'    actionCron 0 ;;      # no args
     mon*)
-        invoke "monthly"   actionCron 0 ;;      # no args
+        invoke 'monthly'   actionCron 0 ;;      # no args
 
     boo*|reb*)
-        invoke "boot"      actionCron 0 ;;      # no args
+        invoke 'boot'      actionCron 0 ;;      # no args
     mid*)
-        invoke "midnight"  actionCron 0 ;;      # no args
+        invoke 'midnight'  actionCron 0 ;;      # no args
     shu*)
-        invoke "shutdown"  -        0 1 ;;      # optional arg
+        invoke 'shutdown'  -        0 1 ;;      # optional arg
     wai*)
-        invoke "wait"      -        0 1 ;;
+        invoke 'wait'      -        0 1 ;;
 
     spi*)
-        invoke "spindown"  spindown   0 ;;      # DEBUG
+        invoke 'spindown'  spindown   0 ;;      # DEBUG
     tri*)
-        invoke "trimssd"   trimssd    0 ;;      # DEBUG
+        invoke 'trimssd'   trimssd    0 ;;      # DEBUG
     esac
 }
 
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
@@ -1,6 +1,6 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2015-2024; BSD License"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2015-2025; BSD License"
 CEN_TITLE="Interface/Route Configuration Tool and Service"
 CEN_SVC_SHORT="Interface/Route Configuration"
 
@@ -703,18 +703,18 @@ do_homedns() {
     splitkeyval "$DAT_OPEN_HOME" okey oval '@'
     if [ "$okey" = 'local' ] ; then             # use generic address
         if [ "${#CEN_NET_ADDR_IPLIST[@]}" -lt 2 ] ; then
-            [ "$1" = 'add' ] && warning "No generic 'home' address"
+            [ "$1" = 'add' ] && warning "No generic 'homedns' address"
             return
         fi
         _nethost_ip="$CEN_NET_ADDR_IPLIST"
         _nethost_name="$HOSTNAME"
     elif ! nethost "$okey" ; then      # valid address?
-        [ "$1" = 'add' ] && warning "Unknown 'home' host:" "$okey"
+        [ "$1" = 'add' ] && warning "Unknown 'homedns' host:" "$okey"
         return
     fi
     [ -n "$oval" ] || oval="$2"
     if [ "${oval:--}" = '-' ] ; then
-        error "Missing 'home' interface" ; return
+        warning "Unknown 'homedns' interface" ; return
     fi
     trace -p "%s 'home' address: %s@%s" "${1^}" "$_nethost_name" "$oval"
     do_address "$1" "$_nethost_name" "$_nethost_ip" "$_nethost_mac" "$oval"
@@ -1174,7 +1174,7 @@ do_open() {
     local ibri="${DAT_OPEN_BRIDGE:-none}" ilis=(${DAT_OPEN_BRIDGE[@]:1})
     local iprx=("${DAT_OPEN_PROXY[@]}") ; [ -z "$iprx" ] && iprx=('none')
     [ "$ibri" = 'none' ] && ilis=('none')
-    message -a -p "Opening %s mode: bridge='%s'  switch='%s'" "$DAT_SWITCH_MODE" "${ilis[*]}" "${iprx[*]}"
+    message -a -p "Opening %s mode: bridge='%s'  switch='%s'" "$DAT_SWITCH_MODE" "$ibri" "${iprx[*]}"
     if [ "$DAT_SWITCH_MODE" = 'router' ] ; then
         netoption 'dns'  || error "Mode 'router' depends on 'option dns'"
         netoption 'dhcp' || error "Mode 'router' depends on 'option dhcp'"
@@ -1188,23 +1188,27 @@ do_open() {
 
     # bring down/up the bridge
     if [ "$ibri" != 'none' ] ; then
-        trace -a -c "Init bridge" "$ibri"
-        nettool -d "$ibri" down
-        if ! nettool -d "$ibri" -q up ; then
-            error "Failed to bring up '$ibri', ignore bridge"
-            ibri='none'
-        else
-            # get active interfaces, bring them down (to allow add to bridge)
-            for ifce in "${ilis[@]}" ; do
-                nettool -d "$ifce" exists || continue
-                iuse+=("$ifce")
-                nettool -q -d "$ifce" down
-            done
-            message -i -c "Active interfaces" "${iuse[*]}"
+        #if ! nettool -d "$ibri" exists ; then
+        #    error "Bridge iface '$ibri' not found, ignore bridge"
+        #    ibri='none'
+        #else
+            trace -a -c "Init bridge" "$ibri"
+            nettool -d "$ibri" down
+            if ! nettool -d "$ibri" -q up ; then
+                error "Failed to bring up '$ibri', ignore bridge"
+                ibri='none'
+            fi
+        #fi
+        # get active interfaces, bring them down (to allow add to bridge)
+        for ifce in "${ilis[@]}" ; do
+            nettool -d "$ifce" exists || continue
+            iuse+=("$ifce")
+            [ "$ibri" != 'none' ] && nettool -q -d "$ifce" down
+        done
+        message -i -c "Active ifaces" "${iuse[*]}"
 
-            [ -n "$CEN_NET_EXTERNAL" ] &&
-                netoption 'other' "$HOSTNAME" && do_external "$HOSTNAME" "$ibri"
-        fi
+        [ -n "$CEN_NET_EXTERNAL" -a "$ibri" != 'none' ] &&
+            netoption 'other' "$HOSTNAME" && do_external "$HOSTNAME" "$ibri"
     fi
     DAT_ROUTE_OPEN="$DAT_SWITCH_MODE"
     do_status -w
@@ -1222,7 +1226,7 @@ do_open() {
     if [ "$ibri" = 'none' ] ; then
         if [ "$DAT_SWITCH_MODE" = 'switch' -o "$DAT_SWITCH_MODE" = 'router' ] ; then
             trace -a "Bridge disabled by configuration"
-            do_homedns add                          # add an extra homedns address
+            do_homedns add "$iuse"              # add an extra homedns address
         fi
     else
         for ifce in "${iuse[@]}" ; do
@@ -1423,6 +1427,7 @@ do_dial() {
         timer -w 1                      # extra time to get ready
     }
 
+    # broken code, retained for fiber modem via ppp
     ___dial_gsm() {
         message -a "Dialing '$dcfg' interface: $DAT_OPEN_PPP"
 
@@ -1462,7 +1467,7 @@ do_dial() {
 
         if [ "${dcfg[0]}" = '-' ] ; then
             if ! ___dial_droute "$ddev" dcfg[0] ; then
-                dial='-no gateway-' ; return 5
+                dial='-no gateway-' ; return 6
             fi
             message -a "Found gateway:" "${dcfg[0]} ($ddev)"
         fi
@@ -1632,10 +1637,8 @@ do_hangup() {
     local devb="$DAT_OPEN_BRIDGE"
     local ddev="${DAT_ROUTE_DIAL%% *}"
 
-    if [ "${ddev::3}" = 'eth' -o "${ddev::3}" = 'usb' ] ; then
-        message -a "Bring down interface: $ddev"
-        [ "${ddev::3}" = 'usb' ] && embed -v centauriswitch dhcp down "$ddev"
-    else
+    case "$ddev" in
+    gsm*|ppp*)                                  # broken code, retained for fiber modem
         if [ -e "${DAT_PID}wvdial" ] ; then
             message -a "Stopping wvdial"
             sysrun -e -p pkill -x wvdial
@@ -1645,8 +1648,12 @@ do_hangup() {
             [ -r "${DAT_PID}wpasuppl" ] && sysrun -e -p kill $(<"${DAT_PID}wpasuppl")
             [ -r "${DAT_PID}dhclient" ] && sysrun -e -p dhclient -pf "${DAT_PID}dhclient" -x
         fi
-        remove -- "${DAT_PID}"*
-    fi
+        remove -- "${DAT_PID}"* ;;
+    *)
+        message -a "Bring down interface:" "$ddev"
+        #[ "${ddev::3}" = 'usb' ] &&
+        embed -v centauriswitch dhcp down "$ddev"
+    esac
 
     netiface -e -k "$ddev" && nettool -d "$_netiface" down
 
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurivbox b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurivbox
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurivbox
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurivbox
@@ -1,10 +1,10 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2007-2024; BSD License"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2007-2025; BSD License"
 CEN_TITLE="Run VirtualBox commands using the 'vbox' proxy user"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -g -y - '0.43:4' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -g -y - '0.44:4' || exit 2
 
 # Data
 
@@ -38,6 +38,8 @@ do_drive() {
     *)      matchpath -s _disk -e -o -- "${DAT_CONFIG%/*}/$2.vdi" "$DAT_DRIVES/$2.vdi"
     esac
     printf -v "$1" "$_disk"
+    [ -n "$_disk" ] && return 0
+    error "Disk image not found:" "$2" ; return 1
 }
 
 # ------------------------------------------------------------------------------
@@ -222,24 +224,44 @@ actionAttach() {
     execute -m -v -- "$1" || return                 # check machine
 
     local disk size used
-    case "$2" in
-    -)      disk='none' ;;
-    */*)    disk="$2" ;;
-    *.*)    matchpath -s disk -e -o -- "${DAT_CONFIG%/*}/$2" "$DAT_DRIVES/$2" ;;
-    +)      inpfile -s disk -l -x 'vdi' + ;;
-    *)      matchpath -s disk -e -o -- "${DAT_CONFIG%/*}/$2.vdi" "$DAT_DRIVES/$2.vdi"
-    esac
+    do_drive disk "$2" || return
+#do_driveinfo "$disk" used size ; quit xxx $? $size ${used[*]%% *}
 
     local ferr='-e'
     local opts=(--storagectl SATA --type hdd --medium "$disk" --port "${3:-0}")
     if [ "$disk" = 'none' ] ; then
         ferr='-q'
     else
-#do_driveinfo "$disk" used size ; quit xxx $? $size ${used[*]%% *}
-#        system -q -z VBoxManage showmediuminfo disk "$disk"
         opts+=(--nonrotational on --discard on)
     fi
     system $ferr VBoxManage storageattach "$DAT_NAME" "${opts[@]}"
+}
+
+# ------------------------------------------------------------------------------
+# run shell or command as user 'vbox': [<cmd> ...]
+# ------------------------------------------------------------------------------
+actionCmd() {
+    if [ "$USER" = 'vbox' ] ; then
+        if [ $# = 0 ] ; then
+            invoke -w $"Not lauching a shell for user 'vbox'"
+        else
+            system -e -- "$@"
+        fi
+    else
+        execute -v
+    fi
+}
+
+# ------------------------------------------------------------------------------
+# compact - discard empty blocks: <driv>
+# ------------------------------------------------------------------------------
+actionCompact() {
+    [ "$1" = '-' ] && return
+    execute -v || return
+    local disk
+    do_drive disk "$1" || return
+    message "Compacting drive:" "$disk"
+    system -e -z vboxmanage modifymedium --compact "$disk"
 }
 
 # ------------------------------------------------------------------------------
@@ -257,21 +279,6 @@ actionDrive() {
         system -e VBoxManage closemedium disk "$CEN_OUTFILE" --delete
     else
         system -e VBoxManage createmedium disk --filename="$CEN_OUTFILE" --size="$2"
-    fi
-}
-
-# ------------------------------------------------------------------------------
-# run shell or command as user 'vbox': [<cmd> ...]
-# ------------------------------------------------------------------------------
-actionCmd() {
-    if [ "$USER" = 'vbox' ] ; then
-        if [ $# = 0 ] ; then
-            invoke -w $"Not lauching a shell for user 'vbox'"
-        else
-            system -e -- "$@"
-        fi
-    else
-        execute -v
     fi
 }
 
@@ -297,6 +304,11 @@ actionExport() {
 # ------------------------------------------------------------------------------
 actionGui() {
     execute -k -v || return
+    embed -b /etc/centauridisplay
+    # embed -e centauridisplay --run qt5 VirtualBox
+    #   qt5
+    #   qt6
+    #   x11
     system -e -- VirtualBox
 }
 
@@ -410,14 +422,18 @@ actionMount() {
     matchpath -a list -e -- "$base"/vol? || return
     if [ $# = 0 ] ; then
         case "${#list[*]}" in
-        4)  set -- + - - / ;;
-        3)  set -- + - / ;;
-        2)  set -- + / ;;
+        4)  set -- + - - / ;;       # has bios partition
+        3)  set -- + - / ;;         # boot and root
+        2)  set -- + - ;;           # root and swap
+        1)  set -- + ;;             # root only
+        *)  error -p "Found %s partitions, need explicit specifications" "${#list[*]}"
+            return ;;
         esac
     fi
     for part in "${list[@]}" ; do
         item="${base}_${part##*/}"
-        mopt=('-l')
+        # with readonly mount option -l does not work
+        mopt=('-l') ; [ -z "$fwri" ] && mopt+=('-r')
         case "${1:-+}" in
         +)  ;;
         -)  message -a -p "Skipping '%s'" "$item" ; shift ; continue ;;
@@ -593,10 +609,11 @@ execute() {
     # re-run via sudo
     if [ -n "$ousr" -a "$USER" != 'vbox' ] ; then
         message -a -d +3 $"Run as user 'vbox' ..."
+        local opts=(-u vbox --preserve-env=PULSE_SERVER,QT_SCALE_FACTOR,GDK_DPI_SCALE,GDK_SCALE)
         if [ "$CEN_ACTION" = 'cmd' ] ; then
-            system -e sudo -i -u vbox -H PULSE_SERVER=localhost
+            system -e sudo -i "${opts[@]}"
         else
-            local opts=(-u vbox -H PULSE_SERVER=localhost "$CEN_NAME" '--local')
+            opts+=(-H "$CEN_NAME" '--local')
             do_opts opts
             system -e -r -x sudo "${opts[@]}" "${CEN_CMDARGS[@]:CEN_CMDCURR}"
         fi
@@ -652,6 +669,8 @@ actions() {
         invoke    'batch'  actionStart 0 1 ;;
     cmd)
         invoke -c -        -               ;;
+    com*)
+        invoke    'compact' -            1 ;;
     cre*)
         invoke    'create' actionDrive   2 ;;
     del*)
@@ -706,6 +725,7 @@ actions:
                             attach a disk, use '-' to detach
        batch   [<name>]     start a virtual machine without gui
        cmd                  open a shell for user 'vbox'
+       compact <name>       discard empty blocks from disk image
        create  <disk> [<size>]
                             create a disk image (size in MByte)
        delete  <disk>       delete a disk image
@@ -729,9 +749,9 @@ arguments:
        <disk>               name of a registered vbox disk image
        <mdir>               mount directory (default is $HOME/Mount)
        <part>               partition selector (- skip, + mount, /... subvol)
-       <port>               x
-       <size>               x
-       <snam>               x
+       <port>               disk controller port 0,1,...
+       <size>               disk image size in MByte
+       <snap>               snapshot name
 !EOF
 }
 
