push development repo to github, api 6

diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_iom b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_iom
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_iom
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_iom
@@ -57,7 +57,7 @@
 # Copyright Dr. J. Pfennig (c) 2019-2025
 # ------------------------------------------------------------------------------
 
-CEN_MODULES['_centauri_bash_iom']='0.06:4'
+CEN_MODULES['_centauri_bash_iom']='0.07:4'
 
 CEN_IOM_QUEUE=()        # see _cen_optarg_iom()
 
@@ -804,7 +804,7 @@ _cen_cache_chk() {
 #           -w  generate warning message  (from <reader> callback only)
 #
 # Arguments:<name>    name or path of the configuration file to be parsed
-#           <init>    callback to catch missing file
+#           <init>    callback to catch missing file, use "+" to ignore
 #           <reader>  data callback
 #           <sect>    section filter. Section is a line containing the name of
 #                     the section enclosed in [] braces. Example: **[hello]**.
@@ -956,11 +956,11 @@ configfile() {
     # check list of filters
     _cen_configfile_fltr() {
         [ "${#_sect[@]}" = 0 ] && return 1
-        _line="${_line%% *}"
-        [ "${_line//[[:alnum:]_-]/}" = '[]' ] || return 1
-        local _item _snam="${_line:1:-1}"
+        local _item="${_line%% *}"
+        [ "${_item//[[:alnum:]_-]/}" = '[]' ] || return 1
+        local _snam="${_item:1:-1}"
         for _item in "${_sect[@]}" ; do
-            [ "$_snam" = "$_item" -o "$_item" = "*" ] || continue
+            [ "$_snam" = "$_item" -o "$_item" = '*' ] || continue
             CEN_CONFIGFILE[3]="$_snam" ; _skip=
             [ -z "$_omul" ] ; return                        # return status
         done
@@ -1008,11 +1008,13 @@ configfile() {
 
     # callback <init>
     _cen_configfile_init() {
-        if [ -z "$_init" ] ; then
+        if [ "${_init:--}" = '-' ] ; then
             $_orep $"Configuration file not found:" "$_file"
             return 1
+        elif [ "$_init" = '+' ] ; then
+            return 0
         fi
-        isfunction -a -x -c $_init "$_file"     # call and return status
+        isfunction -a -x -c "$_init" "$_file"   # call and return status
     }
 
     # do we have a config name or file path?
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_rep b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_rep
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_rep
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_rep
@@ -1,79 +1,202 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-# _centauri_bash_rep = centauri-bash-lib: Repository basic operations
+# _centauri_bash_rep = centauri-bash-lib: Monitoring, Overrides and Repository
 #
-# Call:     . _centauri_bash_rep
+# Call:     . _centauri_bash_rep [-m]
 #
-# The module implements exactly two public functions:
+# Options:  -m      execute "monitor init"
+#
+# The module implements exactly three public functions:
+#
+#,  [[monitor()]]       'tool start' monitoring
 #,  [[override()]]
 #,  [[repository()]]
 #
 # Copyright Dr. J. Pfennig (c) 2024-2025
 # ------------------------------------------------------------------------------
 
-CEN_MODULES['_centauri_bash_rep']='0.02:4'
+CEN_MODULES['_centauri_bash_rep']='0.03:6'
 
 embed -c '_centauri_bash_ext'               # dependency
 
 CEN_REP_DKEY=                               # distribution key, see 'distro'
 
+CEN_REP_HOOK_MAIN=
+CEN_REP_HOOK_QUIT=
+CEN_REP_HOOK_OPTIONS=
+CEN_REP_HOOK_ACTIONS=
+
+# ------------------------------------------------------------------------------
+# monitor - init 'tool start' monitoring and default logger implementation
+#
+# Call:     monitor <kind> <text>...
+#
+# Arguments:<kind>      kind of hook: init|main|args|opts|quit|exit
+#           <text>      text to be logged
+#
+# Variables:CEN_HOOK_MONITOR    hook used to log something
+#           CEN_MONITOR_CALL    call-back to override log implementation
+#           CEN_MONITOR_FILE    enable only if this is a writable file
+#           CEN_MONITOR_MASK    enable bit mask 1:main 2:acts 4:args 8:quit
+#
+#
+#+Proxy:    The library proxy can be used to configure system wide logging
+#           by adding two lines of code, see "/etc/default/centauri_bash_lib":
+#
+#.          [proxy]
+#.          °   # non-comment lines get copied verbatim into the proxy
+#.          °   CEN_MONITOR_FILE=/var/centauri/persistent/centauri-monitor
+#.          °   [ -w "$CEN_MONITOR_FILE" ] && CEN_MONITOR_MASK=1
+#
+#+Tools:    The systemd service script of [[centaurisysinit]] truncates the
+# log file at early boot time.
+#
+#+          Use [[centauriinfo]] to display log data with optional filtering and
+# high-lighting.
+#
+#+The write access permission controls which user's 'tool starts' get logged.
+#
+#+The main library module loads this module with option -m to initialize the
+# monitor if CEN_MONITOR_MASK is set. The default implementation just writes
+# the argumnents to CEN_MONITOR_FILE:
+#
+# °     <epochseconds> <ppid> <pid> <user> <text>...
+#
+#+The predefined <kind> values are implemented by the library itself. Additional
+# log entries can be generated calling monitor() directly of via CEN_HOOK_MONITOR.
+#
+#+After initialization CEN_MONITOR_MASK can be modified to select <kind> or to
+# suspend monitoring.
+# ------------------------------------------------------------------------------
+monitor() {
+    # initialization: for security resons hook only a funtion ...
+    if [ "$CEN_HOOK_MONITOR" = ':' ] ; then
+        if [ -n "$CEN_MONITOR_CALL" ] ; then
+            is_function -f "$CEN_MONITOR_CALL" && CEN_HOOK_MONITOR="$CEN_MONITOR_CALL"
+        else
+            CEN_HOOK_MONITOR='cen_monitor_call'
+        fi
+        [ -z "$CEN_MONITOR_FILE" ] && CEN_MONITOR_FILE="$CEN_PERSISTENT/monitor"
+        if ! [ -w  "$CEN_MONITOR_FILE" ] ; then
+            warning -c $" disabled" "Cannot write:" "$CEN_MONITOR_FILE"
+            CEN_MONITOR_MASK= ; return 1
+        fi
+
+        if ((CEN_MONITOR_MASK & 1)) ; then
+            eval 'cen_monitor_main() { $CEN_HOOK_MONITOR main "$@" ; shift ; $CEN_REP_HOOK_MAIN "$@" ; }'
+            context -h CEN_HOOK_MAIN CEN_REP_HOOK_MAIN  'cen_monitor_main'
+        fi
+        if ((CEN_MONITOR_MASK & 2)) ; then
+            eval 'cen_monitor_acts() { $CEN_HOOK_MONITOR acts "$@" ; shift ; $CEN_REP_HOOK_ACTIONS "$@" ; }'
+            context -h CEN_HOOK_ACTIONS CEN_REP_HOOK_ACTIONS 'cen_monitor_acts'
+        fi
+        if ((CEN_MONITOR_MASK & 4)) ; then
+            eval 'cen_monitor_opts() { $CEN_HOOK_MONITOR opts "$@" ; shift ; $CEN_REP_HOOK_OPTIONS "$@" ; }'
+            context -h CEN_HOOK_OPTIONS CEN_REP_HOOK_OPTIONS 'cen_monitor_opts'
+        fi
+        if ((CEN_MONITOR_MASK & 8)) ; then
+            eval 'cen_monitor_quit() { $CEN_HOOK_MONITOR quit "$@" ; shift ; $CEN_REP_HOOK_QUIT "$@" ; }'
+            context -h CEN_HOOK_QUIT CEN_REP_HOOK_QUIT 'cen_monitor_quit'
+        fi
+    elif [ "${CEN_HOOK_MONITOR:--}" = '-' ] ; then
+        return 1
+    fi
+    $CEN_HOOK_MONITOR "$@"
+}
+
+cen_monitor_call() {
+    # default implementation
+    [ -z "$CEN_MONITOR_MASK" ] && return 1
+    local name="${USER:-${LOGNAME:-$EUID}}"
+    [ "$name" = 0 ] && name='root'
+    echo "$EPOCHSECONDS" "$PPID" "$$" "${name:--}" "$CEN_NAME" "${@@Q}" >> "$CEN_MONITOR_FILE"
+    return 0
+
+}
+
 # ------------------------------------------------------------------------------
 # override - mechanism to pass extra information to scripts
 #
-# Call:     (1) override -c <name>|- <value>
-#           (2) override -d <name>|-
-#           (3) override -r [-f] <name>|- <vnam>
+# Call:     (1) override [-b <base>] [-f] -c <name>|-|-- <word>...
+#           (2) override [-b <base>]      -d <glob>|-|--
+#           (3) override [-b <base>]      -l <glob>|-|-- <vnam>
+#           (4) override [-b <base>] [-f] -r <name>|-|-- <varr>
+#           (5) override [-b <base>]      -p <name>|-|-- [<vnam>]
 #
-#+      Form (1) creates a file named "$CEN_ROOT/persistent/<name>-override" with
-# <value> as contents.
+#-      Form (1) creates a file named "$CEN_PERSISTENT/<name>-override" with
+#-      °        <value> as content -or- "<base>/<name>-override".
+#-      Form (2) delete one or more files created by (1).
+#-      Form (3) returns a list of matching ''override'' names (**not file paths**).
+#-      Form (4) is used to read the content of an ''override'' file into variable
+#-      °        <vnam>.
+#-      Form (5) return the file path and **TRUE** if existing or **FALSE** if not.
 #
-#+      Form (2) deletes a file created by (1).
-#
-#+      Form (3) is used to read the content of an ''override'' file into variable
-#       <vnam>.
-#
-# Options:  -c  create file
-#           -d  delete file
+# Options:  -b  base (optional prefix for path)
+#           -c  create an override file
+#           -d  delete override files by name (glob expression match)
 #           -f  make errors fatal
+#           -l  get list of override names (glob expression match)
+#           -p  return a path, check if existing
 #           -r  read file
 #
-# Arguments:<name>      file name part (use '-' for script name)
-#           <value>     string to be written (must be a single line)
+# Arguments:<base>      path that overrides $CEN_PERSISTENT
+#           <glob>      bash glob expression
+#           <name>      file name part (use '-' for script name)
+#           <varr>      name of an array that returns names (**not file paths**)
 #           <vnam>      name of a variable that returns the file content
+#           <word>      string to be written (joined to a single line)
 #
 #+Form (2) and (3) do nothing if no ''override'' file exists. Only read or write
 # errors get reported.
+#
+#.Examples: override -c -- hello world
+#.          override -p && message "have override"
+#.          override -r -- data && message "data: $data"
+#
+#.          override -c 'other' -- 'hi!'
+#.          override -p 'other' path && message "see: $path"
+#.          override -d 'other'
+#
+#.          override -l 'test*' list
+#.          override -d 'test*'
 # ------------------------------------------------------------------------------
 override() {
-    local _name="$CEN_NAME" _file _fcre _fdel _frea
+    local _name="$CEN_NAME" _base="$CEN_PERSISTENT" _fopt _ferr='-e'
     while [ "${1::1}" = '-' ] ; do
       case "$1" in
-      -)    break ;;
       --)   shift ; break ;;
-      -c)   _fcre=1 ;;
-      -d)   _fdel=1 ;;
-      -f)   [ -n "$CEN_OPT_FORCE" ] && return 1
-            _frea=1 ;;
-      -r)   _frea=1 ;;
+      -b)   shift ; _base="${1%/}" ;;
+      -f)   _ferr="$1" ;;
+      -[cdlpr])
+            _fopt="$1" ; shift
+            [ -z "$1" -o "${1::1}" = '-' ] || _name="$1" ;;
       *)    _cen_abort - "$1"
-      esac ; shift
+      esac
+      [ "$1" = '--' ] && { shift ; break ; }
+      shift
     done
-    [ "${1:--}" != '-' ] && _name="$1" ; shift
-    _file="$CEN_ROOT/persistent/$_name-override"
-    if [ -n "$_fcre" ] ; then
-        writeline -c - -e -o "$_file" -t -- "$1" ; return
-    elif [ -n "$_fdel" ] ; then
-        remove -- "$_file" ; return
-    elif [ -n "$_frea" ] ; then
-        readline -i "$_file" -s "$1" ; return
-    fi
-    _cen_abort =
+
+    _file="$_base/${_name//[[:space:]]/}-override"
+    case "$_fopt" in
+    -c) writeline $_ferr -c - -o "$_file" -t -- "$*" ;;
+    -d) remove -- "$_base/"${_name//[[:space:]]/}'-override' ;;
+    -l) local _list
+        local -n _cen_override_var="$1" ; _cen_override_var=()
+        matchpath -e -a _list -- "$_base/"${_name//[[:space:]]/}'-override'
+        for _name in "${_list[@]##*/}" ; do
+            _cen_override_var+=("${_name%-override}")
+        done ;;
+    -p) [ -n "$1" ] && printf -v "$1" '%s' "$_file"
+        [ -f "$_file" ] ;;
+    -r) readline $_ferr -i "$_file" -s "$1" ;;
+    esac
+    return                                          # return status
 }
 
 # ------------------------------------------------------------------------------
 # Override Arguments + Passing extra information to Scripts
 #
-#+General:  This mechanism manages files in "$CEN_ROOT/persistent" using file
+#+General:  This mechanism manages files in "$CEN_PERSISTENT" using file
 # names built like: "<script-name>-override". The target script can implement
 # whatever it wants to handle information read from such a file. Typically a
 # script will capture a set of action verbs and replace matching verbs by data
@@ -95,14 +218,14 @@ override() {
 #
 #.  PATH+=":${0%/*}" . _centauri_bash_lib -a -d -o - '0.01' || exit 2
 #.
-#.  CEN_DEF_BASE="/opt/$CEN_NAME"           # default for option --base
+#.  DAT_DEF_BASE="/opt/$CEN_NAME"           # default for option --base
 #.  CEN_OPT_BASE=                           # option argument value
 #.
 #.  # ...
 #.
 #.  options() {
 #.  case "$1" in
-#.  °   '')     [ -z "$CEN_OPT_BASE" ] && CEN_OPT_BASE="$CEN_DEF_BASE"
+#.  °   '')     [ -z "$CEN_OPT_BASE" ] && CEN_OPT_BASE="$DAT_DEF_BASE"
 #.  °           ;;
 #.  °   -B|--bas|--base)
 #.  °           optarg 'base'   -   -t
@@ -118,7 +241,7 @@ override() {
 # "/etc/default/mytool" could be:
 #
 #. # overriding the default for option --base
-#. CEN_DEF_BASE='/somewhere/$CEN_NAME"
+#. DAT_DEF_BASE='/somewhere/$CEN_NAME"
 # ------------------------------------------------------------------------------
 
 # ------------------------------------------------------------------------------
@@ -393,9 +516,10 @@ _cen_repo_loc() {
 }
 
 # ------------------------------------------------------------------------------
-# Startup: [-n]
+# Startup: [-m]
 # ------------------------------------------------------------------------------
 
+[ "$1" = '-m' ] && monitor init
 :                                           # return true to indicate success
 
 # end
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimounter b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimounter
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimounter
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurimounter
@@ -1,10 +1,10 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Dr. Jürgen Pfennig (c) 2020-2024 ; all rights reserved"
+CEN_LEGAL="Dr. Jürgen Pfennig (c) 2020-2025 ; all rights reserved"
 CEN_TITLE="Automounter tool and service for local and network filesystems"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -v - '0.15:3' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -v - '0.17:6' || exit 2
 
 CEN_SVC_AFTER='networking.service network-online.target remote-fs.target'
 CEN_SVC_WANTS='avahi-daemon.service'    # service dependency
@@ -82,7 +82,7 @@ DAT_STATE=
 # Read config and check if required programs are installed
 # ------------------------------------------------------------------------------
 do_tools() {
-    [ "$DAT_HAVE_CONFIG" = '2' ] && return
+    [ "$DAT_HAVE_CONFIG" = 2 ] && return
     do_config
     DAT_HAVE_CONFIG=2
     do_spindown check
@@ -123,7 +123,7 @@ do_spindown() {
             [ -b "$driv" ] || continue
             idev="${driv##*/}"
             [ -r "/sys/block/$idev/queue/rotational" ] || continue
-            [ "$(</sys/block/$idev/queue/rotational)" = '0' ] && continue
+            [ "$(</sys/block/$idev/queue/rotational)" = 0 ] && continue
             dlst+=("$idev")
             dsta+=("$idev $(</sys/block/$idev/stat)")
         done
@@ -138,7 +138,7 @@ do_spindown() {
         wxxx="${arg1:-20}" ; dlst=()
         while [ "$wxxx" -gt 0 ] ; do                        # interruptible sleep...
             [ "$CEN_SVC_RUNNING" = 'stopped' ] && return    # service terminated
-            sleep "$DAT_SLEEP_TIME" ; ((wxxx-=DAT_SLEEP_TIME))
+            timer -w "$DAT_SLEEP_TIME" ; ((wxxx-=DAT_SLEEP_TIME))
         done
 
         # check for activity, spin down
@@ -279,7 +279,7 @@ do_config() {
     DAT_HAVE_CONFIG=1
 
     # create import/export folders
-    folder "$CEN_ROOT/persistent" || CEN_FOLDER="/var/lib/$CEN_NAME"
+    folder "$CEN_PERSISTENT" || CEN_FOLDER="/var/lib/$CEN_NAME"
     resolve -c -f "$CEN_FOLDER"                         # systemd uses absolute paths
     DAT_FOLDER_IMPORT="$CEN_RESOLVE/import" ; attributes -d -k -m 775 "$DAT_FOLDER_IMPORT"
     DAT_FOLDER_EXPORT="$CEN_RESOLVE/export" ; attributes -d -k -m 775 "$DAT_FOLDER_EXPORT"
@@ -657,14 +657,14 @@ do_options() {
         MOUNT_NAME=*|MOUNT_POINT=*|MOUNT_BASE=*)
             DAT_OPTMAP["${oopt%%=*}"]="${oopt#*=}" ;;
         FS_TYPE=*|fstype=*)
-            DAT_OPTMAP["FS_TYPE"]="${oopt#*=}" ;;
+            DAT_OPTMAP['FS_TYPE']="${oopt#*=}" ;;
         *)
             DAT_OPTIONS+=",$oopt"
         esac
     done
 
-    [ -z "${DAT_OPTMAP["FS_TYPE"]}" -a -n "${DAT_OPTMAP["type"]}" ] &&
-        DAT_OPTMAP["FS_TYPE"]="${DAT_OPTMAP["type"]}"
+    [ -z "${DAT_OPTMAP['FS_TYPE']}" -a -n "${DAT_OPTMAP['type']}" ] &&
+        DAT_OPTMAP['FS_TYPE']="${DAT_OPTMAP['type']}"
     DAT_OPTIONS="${DAT_OPTIONS:1}"
 }
 
@@ -687,10 +687,10 @@ do_systemd() {
     [ "$1" = "$_verb" ] && _ftyp= ; shift
 
     if [ "$_verb" = 'mount' ] ; then
-        [ -n "${DAT_OPTMAP["IS_STATIC"]}" ] && _cmnt=1
-        [ -n "${DAT_OPTMAP["NO_UNMOUNT"]}" ] && _cmnt=1
+        [ -n "${DAT_OPTMAP['IS_STATIC']}" ] && _cmnt=1
+        [ -n "${DAT_OPTMAP['NO_UNMOUNT']}" ] && _cmnt=1
 #### TODO always check?
-_cmnt=1
+#_cmnt=1
         _mlis+=('--no-ask-password')
         if [ -z "${DAT_OPTMAP['IS_STATIC']}" ] ; then
             _mlis+=('--automount=yes')
@@ -706,8 +706,8 @@ _cmnt=1
         _want=2                                 # wants 2 arguments
 
     elif [ "$_verb" = 'check' ] ; then
-        [ -n "${DAT_OPTMAP["IS_STATIC"]}" ] && return 1
-        [ -n "${DAT_OPTMAP["NO_UNMOUNT"]}" ] && return 1
+        [ -n "${DAT_OPTMAP['IS_STATIC']}" ] && return 1
+        [ -n "${DAT_OPTMAP['NO_UNMOUNT']}" ] && return 1
         return 0
 
     elif [ "$_verb" = 'unmount' ] ; then
@@ -749,7 +749,7 @@ _cmnt=1
         message -a -c "Unmounted" -- "$1"
 
         remove -q -- "$1" && return 0
-        sleep 0.2                               # retry after small delay...
+        timer -w 0.2                                # retry after small delay...
         remove -q -- "$1" && return 0
         message -a -c "rmdir failed" -- "$1"
         return 1
@@ -1296,7 +1296,7 @@ do_poll() {
     local item hcur nbak="${#DAT_POLL_LIST[@]}"
     if [ -z "$host" -o "$nbak" -gt $DAT_POLL_BATCH ] ; then
         [ "$nbak" -gt $DAT_POLL_BATCH ] &&                  # add extra delay
-            [ -n "$DAT_POLL_DELAY" ] && sleep "$DAT_POLL_DELAY"
+            [ -n "$DAT_POLL_DELAY" ] && timer -w "$DAT_POLL_DELAY"
 
         # fetch the poll results
         for item in "${DAT_POLL_LIST[@]}" ; do
@@ -1547,12 +1547,9 @@ run() {
 
     DAT_REMOVE_LIST=()                                      # list of mountpoints
     do_tree                                                 # cleanup tree folder
-if [ "$DAT_STATE" != 'quit' ] ; then
-    do_local -u                                             # local unmount
-fi
+    [ "$DAT_STATE" != 'quit' ] &&  do_local -u              # local unmount
     if [ -n "$DAT_REMOVE_LIST" ] ; then                     # queued removes...
-        sleep 1                                             # wait for unmounts
-       # system -e -p -- sync "${DAT_REMOVE_LIST[@]}"        # io wait
+        timer -w 1                                          # wait for unmounts
         local item ldel=()
         splitjoin -x 'remove -q' -i DAT_REMOVE_LIST         # 1st try, ignore errs
         for item in "${DAT_REMOVE_LIST[@]}" ; do
@@ -1560,7 +1557,7 @@ fi
         done
         if [ -n "$ldel" ] ; then
             message -a -c "Retry remove" -- "${#ldel[@]} item(s)"
-            sleep 1 ; splitjoin -x 'remove' -i ldel         # retry after delay
+            timer -w 1 ; splitjoin -x 'remove' -i ldel      # retry after delay
         fi
     fi
     message "Terminated"
@@ -1653,7 +1650,7 @@ fi
             stat="${DAT_HOSTS["$host"]}"
             [ "$stat" = 'i' ] && continue               # ignore host
             hlow="${host,,}"                            # lower case name
-            if [ "$fnfs" = '1' ] ; then                 # nfs hosts only
+            if [ "$fnfs" = 1 ] ; then                   # nfs hosts only
                 [ "$hlow" = "$host" ] || continue
             else                                        # samba hosts only
                 [ "$hlow" = "$host" ] && continue
@@ -1778,7 +1775,7 @@ actionList() {
 actionNetwork() {
     local narg pipe entr glob item coun=11 plur='s' nmnt
     if ! listsearch -u -m narg -- "$1" 'rescan' 'connect' 'disconnect' 'quit' 'busy'; then
-        error "invalid argument:" "network $1" ; return
+        invoke -e - "$1" ; return
     fi
 
     # busy: show network mounts or wait until all are unmounted (--quiet)
@@ -1800,7 +1797,7 @@ actionNetwork() {
                                                             # option -q does wait
             ((coun--)) || quit -s 2 -l -p "%s export mount%s, quit." "$nmnt" "$plur"
             message -l -a -p "%s export mount%s, wait %s" "$nmnt" "$plur" "$coun"
-            sleep 0.75
+            timer -w 0.75
         done
         quit -s 1
     fi
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripackage b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripackage
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripackage
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauripackage
@@ -5,7 +5,7 @@ CEN_TITLE="Compare package lists, run apt update/install/remove"
 
 # Import the bash library, set name and version
 
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -i -s -t -y - '0.33:4' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -i -s -t -y - '0.35:4' || exit 2
 
 # Data
 
@@ -22,7 +22,8 @@ CEN_OPT_DEVEL=          # see --development option
 CEN_OPT_UPDATE=         # see --update
 CEN_OPT_UPGRADE=        # see --upgrade
 
-CEN_CONFIG_DIR="$CEN_ROOT/shared/.."
+DAT_CONFIG_DIR="$CEN_ROOT/shared/.."
+DAT_DIFF_ARG=           # see check_diff
 DAT_EATMYDATA=          # set by option nosync
                         # dpkg install package status ...
 DAT_STATUS='/var/lib/dpkg/info'
@@ -141,7 +142,7 @@ process_apt() {
         local cols=$((cols - ${#snam} - 2))
 
         ___aptgui_orig() {
-            DEBIAN_FRONTEND='noninteractive' LC_MESSAGES=C DISPLAY= COLUMNS=$cols \
+            DEBIAN_FRONTEND=noninteractive LC_MESSAGES=C DISPLAY= COLUMNS=$cols NO_COLOR=yes \
             system -e "$@" --yes -o Dpkg::Options::='--force-confold' 2>&1 </dev/null ; echo STAT=$?
         }
 
@@ -234,7 +235,7 @@ process_apt() {
         [ -n "$lall" ] && return 0
         local mesg
         printf -v mesg "$1" "$3"
-        confirm -a -c ___aptend -p "[a/y/N/q]? " -v "all yes no quit" "$mesg"
+        confirm -a -c ___aptend -d $"n" -p $"[a/y/N/q]? " -v $"all yes no quit" "$mesg"
         case $? in
         0)  lall=1 ;;
         1)  return 0 ;;
@@ -272,20 +273,19 @@ process_apt() {
     ___aptend                           # apt install|remove
 }
 
-# resolve destination arguments: <arg>
-CEN_DIFF_ARG=
+# resolve destination arguments: <arg> (result in DAT_DIFF_ARG)
 check_diff() {
-    CEN_DIFF_ARG="${1:--}"
-    [ "$CEN_DIFF_ARG" = '-' ] && return
-    if [ "${1::1}" = "@" ] ; then
-        if [ "$1" = "@" ] ; then
-            CEN_DIFF_ARG="$CEN_CONFIG_DIR/@shared/PACKAGES"
+    DAT_DIFF_ARG="${1:--}"
+    [ "$DAT_DIFF_ARG" = '-' ] && return
+    if [ "${1::1}" = '@' ] ; then
+        if [ "$1" = '@' ] ; then
+            DAT_DIFF_ARG="$DAT_CONFIG_DIR/@shared/PACKAGES"
         else
-            CEN_DIFF_ARG="$CEN_CONFIG_DIR/${1:1}/PACKAGES"
+            DAT_DIFF_ARG="$DAT_CONFIG_DIR/${1:1}/PACKAGES"
         fi
     fi
-    prettypath -c -e -f -s CEN_DIFF_ARG -- "$CEN_DIFF_ARG"
-    [ -r "$CEN_DIFF_ARG" ] || fatal $"Cannot read:" "$CEN_DIFF_ARG"
+    prettypath -c -e -f -s DAT_DIFF_ARG -- "$DAT_DIFF_ARG"
+    [ -r "$DAT_DIFF_ARG" ] || fatal $"Cannot read:" "$DAT_DIFF_ARG"
 }
 
 # ------------------------------------------------------------------------------
@@ -341,14 +341,14 @@ run() {
     fi
     arguments 1 2 "$@" || return
     check_diff "$2"
-    local dest="$CEN_DIFF_ARG"
+    local dest="$DAT_DIFF_ARG"
     check_diff "$1"
-    [ "$CEN_DIFF_ARG" = '-' ] && fatal $"1st arg must be <path>, @ or @<host>"
+    [ "$DAT_DIFF_ARG" = '-' ] && fatal $"1st arg must be <path>, @ or @<host>"
     system -f -c diff dpkg apt
 
     # get input data
     local lsrc ldes hinp
-    splitjoin -s lsrc -d '\n' -i - <"$CEN_DIFF_ARG"
+    splitjoin -s lsrc -d '\n' -i - <"$DAT_DIFF_ARG"
     if [ "$dest" = '-' ] ; then
         system -a ldes -d '\n' -e -n -p -r -- dpkg --get-selections
     else
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurirestore
@@ -1,9 +1,9 @@
 #!/usr/bin/bash
 # ------------------------------------------------------------------------------
-CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2017-2024; BSD License"
+CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2017-2025; BSD License"
 CEN_TITLE="Restore a centauribackup, optionally cloning an existing machine"
 
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -m bat -r -y - '0.60:3' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -m bat -r -y - '0.61:4' || exit 2
 
 # Options
 
@@ -114,21 +114,22 @@ do_fixup() {
     CEN_DAT_FIXUP=1
 
     # make /tmp a symlink if missing
-    [ -d "tmp" ] || symlink -m "/dev/shm" "tmp"
+    [ -d 'tmp' ] || symlink -m '/dev/shm' 'tmp'
 
     # in case that udev is not used
-    if [ -d "dev" ] ; then
-        [ -e "dev/console" ] || system -e -p mknod -m 660 "dev/console" c 5 1
-        [ -e "dev/null"    ] || system -e -p mknod -m 660 "dev/null"    c 1 3
+    if [ -d 'dev' ] ; then
+        [ -e 'dev/console' ] || system -e -p mknod -m 660 'dev/console' c 5 1
+        [ -e 'dev/null'    ] || system -e -p mknod -m 660 'dev/null'    c 1 3
     fi
 
-    system -e -p chmod 755 "."
-    system install -d "dev" "proc" "sys" "var/lib/centauri"
+    system -e -p chmod 755 '.'
+    attributes -d -k -m 755 -- 'dev' 'proc' 'sys' 'var' 'var/lib'
+    attributes -d -k -m 755 -o root:wheel -- 'var/lib/centauri'
 
     # fix apt permissions (same code as in centaurisecurity)
-    if [ -d "var/lib/apt" ] ; then
-        attributes -d -m 755 -o root:root -- "var/lib/apt/lists"         "var/cache/apt/archives"
-        attributes -d -m 700 -o _apt:root -- "var/lib/apt/lists/partial" "var/cache/apt/archives/partial"
+    if [ -d 'var/lib/apt' ] ; then
+        attributes -d -m 755 -o root:root -- 'var/lib/apt/lists'         'var/cache/apt/archives'
+        attributes -d -m 700 -o _apt:root -- 'var/lib/apt/lists/partial' 'var/cache/apt/archives/partial'
     fi
 }
 
@@ -136,18 +137,18 @@ do_fixup() {
 # handle formatting and labelling
 # ------------------------------------------------------------------------------
 do_format() {
-    [ -n "$CEN_DAT_LABEL" ] && message -a "Will label root partition as: $CEN_DAT_LABEL"
+    [ -n "$CEN_DAT_LABEL" ] && message -a "Will label root partition as:" "$CEN_DAT_LABEL"
 
     # do we need a mount point?
     if [ -n "$CEN_FLG_MOUNT" ] ; then
         if [  -d "$CEN_FLG_MOUNT" ] ; then
-            message -a "Using moint point: $CEN_FLG_MOUNT"
+            message -a "Using moint point:" "$CEN_FLG_MOUNT"
         else
-            folder -f -m -r -t "_mount" ; CEN_FLG_MOUNT="$CEN_FOLDER"
-            message -a "Created moint point: $CEN_FLG_MOUNT"
+            folder -f -m -r -t '_mount' ; CEN_FLG_MOUNT="$CEN_FOLDER"
+            message -a "Created moint point:" "$CEN_FLG_MOUNT"
         fi
-        [ -d "$CEN_FLG_MOUNT" ] || fatal "Not a directory: $CEN_FLG_MOUNT"
-        [ -w "$CEN_FLG_MOUNT" ] || fatal "Cannot write to: $CEN_FLG_MOUNT"
+        [ -d "$CEN_FLG_MOUNT" ] || fatal "Not a directory:" "$CEN_FLG_MOUNT"
+        [ -w "$CEN_FLG_MOUNT" ] || fatal "Cannot write to:" "$CEN_FLG_MOUNT"
     fi
 
     # --- formatting ---
@@ -161,7 +162,7 @@ do_format() {
            message -a "Creating ext$CEN_FLG_EXTFS filesystem ..."
            confirm -a "Format $CEN_FLG_PART" || quit -t
            mopt="-t ext4"
-           [ "$CEN_FLG_EXTFS" = "3" ] && mopt="-O dir_index"
+           [ "$CEN_FLG_EXTFS" = 3 ] && mopt="-O dir_index"
            system -f -p mke2fs -q -j -m0 $mopt "$CEN_FLG_PART"
         else
            message -a "Creating btrfs filesystem ..."
@@ -314,7 +315,9 @@ do_rename() {
         embed -i -v centaurikeys -y -q hostkeys 'etc/ssh'
 
     # remove persistent device names (legacy)
-    remove -f "etc/udev/rules.d/"*-persistent-*
+    remove -f 'etc/udev/rules.d/'*-persistent-*
+    # remove name override
+    remove -f 'etc/sysctl.d/host+domain.conf'
 
     # clean dhcp and samba caches
     remove -f 'var/lib/dhcp'/*
