API 5 updates

diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/library/_centauri_bash_net
@@ -334,60 +334,98 @@ netgetip() {
 }
 
 # ------------------------------------------------------------------------------
-# nethost - Search a host network configuration entry
+# nethost - Search a host entry in network host configuration table
 #
-# Call:    nethost [-c|-s] [--] <host>|<addr>
+# Call:    nethost [-e|-f] [-c|-n|-s] [--] <host>|<addr>|<mac>|-
 #
 # Options:  -c  do not match a configured server
+#           -e  report errors
+#           -f  make errors fatal
+#           -n  check for name syntax only
 #           -s  only match a configured server
 #
 # Arguments:<host>  a host name (optionally fully qualified)
 #           <addr>  an IPv4 address like **10.21.2.11**
+#           <mac>   a mac address
+#
+#           All input must be in lowercase
 #
 # Variables:**_nethost_name**   array of host names/aliases
+#           **_nethost_dom**    domain name stripped from <host> arugment
 #           **_nethost_mac**    the mac address    (or '-' if unknown)
 #           **_nethost_ip**     the ipv4 address   (or '-' if unknown)
 #
 # Return:  **true** if <host> was found or **false** on failure
 #
-#+         The **_nethost_mac** **_nethost_ip** and **_nethost_name** variables are
-#          set on success or cleared on failure.
+#+         This routine can either check for a valid name synstax (-n option)
+#          or search the CEN_NET_HOSTS configuration table.
+#
+#+         The **_nethost_mac**, **_nethost_ip**, **_nethost_dom** and **_nethost_name**
+#          variables are set on success or cleared on failure. Any domain name
+#          is removed from **_nethost_name[0]** and saved in **_nethost_dom**.
+#
 # ------------------------------------------------------------------------------
 _nethost_mac=
 _nethost_ip=
 _nethost_name=()
+_nethost_domain=
 nethost() {
-    local _only
+    local _only _oerr _onam
     while [ "${1::1}" = '-' ] ; do
       case "$1" in
-      --)   shift ; break ;;
-      -c)   _only='c' ;;
-      -s)   _only='s' ;;
-      *)    _cen_abort - "$1"
+      -)     break ;;
+      --)    shift ; break ;;
+      -c)    _only='c' ;;
+      -e|-f) _oerr="$1" ;;
+      -n)    _onam=1 ;;
+      -s)    _only='s' ;;
+      *)     _cen_abort - "$1"
       esac ; shift
     done
 
-    _nethost_mac= ; _nethost_ip= ; _nethost_name=()
-    netconfig || return 1
+    _nethost_mac= ; _nethost_ip= ; _nethost_name=() ; _nethost_domain=
+    netconfig $_oerr || return 1
 
     local host snam sdom name="${1:--}"
-    [ "$name" = '-' ] && return 1
 
-    if [ "${name//[0-9]/}" != '...' ] ; then            # not an ipv4 address...
+    if [ "${name//[0-9]/}" = '...' ] ; then             # is an ipv4 address...
+        _nethost_ip="$name"
+    elif [ "${name//[0-9a-f]/}" = ':::::' ] ; then      # is a mac address...
+        _nethost_mac="$name"
+    else
         snam="${name%%.*}" ; sdom="${name#*.}"
-        [ "$name" = "$sdom" ] && sdom=
-        [ "$sdom" = "$CEN_NET_DOMAIN" ] && name="$snam" # no local dom in hosts
+        if [ "${name:--}" = '-' ] ; then
+            [ -n "$_oerr" ] && error $_oerr $"Missing hostname" ; return 1
+        elif [ -n "${name//[a-z0-9_-]/}" ] ; then
+            [ -n "$_oerr" ] && error $_oerr $"Invalid hostname:" "$name" ; return 1
+        fi
+        _net_host_name="$name"
+        if [ "$name" = "$sdom" ] ; then                 # no domain specified
+            sdom=
+        elif [ "$sdom" = "$CEN_NET_DOMAIN" ] ; then
+            sdom= ; name="$snam"                        # no local dom in hosts
+        else
+            if [ -n "$_onam" ] ; then                   # name check only
+                _nethost_domain="$sdom" ; return 0
+            fi
+            [ -n "$_oerr" ] && error $_oerr $"Domain mismatch:" "$name" ; return 1
+        fi
     fi
+    [ -n "$_onam" ] && return 0                         # name check only
+
+    # loop over host table
 
     for host in "${CEN_NET_HOSTS[@]}" '-' ; do
-        if [ "$host" = '-' ] ; then                     # no find
-            _nethost_mac= ; _nethost_ip= ; return 1
+        if [ "$host" = '-' ] ; then                     # nothing found
+            [ -n "$_oerr" ] && error $_oerr $"Host not found:" "$name"
+            _nethost_mac= ; _nethost_ip= ; _nethost_name=() ; return 1
         fi
         [ "${host/$name/}" = "$host" ] && continue      # quick pre-check
         set -- $host
         _nethost_mac="$1" ; shift
         _nethost_ip="$1"  ; shift
-        if [ "$name" = "$_nethost_ip" ] ; then          # match by ip address
+        if [ "$name" = "$_nethost_ip" -o \
+             "$name" = "$_nethost_mac" ] ; then         # match by ip/mac address
             _nethost_name=("$@") ; break
         fi
         [ -z "$snam" ] && continue                      # no name to search
@@ -563,7 +601,7 @@ netiface() {
     esac
 
     [ "$_mapm" = 'k' ] && _rslt="$_path$_cen_netiface_kern" || _rslt="$_path$_cen_netiface_name"
-    [ -z "$_vnam" ] && _netiface="$_rslt" || printf -v "$_vnam" "%s" "$_rslt"
+    [ -z "$_vnam" ] && _netiface="$_rslt" || printf -v "$_vnam" '%s' "$_rslt"
     [ -z "$_exst" ] && return 0
     [ -n "$_cen_netiface_kern" ] && [ -e "/sys/class/net/$_cen_netiface_kern" ] && return 0
     $_oerr $"No such interface:" "$_cen_netiface_name ($_cen_netiface_kern)"
@@ -589,11 +627,11 @@ _cen_net_maptest() {
         _name="$1" ; shift
         [ -e "$_name" ] || continue
         case "${_name##*/}" in
-        en?p?)  ((_vote += 1)) ;;
-        wl?p?)  ((_vote += 1)) ;;
-        end?)   ((_vote += 1)) ;;
-        eth?)   ((_vote -= 1)) ;;
-        wlan?)  ((_vote -= 1)) ;;
+        en*[su]*)   ((_vote += 1)) ;;
+        wl*[su]*)   ((_vote += 1)) ;;
+        end?)       ((_vote += 1)) ;;
+        eth?)       ((_vote -= 1)) ;;
+        wlan?)      ((_vote -= 1)) ;;
         esac
     done
     $CEN_TRACE2 -a -c "interface votes" "$_vote"
@@ -622,20 +660,14 @@ _cen_net_mapinit()  {
         local _item _more=()
         for _item in /sys/class/net/en* ; do
             case "${_item##*/}" in
-            *u?)    [ -e "$_item" ] && _cen_net_mapiadd 'usb' "${_item##*/}" ;;
-            end?)   [ -e "$_item" ] && _cen_net_mapiadd 'eth' "${_item##*/}" ;;
+            en*u*)  [ -e "$_item" ] && _cen_net_mapiadd 'usb' "${_item##*/}" ;;
+            end*)   [ -e "$_item" ] && _cen_net_mapiadd 'eth' "${_item##*/}" ;;
             *)      [ -e "$_item" ] && _more+=("$_item")
             esac
         done
         for _item in "${_more[@]}" ; do
             case "${_item##*/}" in
-            enp?s?) _cen_net_mapiadd 'eth' "${_item##*/}"
-            esac
-        done
-        for _item in "${_more[@]}" ; do
-            case "${_item##*/}" in
-            enp?s?) ;;
-            *)      _cen_net_mapiadd 'eth' "${_item##*/}"
+            en*s*) _cen_net_mapiadd 'eth' "${_item##*/}"
             esac
         done
         for _item in /sys/class/net/wlp* /sys/class/net/wl[!p]* ; do
@@ -699,7 +731,7 @@ _cen_net_mapping() {
         case "$_mapn" in
         wlan*)  _cen_net_mapsysd "$_mapn" /sys/class/net/wlp* /sys/class/net/wl[!p]* ;;
         usb*)   _cen_net_mapsysd "$_mapn" /sys/class/net/enp*u? ;;
-        *)      _cen_net_mapsysd "$_mapn" /sys/class/net/enp* /sys/class/net/en[!p]* ;;
+        *)      _cen_net_mapsysd "$_mapn" /sys/class/net/enp*[!u]? /sys/class/net/en[!p]* ;;
         esac
         _cen_net_mapsysd "$_mapn"
     fi
@@ -797,7 +829,7 @@ _cen_net_mapiadd() {
 #
 # Options:  -e  error if network not found
 #           -f  fatal error if network not found
-#           -s  save result to named variable
+#           -s  save network entry to named variable
 #
 # Arguments:<name>  network name, see below
 #           <indx>  index to CEN_NET_NETWORKS array
@@ -868,10 +900,11 @@ netindex() {
 # ------------------------------------------------------------------------------
 # netmask - check if address is part of a sub-net
 #
-# Call:    (1) netmask [-e|-f] <base>/<bits>        # is base address valid?
-#          (2) netmask [-e|-f] <base>/<bits> <addr> # is <addr> in base net?
+# Call:    (1) netmask [-e|-f] [-a] <base>/<bits>        # is base address valid?
+#          (2) netmask [-e|-f] [-a] <base>/<bits> <addr> # is <addr> in base net?
 #
-# Options:  -e  report syntax errors
+# Options:  -a  accept invalid netmask
+#           -e  report syntax errors
 #           -f  make syntax errors fatal
 #
 # Arguments:<base>  sub-net base address
@@ -888,10 +921,11 @@ _netmask_addr=                          # current binary address
 _netmask_curr=                          # current argument
 _netmask_mask=                          # mask high bits
 netmask() {
-    local _oerr
+    local _oerr _oain
     while [ "${1::1}" = '-' ] ; do
       case "$1" in
       --)       shift ; break ;;
+      -a)       _oain=1 ;;
       -e|-f)    _oerr="$1" ;;
       *)        _cen_abort - "$1"
       esac ; shift
@@ -910,12 +944,15 @@ netmask() {
     fi
 
     if [ "${2:--}" = '-' ] ; then               # check for valid subnet
+        [ -n "$_oain" ] && return 0
         [ $((_netmask_addr & ~_netmask_mask)) = 0 ] && return 0
         [ -n "$_oerr" ] && error $_oerr $"Invalid sub-net specification:" "$1"
         return 2
     fi
 
+#local _bit1="$_netparse_bits"
     netparse -a $_oerr -n "$2" || return 1
+#[ "$_netparse_bits" != "$_bit1" ] && trace -a -c " mask#2" "$_bit1 $_netparse_bits"
     netconv -b "$_netparse_addr" || return 1
     $CEN_TRACE2 -a -c -p " check" "%-14s -> %x" "$2" "$_netconv"
     [ $((_netconv & _netmask_mask)) = "$_netmask_addr" ]
@@ -987,14 +1024,16 @@ netoption() {
 # ------------------------------------------------------------------------------
 # netparse - Parse an IPv4 address and/or netmask
 #
-# Call:     netparse [-a] [-b] [-e|-f] [-n] [<ipaddr>][/<maskbits>]
-#           netparse [-b] [-e|-f] [-n] <maskbits>
+# Call:     netparse [-a] [-b] [-e|-f] [-n] [-r] [<ipaddr>][/<maskbits>]
+#           netparse [-b] [-e|-f] [-n] [-r] <maskbits>
 #
 # Options:  -a  address must be present
 #           -b  netmask bits must be present
 #           -e  report errors
 #           -f  make errors fatal
 #           -n  do not fill _netparse_mask, just clear it
+#           -r  check min/max of mask bits (minimum is 16, maximum is 21)
+#               also check network address class if <ipaddr> is passed
 #
 # Arguments:<ipaddr>   a dotted 4-part IPv4 address -or- a network reference
 #           <maskbits> number of maskbit as decimal number
@@ -1038,6 +1077,7 @@ netparse() {
       -e)   _oerr='error' ;;
       -f)   _oerr='fatal' ;;
       -n)   _onom=1 ;;
+      -r)   _orng=1 ;;
       *)    _cen_abort - "$1"
       esac ; shift
     done
@@ -1067,13 +1107,31 @@ netparse() {
         $_oerr $"Address has invalid syntax:" "$1" ; return 5
     fi
 
+    # check bitmask limits and network class
+    if [ -n "$_orng" -a -n "$_netparse_bits" ] ; then
+        local _mmin=0
+        case "$1" in
+        192.168.*)  _mmin=16 ;;
+        172.16.[0-9].*|172.16.1[0-5].*)
+                    _mmin=20 ;;
+        10.*)       _mmin=16
+        esac
+        if [ "$_mmin" = 0 ] ; then
+            warning -p $"Address '%s' is in a public IPv4 range"
+        elif [ "$_netparse_bits" -gt 21 ] ; then
+            $_oerr -p $"Netmask is too long (max %s): %s" 21 "$1" ; return 6
+        elif [ "$_netparse_bits" -lt "$_mmin" ] ; then
+            $_oerr -p $"Netmask is too short (min %s): %s" "$_mmin" "$1" ; return 7
+        fi
+    fi
+
     # make netmask
     if [ -n "$_onom" ] ; then
         _netparse_mask=
     elif netconv -d $((((1 << 32) - 1) & ~((1 << (32 - _netparse_bits)) - 1))) ; then
         _netparse_mask="$_netconv"
     else
-        _netparse_mask='0.0.0.0' ; return 1
+        _netparse_mask='0.0.0.0' ; return 8
     fi
     return 0
 }
@@ -1986,7 +2044,8 @@ CEN_NET_MASTER='$CEN_NET_MASTER'
 #           an interface to exist. Form (4) runs **ip**°<what> and can insert <dev>
 #           after <cmd>. Any tool can be run using form (5).
 #
-#+          Form (6) sets or checks "/proc/sys/net/ipv?/conf/.../disable_ipv?"
+#+          Form (6) sets or checks "/proc/sys/net/ipv?/conf/.../disable_ipv?" to enable
+#           or disable the IPv6 protocol stack.
 #
 # Options:  -4  [*] use ipv4 (adds option -4 when running a tool)
 #           -6  use ipv6 (adds option -6 when running a tool)
@@ -2020,21 +2079,21 @@ CEN_NET_MASTER='$CEN_NET_MASTER'
 #.          nettool -d wlan0 -w -t iw dev wlan0 set 4addr on
 # ------------------------------------------------------------------------------
 nettool() {
-    local _ifce _fipv _ferr='-e -p' _oerr=error _orun _labl _tool _carr _cmnd _mode _temp _what _stat
+    local _ifce _fipv _ferr='-e -p' _oerr='error' _orun _labl _tool _carr _cmnd _mode _temp _what _stat
     while [ "${1::1}" = '-' ] ; do
         case "$1" in
         --)     shift ; break ;;
         -4|-6)  _fipv="$1" ;;
-        -a)     _tool=ip ; _what='address' ;;
+        -a)     _tool='ip' ; _what='address' ;;
         -c)     _carr=1 ;;
         -d)     shift ; _ifce="$1" ;;
-        -f)     _ferr='-f -p' ; _oerr=fatal ;;
+        -f)     _ferr='-f -p' ; _oerr='fatal' ;;
         -i)     shift ; _tool='ip' ; _what="$1" ;;
         -o)     _tool='ip' ; _what='route' ;;
         -q)     _ferr='-q' ; _oerr=: ;;
         -r)     _orun='-r' ;;
         -t)     shift ; _tool="$1" ;;
-        -w)     _ferr='-w -p' ; _oerr=warning ;;
+        -w)     _ferr='-w -p' ; _oerr='warning' ;;
         *)      _cen_abort - "$1"
         esac ; shift
     done
@@ -2112,7 +2171,7 @@ nettool() {
                 [ "$_cmnd" = 'isu' ] && return 1
                 [ "$_cmnd" = 'dow' ] && return 0
                 [ "$_cmnd" = 'exi' ] && return 0
-                if sysrun -q ifquery "/dev/$_ifce" ; then       # managed by ifup ...
+                if sysrun -q ifquery "$_ifce" ; then            # managed by ifup ...
                     _tool='ifup' ; set -- '--force' "$_ifce"
                 else
                     _tool='ip' ; set -- link set up "$_ifce"
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriconfig b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriconfig
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriconfig
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriconfig
@@ -4,7 +4,7 @@ CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2018-2024; BSD License"
 CEN_TITLE="Repository Management and Synchronisation Tool"
 
 # ATTENTION: PATH is set non-standard to allow action 'setup' as described in help
-PATH="${0%/*}:$PATH" . _centauri_bash_lib -a -d -f -m sys -y - '0.33:3' || exit 2
+PATH="${0%/*}:$PATH" . _centauri_bash_lib -a -d -f -m sys -y - '0.35:4' || exit 2
 
 CEN_OPT_ALL=                    # see --all
 CEN_OPT_CONFIG=                 # see --config
@@ -17,6 +17,7 @@ CEN_OPT_CLIENT=                 # see --host
 CEN_OPT_MASTER=                 # see --master
 CEN_OPT_NICKNAME=               # see --nickname
 CEN_OPT_OVERRIDE=               # see --override
+CEN_OPT_PASSWD=                 # see --passwd
 CEN_OPT_PRIVATE=                # see --private
 CEN_OPT_ROLE=                   # see --role
 CEN_OPT_ROOT=                   # see --root
@@ -107,7 +108,43 @@ do_orphans() {
     done
 }
 
+# ------------------------------------------------------------------------------
+# get server and module from CEN_OPT_REPO: <vdis>|- <vcfg>|- <vsvr>|- <vsyn>|-
+# ------------------------------------------------------------------------------
+#       vdis    name of variable for dist nickname      (see --nickname)
+#       vcfg    ...              for config name        (see --domain)
+#       vsvr    ...              for rsync server       (DAT_NET_NICK)
+#       vsyn    ...              for rsync module       (CEN_RSYNC_MODULE secret)
+#
+#       distribution         the distribution's nickname     --nickname
+#       configuration        the repository domain/realm     --domain
+#       rsync server         the master-repository server    --repository
+#       rsync module         sync module for authorization   --repository
+# ------------------------------------------------------------------------------
+do_optrepo() {
+    # split repository string (module is optional)
+    local _rsvr="${CEN_OPT_REPO%%:*}" _rmod="${CEN_OPT_REPO#*:}"
+    [ "$_rsvr" = "$CEN_OPT_REPO" ] && _rmod="$CEN_RSYNC_MODULE"
+    [ "${_rsvr:--}" = '-' ] && _rsvr="$DAT_NET_NICK"
+    [ "${_rsvr%.*}" = "$_rsvr" ] && _rsvr+=".$CEN_NET_DOMAIN"
+
+    local _rdis="$DAT_NICKNAME" _rcfg="${CEN_OPT_DOMAIN:-$CEN_NET_CONFIG}"
+    if [ "${_rmod:--}" = '-' ] ; then
+        _rmod="$_rcfg" ; [ -z "$CEN_OPT_MASTER" ] && _rmod+="-${CEN_OPT_HOST:-$HOSTNAME}"
+    fi
+
+#    [ "${_rsvr:--}" = '-' ] && error "Please use '--repository=' to specify the server name"
+#    [ "${_rmod:--}" = '-' ] && error "Please use '--repository=' to specify the repository name"
+
+    [ "$1" != '-' ] && printf -v "$1" '%s' "$_rdis"     # dist
+    [ "$2" != '-' ] && printf -v "$2" '%s' "$_rcfg"     # config
+    [ "$3" != '-' ] && printf -v "$3" '%s' "$_rsvr"     # server
+    [ "$4" != '-' ] && printf -v "$4" '%s' "$_rmod"     # module
+}
+
+# ------------------------------------------------------------------------------
 # setup paths (after option parsing): [-h|-r]
+# ------------------------------------------------------------------------------
 do_setup() {
     local hopt ropt
     [ "$1" = '-h' ] && hopt=1
@@ -241,7 +278,7 @@ do_repository() {
     ___repo_setup() {
         trace -a -c "Create symlink" "$2 => $DAT_ROOT/$1"
         folder -f -m -- "$2"
-        symlink -m -f -r -s -- "$2" "$DAT_ROOT/$1"
+        symlink -m -f -l -s -- "$2" "$DAT_ROOT/$1"
     }
 
     trace -a -c "Check folders at" "$DAT_REPOSIT"
@@ -661,10 +698,10 @@ actionCleanup() {
 # ------------------------------------------------------------------------------
 actionLocal() {
     local over                              # set be 'override' action
-    local cmdc="cp -abu --dereference"
-    local cmdd="rm -f"
-    local cmdl="/usr/bin/ln -f -r -s"       # no bash built-in
-    [ -n "$CEN_OPT_FORCE" ] && cmdc="cp -preserve=mode,ownership --dereference"
+    local cmdc='cp -abu --dereference'
+    local cmdd='rm -f'
+    local cmdl='/usr/bin/ln -f -r -s'       # no bash built-in
+    [ -n "$CEN_OPT_FORCE" ] && cmdc='cp -preserve=mode,ownership --dereference'
     CEN_HISTORY='-'
 
     # setup the repository
@@ -863,32 +900,26 @@ actionLocal() {
 # ------------------------------------------------------------------------------
 actionServer() {
 
-    # helper to run rsync: rget|rput (using rnam, rmod, rcon)
+    # helper to run rsync: rget|rput
+    #   rdis := distribution
+    #   rcfg := configuration
     #   rnam := remote server
     #   rmod := repository module (domain)
-    #   rcon := configuration (distro)
     ___run_rsync() {
-        # override server and module
-        local pdom="${CEN_OPT_DOMAIN:-$DAT_NET_DOMAIN}"
-        local psrv pnam="${rnam:-$DAT_NET_NICK}" pmod="${rmod:-$pdom}"
-        [ "${pnam:--}" = '-' ] && error "Please use '--repository=' to specify the server name"
-        [ "${pmod:--}" = '-' ] && error "Please use '--repository=' to specify the repository name"
-        [ -d "$DAT_ROOT" ] || fatal "DAT_ROOT is invalid: $DAT_ROOT"
-        [ -n "$rcon" ] || fatal "DAT_NICKNAME not set"
 
-        folder -m "$DAT_ROOT/$bdir/$pmod"
+        folder -m "$DAT_ROOT/$bdir/$rcfg"
         error -t || return
 
-        local opts=(--silent)
-        opts+=( --exclude="/$bdir/***" --all --exclude=".*" --exclude="*~" --exclude="*.pyc"
-                --exclude="__pycache__/***" --exclude="README.html" --exclude="library/*.?" )
+        local psrv pnam="${rnam%%.*}" opts=(--silent)
+        opts+=( --exclude "/$bdir/***" --all --exclude '.*' --exclude '*~' --exclude '*.pyc'
+                --exclude '__pycache__/***' --exclude 'README.html' --exclude 'library/*.?' )
 
         # protect server against rget/rput (using $HOSTNAME)
-        if [ "$DAT_NET_ROLE" = "PRIMARY" -o "$DAT_NET_ROLE" = "SECONDARY" ] && \
+        if [ "$DAT_NET_ROLE" = 'PRIMARY' -o "$DAT_NET_ROLE" = 'SECONDARY' ] && \
            [ "$DAT_NET_MODE" != 'SLAVE' ] ; then
-            if [ "$1" = "rget" ] ; then
+            if [ "$1" = 'rget' ] ; then
                 if [ "$pnam" = "$HOSTNAME" -o "$pnam" = "$DAT_NET_NICK" ] ; then
-                    message "Ignoring 'rget' on $DAT_NET_ROLE server of '$pmod'"
+                    message "Ignoring 'rget' on $DAT_NET_ROLE server of '$rcfg'"
                     return
                 fi
             elif [ "$pnam" = "$HOSTNAME" -o "$pnam" = "$DAT_NET_NICK" ] ; then
@@ -896,41 +927,41 @@ actionServer() {
                 return
             fi
             opts+=( --include="^/$adir/$"
-                    --include="^/$adir/$pmod/***" )
+                    --include="^/$adir/$rcfg/***" )
         # add client's archive path to rsync
         elif [ -d "$DAT_ROOT/$adir" ] ; then
             opts+=( --include="^/$adir/$"
-                    --include="^/$adir/$pmod/$"
-                    --include="^/$adir/$pmod/$DAT_NET_HOST$" )
+                    --include="^/$adir/$rcfg/$"
+                    --include="^/$adir/$rcfg/$DAT_NET_HOST$" )
         fi
 
         # exclude library proxy (should be auto updated via config)
-        opts+=( --exclude="^/$cdir/$rcon/@admin/tools/_centauri_bash_lib$" )
+        opts+=( --exclude="^/$cdir/$rdis/@admin/tools/_centauri_bash_lib$" )
 
         # data to copy
         opts+=( --include="^/$cdir/$"
-                --include="^/$cdir/$rcon/$"
-                --include="^/$cdir/$rcon/@admin/***" )
+                --include="^/$cdir/$rdis/$"
+                --include="^/$cdir/$rdis/@admin/***" )
         if [ -n "$CEN_OPT_GLOBAL" ] ; then
-            opts+=( --include="^/$cdir/$rcon/$pmod/***"
-                    --include="^/$cdir/$rcon/@soho/***" )
+            opts+=( --include="^/$cdir/$rdis/$rcfg/***"
+                    --include="^/$cdir/$rdis/@soho/***" )
          else
-            opts+=( --include="^/$cdir/$rcon/$pmod/$"
-                    --include="^/$cdir/$rcon/$pmod/@shared/***"
-                    --include="^/$cdir/$rcon/$pmod/$DAT_NET_HOST/***" )
+            opts+=( --include="^/$cdir/$rdis/$rcfg/$"
+                    --include="^/$cdir/$rdis/$rcfg/@shared/***"
+                    --include="^/$cdir/$rdis/$rcfg/$DAT_NET_HOST/***" )
         fi
-        opts+=( --exclude="*" )
+        opts+=( --exclude='*' )
 
         # proxy and repository
         [ -n "$CEN_OPT_PROXY" ] && opts+=( --proxy="$CEN_OPT_PROXY" )
-        printf -v psrv "root@%s::@%s" "$pnam" "${CEN_RSYNC_MODULE:-$pmod}"
-        if [ -n "$CEN_RSYNC_PASSWD" ] ; then
-            export RSYNC_PASSWORD="$CEN_RSYNC_PASSWD"
-        else
-            opts+=( --passsword=+ )
-        fi
-        [ "$1" = "rget" ] && opts+=( --backup="$DAT_ROOT/$bdir/$pmod" sync "$psrv" "$DAT_ROOT" )
-        [ "$1" = "rput" ] && opts+=( --backup="$bdir/$pmod" sync "$DAT_ROOT" "$psrv" )
+        printf -v psrv 'root@%s::@%s' "$rnam" "$rmod"
+
+        # for CEN_RSYNC_xxx see: secrets/import/repository.conf
+        export RSYNC_PASSWORD
+        password -e -x -m 4 -u 'rsync' RSYNC_PASSWORD "$CEN_OPT_PASSWD" CEN_RSYNC_PASSWD || quit
+
+        [ "$1" = 'rget' ] && opts+=( --backup="$DAT_ROOT/$bdir/$rcfg" sync "$psrv" "$DAT_ROOT" )
+        [ "$1" = 'rput' ] && opts+=( --backup="$bdir/$rcfg" sync "$DAT_ROOT" "$psrv" )
 
         # encfs start for centauricopy (--password disables internal check)
         if [ -n "$CEN_OPT_PROXY" ] ; then
@@ -938,7 +969,6 @@ actionServer() {
         fi
 
         # copy configs
-        #quit "DEBUG centauricopy ${opts[*]}"
         embed -z -v centauricopy "${opts[@]}"
     }
 
@@ -949,23 +979,30 @@ actionServer() {
     local bdir='backup'
     local adir='archived'
 
-    # split repository string (module is optional)
-    local rnam="${CEN_OPT_REPO%%:*}" rmod="${CEN_OPT_REPO#*:}" rcon="$DAT_NICKNAME"
-    [ "$rnam" = "$CEN_OPT_REPO" ] && rmod=
+    local rdis      # distribution nickname
+    local rcfg      # configuration
+    local rnam      # rsync repository server
+    local rmod      # rsync repository module
+    do_optrepo rdis rcfg rnam rmod
+
+    [ -d "$DAT_ROOT" ] || fatal "DAT_ROOT is invalid:" "$DAT_ROOT"
+    [ -n "$rdis" ] || fatal "DAT_NICKNAME not set"
 
     # get PACKAGES list, sync with server
-    if [ "$CEN_ACTION" = "rput" ] ; then
-        if [ "$DAT_FAMILY" = "debian" ] ; then
+    if [ "$CEN_ACTION" = 'rput' ] ; then
+        if [ "$DAT_FAMILY" = 'debian' ] ; then
             local dest="$DAT_PRIVATE/PACKAGES"
-            dryrun "create package list: $dest" ||
+            dryrun "create package list:" "$dest" ||
                 system -e -p -z -- dpkg --get-selections > "$dest"
         fi
         [ "$DAT_NET_MODE" = 'SLAVE' -o "$DAT_NET_ROLE" = 'WORKSTATION' ] && ___run_rsync rput
     else
         [ "$DAT_NET_MODE" = 'SLAVE' -o "$DAT_NET_ROLE" = 'WORKSTATION' ] && ___run_rsync rget
-        local dadm="$DAT_ROOT/$cdir/$rcon/@admin"
-        [ -d "$dadm" ] && symlink -m -r "$dadm" "$DAT_ROOT/admin"
+        local dadm="$DAT_ROOT/$cdir/$rdis/@admin"
+        [ -d "$dadm" ] && symlink -m -l "$dadm" "$DAT_ROOT/admin"
     fi
+
+    ### TODO message for no action, -R secondary
 }
 
 # ------------------------------------------------------------------------------
@@ -983,7 +1020,7 @@ actionSync() {
     CEN_ACTION='put'     ; actionLocal $carg
     CEN_ACTION='get'     ; actionLocal $carg
 
-    CEN_ACTION="rput"    ; actionServer
+    CEN_ACTION='rput'    ; actionServer
 
     if [ -n "$DAT_OVERRIDE" ] ; then
         warning -a "Using repository overrides - no implicit '$CEN_NAME autorun'"
@@ -998,24 +1035,26 @@ actionSync() {
 # ------------------------------------------------------------------------------
 actionInfo() {
     [ "$CEN_VERB" -lt 1 ] && return
-    local tab=$'\t'
-    echo "\
+    local sdis scfg ssvr smod ; do_optrepo sdis scfg ssvr smod
 
-Domain${tab}$DAT_NET_DOMAIN
-Host${tab}$DAT_NET_HOST
-Server${tab}$DAT_NET_NICK
-Role${tab}$DAT_NET_ROLE
-
-Distro${tab}$DAT_DISTRO
-Family${tab}$DAT_FAMILY
-Nick${tab}$DAT_NICKNAME
-Keys${tab}${DAT_KEYS[*]}
-
-Root${tab}$DAT_ROOT
-Config${tab}$DAT_CONFIG
-Private${tab}$DAT_PRIVATE
-Shared${tab}$DAT_SHARED
-"
+    local ikey ival item list=()
+    local rpri="$CEN_ROOT/configs/$sdis/$scfg/$CEN_OPT_HOST"
+    local rsha="$CEN_ROOT/configs/$sdis/$scfg/@shared"
+    for item in 'Distribution:sdis' 'Configuration:scfg' 'Server:ssvr' 'Module:smod' '' \
+                'Host:DAT_NET_HOST' 'Role:DAT_NET_ROLE' 'Family:DAT_FAMILY' \
+                'Nickname:DAT_NICKNAME' 'Keys:{DAT_KEYS[*]}' '' \
+                'Root:DAT_ROOT' 'Config:DAT_CONFIG' \
+                'Private:rpri' 'Shared:rsha' ; do
+        if [ "${item:-}" = '-' ] ; then
+            list+=('')
+        else
+            splitkeyval "$item" ikey ival ':'
+            [ -n "$ival" ] && eval "ival=\"\$$ival\""
+            printf -v item '    %-14s %s' "$ikey" "$ival"
+            list+=("$item")
+        fi
+    done
+    splitjoin -s - -l -i list
 }
 
 # ------------------------------------------------------------------------------
@@ -1196,7 +1235,7 @@ actionCheck() {
             ;;
         esac
     done
-message "dist $DAT_DISTRO"
+
     if [ "$nrep" = 0 ] ; then
         message -p "No errors found"
     else
@@ -1387,39 +1426,41 @@ actionMerge() {
 options() {
     case "$CEN_ACTION" in
     -A|--all)
-        optarg "all"       -                  ;;            # flag
+        optarg 'all'       -                  ;;            # flag
     -C|--con*)
-        optarg "config"    -               -t ;;            # text
+        optarg 'config'    -               -t ;;            # text
     -D|--dis*)
-        optarg "distro"    -               -t ;;            # text
+        optarg 'distro'    -               -t ;;            # text
     -E|--ext*)
-        optarg "extra"     -                  ;;            # flag
+        optarg 'extra'     -                  ;;            # flag
     -F|--fam*)
-        optarg "family"    -               -t ;;            # text
+        optarg 'family'    -               -t ;;            # text
     -G|--glo*)
-        optarg "global"    -                  ;;            # flag
+        optarg 'global'    -                  ;;            # flag
     -H|--hos|--host)
-        optarg "host"      CEN_OPT_CLIENT  -t ;;            # text
+        optarg 'host'      CEN_OPT_CLIENT  -t ;;            # text
     -I|--dom*)
-        optarg "domain"    -               -t ;;            # text
+        optarg 'domain'    -               -t ;;            # text
     -M|--mas*)
-        optarg "master"    -                  ;;            # text
+        optarg 'master'    -                  ;;            # flag
     -N|--nic*)
-        optarg "nickname"  -               -t ;;            # text
+        optarg 'nickname'  -               -t ;;            # text
     -O|--roo|--root)
-        optarg "root"      -               -d ;;            # folder
+        optarg 'root'      -               -d ;;            # folder
     -P|--pri*)
         optarg 'private'   -               -d ;;            # folder
     -R|--rol|--role)
-        optarg "role"      -               "pri.*|sec.*|wor.*" ;;
+        optarg 'role'      -               'pri.*|sec.*|wor.*' ;;
     -S|--sha*)
         optarg 'shared'    -               -d ;;            # folder
     -V|--ove*)
         optarg 'override'  -               -o ;;            # ternary
+    -W|-pas*)
+        optarg 'passwd'    -               -t ;;            # text
     -X|--pro*)
-        optarg "proxy"     -               -t ;;            # text
+        optarg 'proxy'     -               -t ;;            # text
     -Y|--rep*)
-        optarg "repository" CEN_OPT_REPO   -t ;;            # text
+        optarg 'repository' CEN_OPT_REPO   -t ;;            # text
     esac
 }
 
@@ -1436,32 +1477,32 @@ actions() {
 
     case "$CEN_ACTION" in
     aut*)
-        ___invoke 'autorun' -          0 ;;
+        ___invoke 'autorun' -             0 ;;
     che*)
-        ___invoke 'check'   -          0 ;;
+        ___invoke 'check'   -             0 ;;
     cron|sync)
-        ___invoke  -     actionSync    0 ;;
+        ___invoke  -        actionSync    0 ;;
     dif|diff)
-        ___invoke 'diff' actionList  0 1 ;;
+        ___invoke 'diff'    actionList  0 1 ;;
     fix)
-        ___invoke 'fix'  actionCheck   0 ;;
+        ___invoke 'fix'     actionCheck   0 ;;
     get|put)
-        ___invoke  -     actionLocal 0 1 ;;
+        ___invoke  -        actionLocal 0 1 ;;
     inf|info)
-        ___invoke 'info'  -            0 ;;
+        ___invoke 'info'    -             0 ;;
     ite*)
-        ___invoke 'items' -          0 1 ;;
+        ___invoke 'items'   -           0 1 ;;
     lis|list)
-        ___invoke 'list'  -          0 1 ;;
+        ___invoke 'list'    -           0 1 ;;
     rget|rput)
-        ___invoke  -     actionServer  0 ;;
+        ___invoke  -        actionServer  0 ;;
 
     cle*)
-        invoke -r 'cleanup' -          0 ;;
+        invoke -r 'cleanup' -             0 ;;
     set*)
-        invoke -r 'setup' -          0 2 ;;
+        invoke -r 'setup'   -           0 2 ;;
     mer*)
-        invoke -r 'merge' -            2 ;;
+        invoke -r 'merge'   -             2 ;;
     esac
 }
 
@@ -1496,6 +1537,7 @@ $CEN_USE_OPTIONS
 
        -E --extra           select non-installed extra files
        -G --global          update all hosts (for administrative use only)
+       -W --passw   <pasw>  rsync password for repository
        -X --proxy   <host>  use "ssh <host> nc %H 873" as rsync connection prog
        -Y --repos   <repo>  modifies server and module
 
@@ -1533,7 +1575,26 @@ arguments:
        <role>               computer role: primary|secodary|workstation
        <repo>               [<server>[:<module>]  for example '$_repa'
 
-setup: Use the following commands for an initial setup:
+tools: This script uses 'centauricopy' (for rsync) and 'centauridiff'. The
+       absence of option '--master' uses staging on the server side, see
+       'centaurimachines'. Defaults for the 'rsync' password/module to be
+       used are loaded be 'centaurisecrets' at network start time in file
+       'secrets/import/repository.conf'.
+
+terms: Using options to override the defaults:
+
+    distribution         the distribution's nickname     --nickname
+    configuration        the repository domain/realm     --domain
+    rsync server         the master-repository server    --repository
+    rsync module         sync module for authorization   --repository
+
+    Per default the 'rsync server' is the primary domain server and the
+    'rsync module' is taken from the secrets data read from the server
+    via 'centaurisecrets' or <config>-<hostname> if not available. Use
+    opition '--master' to override this as <config> to bypass staging
+    (see 'centaurimachines' for details).
+
+setup: Use the following commands for an initial client setup:
 
        mkdir -p /tmp/xxx/library /tmp/xxx/tools
        scp -p $_repo/library/"*_???" /tmp/xxx/library
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurinetcfg b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurinetcfg
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurinetcfg
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centaurinetcfg
@@ -254,10 +254,12 @@ do_config() {
 
     # check for valid network (need netmask bits): <indx> <nnam> <addr>
     ___arg_network() {
-        local indx="$1" nnam="$2" addr="$3" emsg
+        local indx="$1" nnam="$2" addr="$3" emsg # aopt
         if [ -z "$indx" ] ; then
             emsg="Invalid network name:"
         else
+#            [ "$indx" = 0 -o "$indx" = 7 ] && aopt='-a'
+#            netmask $aopt -- "$addr"            # also sets _netparse_addr amd bits
             netmask -- "$addr"                  # also sets _netparse_addr amd bits
             case $? in
             0)  netconv -d -- "$_netmask_mask"  # need to convert to dec -> dotted
@@ -320,10 +322,10 @@ do_config() {
         if [ "${#apar[@]}" -gt 4 ] ; then
             ___error "Too many fields: $1 (dport|sport|daddr|saddr)"
         else
-            ___filter_chk_port "${apar[0]}" "destination" &&
-            ___filter_chk_port "${apar[1]}" "source" &&
-            ___filter_chk_addr "${apar[2]}" "destination" &&
-            ___filter_chk_addr "${apar[3]}" "source" && return 0
+            ___filter_chk_port "${apar[0]}" 'destination' &&
+            ___filter_chk_port "${apar[1]}" 'source' &&
+            ___filter_chk_addr "${apar[2]}" 'destination' &&
+            ___filter_chk_addr "${apar[3]}" 'source' && return 0
         fi
         return 1
     }
@@ -427,7 +429,7 @@ do_config() {
     }
 
     ___config_homedns() {
-        ___arg_rng_chk $# 2 3 "homedns" || return 1
+        ___arg_rng_chk $# 2 3 'homedns' || return 1
         hdns+=("$1 $2 ${3:-$2}")
         ___message "%-10s %s %s %s" 'homedns' "$1" "$2" "${3:-$2}"
     }
@@ -439,20 +441,20 @@ do_config() {
         local ip4a="$1" ; shift
         local name="$1"
 
-        if [ "$maca" = '+' ] ; then             # allow duplicated host entry
-            if [ -n "${DAT_MAP_IP[$name]}" ] ; then
-                ___message "%-10s %-18s %-18s %s   # ignored " 'host' "$maca" "$ip4a" "$name"
-                return
-            fi
-            maca='-'
-        fi
-
         if [ "$ip4a" = '+' ] ; then
             ip4a="${_netparse_addr##*.}" ; ((ip4a += 1))
             ip4a="${_netparse_addr%.*}.$ip4a"
             _netparse_addr="$ip4a"
         elif [ "$ip4a" != '-' ] ; then
             ___arg_address "$ip4a" ; ip4a="$_netparse_addr"
+        fi
+
+        if [ "$maca" = '+' ] ; then             # allow duplicated host entry
+            if [ -n "${DAT_MAP_IP[$name]}" ] || [ -n "${DAT_MAP_NAME[$ip4a]}" ] ; then
+                ___message "%-10s %-18s %-18s %s   # ignored " 'host' "$maca" "$ip4a" "$name"
+                return
+            fi
+            maca='-'
         fi
 
         if [ "$name" = "$CEN_NET_SERVER_GEN" ] ; then
@@ -468,7 +470,7 @@ do_config() {
     }
 
     ___config_iface() {
-        ___arg_rng_chk $# 3 3 "iface" || return 1
+        ___arg_rng_chk $# 3 3 'iface' || return 1
         case "$1" in
         eth[01]|wlan[01])   ;;
         *)      ___error "Invalid interface name:" "$1"
@@ -485,35 +487,45 @@ do_config() {
 
     ___config_network() {
         ___arg_rng_chk $# 2 2 'network' || return 1
+        [ "$2" = '-' ] && return 0
+
         local indx
         case "$1" in
         *.*)        indx=0 ; CEN_NET_DOMAIN="$1" ;;
-        external)   [ "${2:--}" = '-' ] && return   # conditional override ...
-                    netindex 'other' -f ; indx="$_netindex"
-                    CEN_NET_NETWORKS[indx]= ;;      # allow to override
+        external)   indx=7 ;;
         *)          netindex "$1" && indx="$_netindex"
         esac
-        [ "$2" = '-' ] && return 0
-
         ___arg_network "$indx" "$1" "$2" || quit -e
+
         if [ "$indx" = 0 ] ; then
             CEN_NET_NETWORKS=("$_netparse_addr/$_netparse_bits")
             CEN_NET_NETMASK="$_netparse_mask"
             CEN_NET_NETBITS="$_netparse_bits"
         elif [ -z "$CEN_NET_NETWORKS" ] ; then
-            ___error "No base network defined:" "$1" || quit -e
+             ___error "No base network defined:" "$1" || quit -e
+        elif [ "$1" = 'external' ] ; then
+               if [ "$_netparse_bits" -lt "$CEN_NET_NETBITS" ] ; then
+                    CEN_NET_NETBITS="$_netparse_bits"
+                    CEN_NET_NETMASK="$_netparse_mask"
+               fi
+               local over=0
+               CEN_NET_EXTERNAL="$_netparse_addr/$_netparse_bits"
+               netmask "$CEN_NET_NETWORKS" "$CEN_NET_EXTERNAL" && ((over += 1))
+               netmask "$CEN_NET_EXTERNAL" "$CEN_NET_NETWORKS" && ((over += 2))
+               case "$over" in
+               1)   message -p $"External network '%s' is sub-net of base '%s'" \
+                               "$CEN_NET_EXTERNAL" "$CEN_NET_NETWORKS" ;;
+               2)   message -p $"Base network '%s' is sub-net of external '%s'" \
+                               "$CEN_NET_NETWORKS" "$CEN_NET_EXTERNAL" ;;
+               3)   __error $"Base and external are the same network" ;;
+               *)   __error $"Base and external network must overlap completely"
+               esac
+               CEN_NET_NETWORKS[7]="$CEN_NET_EXTERNAL"
         elif [ -n "${CEN_NET_NETWORKS[indx]}" ] ; then
             ___error "Network already defined:" "$1"
         elif ! netmask -- "$CEN_NET_NETWORKS" "$2" ; then
-            if [ "$indx" = 7 ] ; then
-                message -a "Using external sub-net:" "$2"
-                CEN_NET_EXTERNAL="$2"
-                CEN_NET_NETWORKS[indx]="$_netparse_addr/$_netparse_bits"
-            else
-                ___error "Sub-net not in base network:" "$1"
-            fi
+            ___error "Sub-net not in base network:" "$1"
         else
-            ___arg_network "$indx" "$1" "$2"
             CEN_NET_NETWORKS[indx]="$_netparse_addr/$_netparse_bits"
         fi
         ___message "%-10s %-16s %s" 'network' "$1" "$2"
@@ -1629,7 +1641,7 @@ actionStatus() {
 
     ___status_print() {
         local idnt
-        [ "$1" = "-i" ] && idnt="\n                            " && shift
+        [ "$1" = '-i' ] && idnt="\n                            " && shift
         printf "$idnt%-15s %-15s %-15s %-15s" "$@"
     }
 
@@ -1652,7 +1664,7 @@ actionStatus() {
     ___status_homedns() {
         local name opti
         for name in "${CEN_NET_HOMEDNS[@]}" ; do
-            ___status_print $opti $name ; opti="-i"
+            ___status_print $opti $name ; opti='-i'
         done
     }
 
@@ -1669,6 +1681,17 @@ actionStatus() {
         CEN_NET_ADDR_IPLIST $(___status_print ${CEN_NET_ADDR_IPLIST[@]})
 
 !EOF
+    if [ -n "$CEN_NET_NETWORKS" ] ; then
+        local inet iext
+        netmask "$CEN_NET_NETWORKS" "${CEN_NET_EXTERNAL%/*}" && iext="(subnet)"
+        netmask "$CEN_NET_EXTERNAL" "${CEN_NET_NETWORKS%/*}" && inet="(subnet)"
+        create -c <<!EOF
+        CEN_NET_NETWORKS    $(___status_print "$CEN_NET_NETWORKS" "$inet")
+        CEN_NET_EXTERNAL    $(___status_print "$CEN_NET_EXTERNAL" "$iext")
+
+!EOF
+    fi
+
     if ! netserver ; then
         echo -e "    No network status file: $CEN_NET_FILE_STAT\n"
         return
@@ -1713,8 +1736,8 @@ actionSwitch() {
         else
             netlink -k -m '/etc/nsswitch.conf' '.' "$snam"
         fi
-        [ $? = 0 -a -n "$_netlink" ] && nscd="-f"
-        [ -n "$nscd" ] && message "nsswitch.conf switched to: $_netlink_suff"
+        [ $? = 0 -a -n "$_netlink" ] && nscd='-f'
+        [ -n "$nscd" ] && message -c "nsswitch.conf switched to" "$_netlink_suff"
     fi
 
     # switch /etc/hosts and (re)create resolv.conf
@@ -1740,16 +1763,17 @@ actionValidate() {
     cac*)   coca=1 ;;
     lis*)   DAT_LIST=1 ;;
     noc*)   ;;
-    *)      set -x ; invoke -a 'cache|nocache|list' ; return
+    *)      invoke -a 'cache|nocache|list' ; return
     esac
     do_config -v
-    error -t || args="Error(s) found"
     [ -n "$DAT_LIST" ] && return
+
+    error -t || args="Error(s) found"
+    message "File '$CEN_OPT_CONFIG' [$DAT_CONFIG_LINES lines]: $args"
+    error -t || return
 
     local name="'${CFG_SERVER_DEF}.$CEN_NET_DOMAIN'"
     [ -n "$CFG_SERVER_DEF" ] || name="(none)"
-    message "File '$CEN_OPT_CONFIG' [$DAT_CONFIG_LINES lines]: $args"
-    error -t || return
     message -i -p "Server %-10s =>  %s" "'$CEN_NET_SERVER_GEN'" "$name"
     message -i -p "Router %-10s =>  '%s'" "'$CEN_NET_ROUTER_GEN'" "${CEN_NET_ROUTER_DEF}.$CEN_NET_DOMAIN"
     [ -n "$coca" ] && do_coca
diff --git a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
--- a/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
+++ b/dists/bookworm/dynamic/var/centauri/configs/bookworm/@admin/tools/centauriroute
@@ -149,19 +149,19 @@ do_addrchk() {
         fi
     fi
 
-    [ "$_addrchk_ipvx" = 4 ] && return 0            # using ipv4 only
+    [ "$_addrchk_ipvx" = 4 ] && return 0            # using IPv4 only
     if ! do_ipv6chk ; then
         if [ -z "$now6" -a "$CEN_ACTION" != 'open' ] ; then
-            [ -z "$DAT_IPV6_NOWARN" ] && invoke -w "ipv6 is not enabled for this host"
+            [ -z "$DAT_IPV6_NOWARN" ] && invoke -w "IPv6 is not enabled for this host"
             DAT_IPV6_NOWARN=1
         fi
     elif [ "$ifce" != '-' ] && ! nettool -6 -d "$_addrchk_ifce" status ; then
-        [ -z "$now6" ] && invoke -w "ipv6 is not enabled for:" "$ifce"
+        [ -z "$now6" ] && invoke -w "IPv6 is not enabled for:" "$ifce"
     else
-        return 0                                    # ipv6 is ok
+        return 0                                    # IPv6 is ok
     fi
     [ "$_addrchk_ipvx" = 6 ] && return 1            # cannot run
-    _addrchk_ipvx=4 ; return 0                      # use ipv4 only
+    _addrchk_ipvx=4 ; return 0                      # use IPv4 only
 }
 
 # -----------------------------------------------------------------------------
@@ -188,7 +188,7 @@ do_address() {
         *)      iopt='delete'
     esac
 
-    if [ "$ipvx" != 6 ] ; then                          # ipv4 address
+    if [ "$ipvx" != 6 ] ; then                          # IPv4 address
         nettool -q -a -4 -d "$ifac:0" "$iopt" "$neti" $flag
     fi
 
@@ -430,7 +430,7 @@ do_config() {
         ___ifce_names "$@" ; DAT_SWITCH_IFACES="${list[*]}"
         ___ifce_names "${DAT_OPEN_BRIDGE[@]}" ; DAT_OPEN_BRIDGE=("${list[@]}")
         ___ifce_names "${DAT_OPEN_PROXY[@]}" ; DAT_OPEN_PROXY=("${list[@]}")
-        set -f ; set -- $DAT_SWITCH_WLAN ; set +f
+        set -f ; set -- $DAT_OPEN_WLAN ; set +f
         ___ifce_names "$@" ; DAT_OPEN_WLAN="$list"
         if [ "$DAT_OPEN_DIAL" = 'wlan' ] ; then
             ___ifce_names "${DAT_OPEN_DIAL[1]}" ; DAT_OPEN_DIAL[1]="$list"
@@ -478,6 +478,7 @@ do_external() {
     #            1 : try 3 then 2
     local indx="${1#*-}" name="${1%-*}"
     [ "$indx" = 0 ] && indx=1 || indx=2
+
     # do not add an address if external is a subnet of the inner net ...
     if nethost "$name-$indx" && ! netmask "$CEN_NET_EXTERNAL" "$_nethost_ip" ; then
         $CEN_TRACE2 -a -c "External addr" "$1 -> $_nethost_ip [$indx]"
@@ -487,7 +488,12 @@ do_external() {
         $CEN_TRACE2 -a -c "External addr" "$1  =>  <is subnet>"
         return 1
     fi
-    nettool -d "$2" -w -o add "$CEN_NET_EXTERNAL"
+
+    # these may fail, a route may already exist ...
+    nettool -d "$2" -w -o add "$CEN_NET_EXTERNAL" &&
+        message -a -p "Added route '%s' via '%s'" "$CEN_NET_EXTERNAL" "$2"
+    nettool -d "$2" -q -o add "$CEN_NET_NETWORKS" &&
+        message -a -p "Added route '%s' via '%s'" "$CEN_NET_NETWORKS" "$2"
 }
 
 # -----------------------------------------------------------------------------
@@ -525,7 +531,7 @@ do_ifexists() {
 }
 
 # -----------------------------------------------------------------------------
-# Check if ipv6 is enabled for some host: <host>|-
+# Check if IPv6 is enabled for some host: <host>|-
 # -----------------------------------------------------------------------------
 do_ipv6chk() {
     local host="${1%-[0-9]}"
@@ -541,7 +547,7 @@ do_ipv6chk() {
         netoption 'ipv6' "$host" ; DAT_IPV6_HOST="$host:$?"
     fi
     [ "${DAT_IPV6_HOST#*:}" = 0 ] && return 0
-    trace -a -p "No ipv6 for host: %s" "$host" ; return 1
+    trace -a -p "No IPv6 for host: %s" "$host" ; return 1
 }
 
 # -----------------------------------------------------------------------------
@@ -646,7 +652,7 @@ do_gateway() {
     do_addrchk -d -h -- "$1" "$2" "$3" || return 1
     trace -a -c "gateway host" "${_nethost_name:--unknown-}  $_nethost_ip  $_nethost_mac"
 
-    # for an ipv6 route we need the router's mac to generate a link local IPv6 address
+    # for an IPv6 route we need the router's mac to generate a link local IPv6 address
     if [ "$_addrchk_ipvx" != 4 ] ; then
         if [ "${_nethost_mac:--}" = '-' ] ; then    # try to get mac via arp ...
             local list item
@@ -667,22 +673,23 @@ do_gateway() {
             netconv -m "$_nethost_mac"
         fi
         if [ -z "$_netconv" ] ; then
-            local mesg="Got no mac address for ipv6 route, please add in configuration:"
+            local mesg="Got no mac address for IPv6 route, please add in configuration:"
             if [ "$_addrchk_ipvx" = 6 ] ; then
                 invoke -e "$mesg" "$1" ; return 1
             fi
             invoke -w "$mesg" "$1" ; _addrchk_ipvx=4
-            nettool -6 -w && message "Disabled Iov6 due to unreachable gateway"
+            nettool -6 off && message "Disabled IPv6 due to unreachable gateway"
         fi
     fi
 
+    # adding a gateway fails if the interface has no address in the dest. subnet
     if [ "$_addrchk_ipvx" != 6 ] ; then
-        nettool -4 -i route flush default
-        nettool -4 -i route add default via "$_nethost_ip" dev "$_addrchk_ifce"
+        nettool -4 -o flush default
+        nettool -4 -w -o add default via "$_nethost_ip" dev "$_addrchk_ifce"
     fi
     if [ "$_addrchk_ipvx" != 4 ] ; then
-        nettool -6 -i route flush default
-        nettool -6 -i route add default via "$_netconv" dev "$_addrchk_ifce"
+        nettool -6 -o flush default
+        nettool -6 -w -o add default via "$_netconv" dev "$_addrchk_ifce"
     fi
     return 0
 }
@@ -1048,9 +1055,9 @@ do_service() {
 # ------------------------------------------------------------------------------
 # replace metric in routes: system|sysrun -4|-6 <ifce> <metr> <wait>
 # ------------------------------------------------------------------------------
-# Notes:    ipv6 route metrics are a nightmare
-#           for ipv4 we use ifmetric if it is installed
-#           setting ipv6 addresses does do not create routes synchronously
+# Notes:    IPv6 route metrics are a nightmare
+#           for IPv4 we use 'ifmetric' if it is installed
+#           setting IPv6 addresses does do not create routes synchronously
 # ------------------------------------------------------------------------------
 do_setmetric() {
     local scmd="$1" imod="$2" ifce="$3" metr="$4"
@@ -1058,7 +1065,7 @@ do_setmetric() {
     # optional sleep
     [ "${5:-0}" != 0 ] && timer -w "$5"
 
-    # for ipv4 'ifmetric' would be faster ...
+    # for IPv4 'ifmetric' would be faster ...
     if [ "$imod" = '-4' ] && sysfind -c 'ifmetric' ; then
         $scmd -- ifmetric "$ifce" "$metr" ; return  # return status
     fi
@@ -1109,7 +1116,7 @@ do_setmetric() {
     $scmd -e -p -- ip $imod route flush table all dev "$ifce"
     set -f
 
-    # ipv4 routes have dependencies, let 'ip' handles this via retrying
+    # IPv4 routes have dependencies, let 'ip' handles this via retrying
     if [ "$imod" != '-6' ] ; then
         alst=()
         for item in "${nlst[@]}" ; do
@@ -1172,7 +1179,7 @@ do_open() {
         netoption 'dns'  || error "Mode 'router' depends on 'option dns'"
         netoption 'dhcp' || error "Mode 'router' depends on 'option dhcp'"
         if netoption 'ipv6' ; then
-            message -a "Mode 'router' disables ipv6 to allow NAT"
+            message -a "Mode 'router' disables IPv6 to allow NAT"
             nettool -6 off ; DAT_IPV6_NOWARN=1
         fi
     fi
@@ -1205,8 +1212,11 @@ do_open() {
     # set '4addr' mode of wlan client in bridge
     local wdev="${DAT_OPEN_WLAN%% *}" wcfg="${DAT_OPEN_WLAN#* }"
     [ "$wcfg" = "$wdev" ] && wcfg="$CEN_NAME"
-    netiface -k -s wdev -x -- "$wdev"
-    [ -z "$wdev" ] && wdev='none'
+    if [ -z "$wdev" ] ; then
+        trace -a "No WLAN configured" ; wdev='none'
+    elif ! netiface -k -s wdev -x -- "$wdev" ; then
+        warning "Configured WLAN not found:" "$DAT_OPEN_WLAN" ; wdev='none'
+    fi
 
     # client wlan in bridge must be in '4addr' mode
     if [ "$ibri" = 'none' ] ; then
@@ -1265,7 +1275,10 @@ do_open() {
         [ "$DAT_SWITCH_MODE" = 'switch' -o "$DAT_SWITCH_MODE" = 'router' ] &&
             do_homedns add "$ibri"                  # add an extra homedns address
 
-        # adding the gateway fails if bridge has no matching address assigned...
+        # adding the gateway fails if bridge has no matching address assigned, so
+        # so to be safe (re-)add the generic address which might already be set ...
+
+        do_address add - - - "$ibri"                # add generic address
         do_gateway "$CEN_NET_ROUTER_DEF" "$ibri"
         actionMetric "$ibri" - 200 +
     fi
@@ -1287,7 +1300,7 @@ do_open() {
             nettool -6 status ||
                 warning "interface mode 'static' without bridge: no IPv6 support"
         else                                            # server with brigde ...
-            local item imac                             # add ipv6 addresses to...
+            local item imac                             # add IPv6 addresses to...
             ifce="$ibri"                                # ... the bridge (not the slaves)
             netgetip -6                                 # get known addresses
             for item in "$HOSTNAME" "$HOSTNAME-0" "$HOSTNAME-1" ; do
@@ -1300,7 +1313,7 @@ do_open() {
                     do_address add "$_nethost_name" "$_nethost_ip" "$_nethost_mac" "$ifce" 6
                 fi
             done
-            # set bridge mac
+            # set bridge mac (allowing firewall rules to filter by mac)
             message -a -p "Bridge '%s' mac address: %s" "$ifce" "${imac:--unknown-}"
             [ -n "$imac" ] && nettool -d "$ifce" -i link set address "$imac"
         fi
@@ -1696,13 +1709,13 @@ do_udev() {
 # -----------------------------------------------------------------------------
 # add/remove addresses: add|delete <host>|- [<ifce> [ipv4|ipv6|+|-]]
 #
-#   <host>  name or ipv4 address (not ipv6!)
+#   <host>  name or IPv4 address (not IPv6!)
 #   <ifce>  internal interface name like eth0, wlan1, ...
-#   ipv ... specify ipv4/6 behaviour (default: ipv4):
-#           ipv4|4  ipv4 only
-#           ipv6|6  ipv6 only
-#           -       ipv4, ipv6 if enabled
-#           +       like '6' but no ipv6 warning, and for static interface mode:
+#   ipv ... specify IPv4/6 behaviour (default: ipv4):
+#           ipv4|4  IPv4 only
+#           ipv6|6  IPv6 only
+#           -       IPv4, IPv6 if enabled
+#           +       like '6' but no IPv6 warning, and for static interface mode:
 #                            add generic ip to 1st calling interface
 # ------------------------------------------------------------------------------
 actionAddr() {
@@ -1723,8 +1736,10 @@ actionAddr() {
             host="$_nethost_name"
     esac
 
-    do_addrchk - "$ifce" "$mipv" || return
+    do_addrchk - "$ifce" "$mipv" || return          # address already set
+
     if [ "$mipv" = '+' ] ; then
+        trace -a -p "Add generic address to '%s'" "$_addrchk_ifce"
         case "$_addrchk_ifce" in
         wl*)    local wtim                          # wait until carrier ...
                 for wtim in 1 2 3 4 5 6 7 8 9 10 ; do
@@ -1736,6 +1751,121 @@ actionAddr() {
         esac
     fi
     do_address "$mode" "$host" - - "$_addrchk_ifce" "$_addrchk_ipvx"
+}
+
+# -----------------------------------------------------------------------------
+# add/remove arp entries: add|delete|list [<host> [<maca>|-]]
+#
+#   <host>  name or IPv4 address (not IPv6!)
+#   <maca>  mac address of a single <host> (can be '-' for delete)
+# ------------------------------------------------------------------------------
+actionArp() {
+    local mode host="${2:--}" maca="$3" lall
+
+    case "$1" in
+    add)    mode=$"add" ;;
+    del*)   mode=$"delete" ;;
+    lis*)   ;;
+    *)      invoke -a 1 $"add|delete|list" ; return
+    esac
+
+    # add/delete a sing arp entry
+    ___arp_entry() {
+        local mesg
+        if [ "$mode" = $"add" ] ; then
+            [ "${2:--}" = '-' ] && return
+            if sysrun -q -s mesg -- arp -s "$1" "$2" ; then
+                message -a -c $"Added entry" "$1" "$2"
+            else
+                message -a -c $"Adding failed" "$mesg"
+            fi
+        else
+            if sysrun -q -s mesg -- arp -d "$1" ; then
+                message -a -c $"Deleted entry" "$1"
+            else
+                message -a -c $"Delete failed" "$mesg"
+            fi
+        fi
+    }
+
+    local list item wrds ; local -A hmap
+    case "$host" in
+    -)          lall=1 ;;
+    .)          list=("$HOSTNAME" "$HOSTNAME-0" "$HOSTNAME-1" "$HOSTNAME-2" "$HOSTNAME-3") ;;
+    *-[0-9])    list=("$host") ;;
+    *)          list=("$host" "$host-0" "$host-1" "$host-2" "$host-3") ;;
+    esac
+
+    if [ -n "$lall" ] ; then                        # list all
+        if [ -n "$mode" ] ; then
+            invoke -e $"Need <host> argument to %s arp entries" "$mode" ; return
+        fi
+    elif [ -n "$maca" ] ; then                      # add/delete single entry
+        ___arp_entry "$list" "$maca" ; return
+    else
+        # add aliases to list
+        nethost -- "$list" || return
+        hmap["${_nethost_name//-/ }"]="$_nethost_mac"
+        list=("${list[@]:1}" "${_nethost_name[@]}")
+
+        # get mac addresses
+        for item in "${list[@]}" ; do
+            [ -n "${hmap["${item//-/ }"]}" ] && continue
+            nethost -- "$item" || continue
+            hmap["${_nethost_name//-/ }"]="$_nethost_mac"
+        done
+    fi
+
+    # add/delete entries for <host>
+    if [ -n "$mode" ] ; then
+        txtsort -a list -- "${!hmap[@]}"
+        for host in "${list[@]}" ; do
+            maca="${hmap["$host"]}"
+            host="${host// /-}"
+            ___arp_entry "$host" "$maca"
+        done
+        return
+    fi
+
+    # print list of arp entries
+    system -a list -e -p -r -- arp || return
+    txtgrep -a list -i list -y '* ether *'
+    txtsort -a list -i list
+
+    local head=$"Host_____________  Arp______________  Config___________  Interface"
+    local hcnt=0 macc
+    for item in "${list[@]}" ; do
+        splitjoin -s wrds -d " \t" -- "$item"
+        host="${wrds[0]}"
+        if [ "${host//[0-9]/}" = '...' ] ; then
+            nethost -- "$host" && host="$_nethost_name"
+        else
+            host="${host%%.*}"
+        fi
+        if [ -z "$lall" ] ; then
+            macc="${hmap[${host//-/ }]}"
+            [ -n "$macc" ] || continue
+        else
+            nethost -- "$host" ; macc="$_nethost_mac"
+        fi
+        if [ "${wrds[2]}" = "$macc" ] ; then
+            macc=$"<ok>"
+        elif [ "${macc:--}" = '-' ] ; then
+            macc=$"<unknown>"
+            nethost "${wrds[2]}" && macc="$_nethost_name"
+        fi
+
+        if [ "$hcnt" = 0 ] ; then
+            message -- "${head//_/ }"               # title text
+            message -a -- "${head//[! ]/-}"         # header line
+        fi ; ((hcnt += 1))
+        message -a -p '%-18s %-18s %-18s %s' "$host"  "${wrds[2]}" "$macc" "${wrds[4]}"
+    done
+    if [ "$hcnt" = 0 ] ; then
+        message -a $"No matches"
+    else
+        message -a -- "${head//?/=}"                # footer line
+    fi
 }
 
 # ------------------------------------------------------------------------------
@@ -1821,13 +1951,13 @@ actionIpv6() {
     esac
 
     if [ "$mode" = 'chk' ] ; then
-        local item know=0               # 0 no change,  1 disable ipv6, 2 ipv6 ok
+        local item know=0               # 0 no change,  1 disable IPv6, 2 IPv6 ok
         netresolv -r
         for item in "${_netresolv[@]:1}" ; do
             $CEN_TRACE2 -a -c "IPv6 dns server" "$item"
             nethost -- "$item" || continue                  # unknown host
             know=1
-            netoption 'ipv6' "$_nethost_name" || continue   # no ipv6
+            netoption 'ipv6' "$_nethost_name" || continue   # no IPv6
             $CEN_TRACE2 -a -c "IPv6 check" "$_nethost_name"
             if ! sysrun -q -r -- ping -6 -c1 -q "$_nethost_name" ; then
                 timer -w 1
@@ -1862,7 +1992,7 @@ actionMetric() {
     if [ "${metr:--}" = '-' ] ; then
         do_metric metr "$host" "$1" "$_addrchk_ifce"
     fi
-    message -a "Setting metric for '$1' to '$metr'"
+    message -a -c "setting metric" "iface '$1' to '$metr'"
 
     [ "$_addrchk_ipvx" != 6 ] && do_setmetric 'sysrun' -4 "$_addrchk_ifce" "$metr"
     if [ "$_addrchk_ipvx" != 4 ] ; then
@@ -1871,7 +2001,7 @@ actionMetric() {
         else
             # change cgroup to root to avoid getting killed from systemd
             background -c $$ '/' || CEN_QUIT_WSUB=1
-            # must defer ipv6 a little bit until routes are set
+            # must defer IPv6 a little bit until routes are set
             background -s do_setmetric 'sysrun' -6 "$_addrchk_ifce" "$metr" "$wait"
         fi
     fi
@@ -2171,6 +2301,8 @@ actions() {
     # other commands
     add*)
         invoke -r 'addr'   -            1 4 ;;
+    arp)
+        invoke -r -        -            1 3 ;;
     ext*)
         invoke -r 'extender' -          3 3 ;;
     gat*)
@@ -2201,13 +2333,15 @@ usage() {
     usageset \
         -a 'addr   add|delete|extern <host>|<addr> <inam> [ipv4|ipv6|+|-' \
         -a -                     "add/remove an address to/from interface" \
+        -a 'arp    add|delete|list [<host> [<maca>|-]]' \
+        -a -                     "add/remove/list arp entries manually" \
         -a 'extender start|stop|status <itnk> <inam>' \
         -a -                     "bridge local interface to trunk via arp/dhcp proxy" \
         -a 'gateway <host>|<addr>|- [<inam>|- [[ipv4|ipv6|-]' \
         -a -                     "set default gateway or delete if <host> is '-'" \
         -a 'init   [<mode> [<conf>]]' \
         -a -                     "like 'mode', do setups, used by centauriswitch" \
-        -a 'ipv6   [<stat>]'     "show or set the ipv6 state of this computer" \
+        -a 'ipv6   [<stat>]'     "show or set the IPv6 state of this computer" \
         -a 'metric <inam> [<host> [<metr> [ipv4|ipv6|- [<wait>]]]]' \
         -a -                     "set metric for a route of an interface" \
         -a 'mode   [<mode> [<conf>]]' \
@@ -2236,10 +2370,6 @@ $CEN_USE_OPTIONS
 $CEN_USE_ACTIONS
 
 arguments:
-       <addr>      An Ipv4 address
-       <host>      A host name (must be defined in centaurinetcfg)
-       <inam>      An internal interface name
-       <itnk>      An trunk interface name (this network runs dhcp)
        <mode>      The computer's network mode (default: static)
                    °   disabled - centauri[switch|filter|secrets] are off
                    °   static   - only centauri[filter|secrets] are on
@@ -2250,6 +2380,12 @@ arguments:
        <conf>      The suffix of a $DAT_ETC_DIR/network/interfaces configuration;
                    °   <mode> is used if not specified. Only the <mode>s static,
                    °   switch and router are allowed to set <conf>.
+
+       <addr>      An Ipv4 address
+       <host>      A host name (must be defined in centaurinetcfg)
+       <inam>      An internal interface name
+       <itnk>      An trunk interface name (this network runs dhcp)
+       <maca>      A MAC address for a single <host> (can be '-' for delete)
        <serv>      A DNS name or IP address
        <stat>      Must be one of: on|off|auto|status
        <time>      wait time (floating point) in [s]
